umbraco/Umbraco.CMS.Backoffice

- e2e/installer.spec.ts
- playwright.config.ts
- src/css/custom-properties.css
- src/installer/index.ts
- src/installer/installer-consent.element.ts
- src/installer/installer-database.element.ts
- src/installer/installer-error.element.ts
- src/installer/installer-installing.element.ts
- src/installer/installer-user.element.ts
- src/installer/installer.element.ts
- src/installer/installer.stories.ts
- src/mocks/domains/install.handlers.ts
This also introduces a new InstallerError component to display errors from the server. In the old backoffice we didn't really display validation errors but only crazy long stacktraces. This is now being handled a little more gracefully, but we might still have to introduce instance checking of the errors later on. For now we just have a `ProblemDetails` object, but we could have a `HttpValidationProblemDetails` object in the future and so on.
> Add e2e tests for installer

- .eslintrc.json
- src/app.ts
- src/backoffice/editors/data-type/editor-data-type.element.ts
- src/backoffice/editors/document-type/editor-document-type.element.ts
- src/backoffice/editors/document-type/views/editor-view-document-type-design.element.ts
- src/backoffice/editors/shared/node/editor-node.element.ts
- src/backoffice/editors/shared/node/views/edit/editor-view-node-edit.element.ts
- src/backoffice/editors/shared/node/views/info/editor-view-node-info.element.ts
- src/backoffice/trees/data-types/tree-data-types.element.ts
- src/backoffice/trees/document-types/tree-document-types.element.ts
- src/backoffice/trees/documents/tree-documents.element.ts
- src/backoffice/trees/extensions/tree-extensions.element.ts
- src/backoffice/trees/media/tree-media.element.ts
- src/backoffice/trees/member-groups/tree-member-groups.element.ts
- src/backoffice/trees/members/tree-members.element.ts
- src/backoffice/trees/shared/context-menu/tree-context-menu-page-action-list.element.ts
- src/backoffice/trees/shared/context-menu/tree-context-menu-page.service.ts
- src/backoffice/trees/shared/tree-item.element.ts
- src/backoffice/trees/shared/tree-navigator.element.ts
- src/core/extension/create-extension-element.function.ts
- src/core/extension/extension.registry.ts
- src/core/services/modal/modal.service.ts
- src/core/services/notification/layouts/default/notification-layout-default.element.ts
- src/core/services/notification/layouts/default/notification-layout-default.test.ts
- src/core/services/notification/notification.stories.ts
- src/installer/database/installer-database.stories.ts
- src/installer/error/installer-error.stories.ts
- src/installer/installer.element.ts
- src/installer/installing/installer-installing.stories.ts
- src/installer/user/installer-user.stories.ts
Import statements can quickly become messy and one way to prevent that is with some linting. I have turned on the import order linting rule which now gives a warning if the import statements are not in the correct order.
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
eslint can fix most of the issues by running the script: `npm run lint:fix`
> Linting rule for import order

- src/backoffice/shared/collection/views/collection-view-media-grid.element.ts
- src/backoffice/users/current-user/current-user-history.store.ts
- src/core/backend-api/core/ApiError.ts
- src/core/extensions-api/registry/extension.registry.ts
Fixes runtime issues, where code is trying to manipulate data coming from Store/UniqueBehaviorSubject
> Do not manipulate data from a UniqueBehaviorSubject

- src/backoffice/shared/components/workspace-property/workspace-property.element.ts
Fixes observing label to set description => should observe _propertyContext.description
> Fixes label binding as description

- src/backoffice/settings/dashboards/settings-welcome/dashboard-settings-welcome.element.ts
Updated HTML for settings dashboard to use a grid of uui-box's to be more visually appealing.
Before this update, it was a very plain list of short descriptions and links, hopefully with a card/uui-box each in the grid with CTA buttons, makes it more visual appealing and likely people to use the links available to them.
> Updated Welcome Dashboard in Settings section

- .storybook/preview.js
- libs/element/context-provider.element.ts
enables to parse a method to the context-provider-element instead of the value.
` .create=${host => new UmbDocumentTypeDetailStore(host)`
> Create method to enable Contexts to be initialised with a host reference

- src/backoffice/shared/components/section/section-dashboards/section-dashboards.element.ts
Setting `height:100%` on `router-slot` inside `uui-scroll-container` causes UI issues when scrolling to the bottom of the scrollable container, as the router-slot padding-bottom is lost. slot should have its natural height, with overflow controlled by the parent scrollable container.
Also tidies other CSS in the component - no need to set width on block-level elements, flexing `#scroll-container` saves a rule.
> don't set height on scrollable router-slot

- .storybook/preview.js
We provided the modal service under the wrong alias. It is now changed to use the context token, so we don't end up in a spelling mistake again.
> Bugfix: Provide modals under the correct context token

- libs/context-api/context-token.ts
- src/backoffice/users/user-groups/workspace/user-group-workspace.context.ts
- src/backoffice/users/users/workspace/user-workspace.context.ts
This adds a TYPE property that allows you to get the inferred/generic type of a context token without importing the actual type elsewhere.
We can now also remove the `multi` function which was just left there in order not to get warnings because the generic T parameter was not used for anything else except to hold the type.
```typescript
class MyComponent extends UmbLitElement {
#notificationService?: typeof UMB_NOTIFICATION_SERVICE_CONTEXT_TOKEN.TYPE;
constructor() {
super();
this.consumeContext(UMB_NOTIFICATION_SERVICE_CONTEXT_TOKEN, (_instance) => { this.#notificationService = _instance; });
}
}
```
> add TYPE property to UmbContextToken to get the generic type

- src/backoffice/documents/document-types/repository/document-type.repository.ts
- src/backoffice/documents/document-types/repository/sources/document-type.tree.server.data.ts
- src/backoffice/documents/documents/repository/document.repository.ts
- src/backoffice/documents/documents/repository/sources/document.tree.server.data.ts
- src/backoffice/media/media/repository/sources/media.tree.server.data.ts
- src/backoffice/settings/data-types/repository/data-type.repository.ts
- src/backoffice/settings/data-types/repository/sources/data-type.tree.server.data.ts
This PR updates a couple of import paths to use the import alias instead of a relative path.
> Use import aliases when importing when the libs folder

- .github/workflows/npm-publish-github-packages.yml
- .gitignore
- libs/package.json
- package.json
- utils/move-libs.js
Use `web-component-analyzer` to generate the JSON format for VSCode for HTMLCustomData to help with completions.
`wca analyze src --format vscode --outFile vscode-html-custom-data.json`
https://github.com/microsoft/vscode-custom-data
https://github.com/microsoft/vscode-custom-data/tree/main/samples/webcomponents
https://code.visualstudio.com/api/extension-guides/custom-data-extension
The JSON file would need to be shipped as part of a NPM package then people would need to update their VSCode workspace settings file at `.vscode/settings.json`
This will only work in .html files and NOT inside other Lit based WebComponents in the html tagged literal.
I have raised an issue on the popular VSCode plugin `lit-plugin` to see if this would work.
https://github.com/runem/lit-analyzer/issues/300
> Use wca to generate the JSON format for VSCode for HTMLCustomData

- src/backoffice/media/media/repository/media.repository.ts
The media repository currently rely on ContextControllers to return a promise for initialisation. Unfortunatly that is not the case. I have swapped out the Promise.all with the temp initialise logic until we have found a generic solution.
This will fix a race condition, especially in the unit tests, where some of the methods on the repository are called before the contexts are received.
> Bugfix: fix context initialisation of media repository

- src/app.ts
In the app element we made two requests to get the init status of the app. That resulted in the backoffice element getting initialised twice. This PR removes one of the calls.
> Bugfix: Remove double request to get init status

- src/app.ts
#647 removed the duplicate `setInitStatus` call in the app element, but we need to keep the one in `connectedCallback` rather than the constructor as we need the OpenAPI configuration to be completed before attempting to fetch the initial status, else we don't have the base URL set.
> Keep other setInitStatus in app.ts

- src/backoffice/shared/modals/property-settings/property-settings-modal.element.ts
This removes the dot from the default email and URL regexes that can result in bad email addresses/URLs
The default validation allows _any_ character (UTF-8, emoji etc.) that are not valid in TLDs - I've seen a few instances of this being missed in the wild (it's been a problem in the Backoffice for a long time).
The old Backoffice actually defines this regex in code like this: `[a-zA-Z0-9_\.\+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-\.]+` but it's not properly escaped and gets transformed by the gulp build into `[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+`, which is wrong.
Create a new property editor, choose email or URL custom validation.
I appreciate that we want a best-case regex suitable for most users, and no regex is 100% for these kinds of things, but my edge-case spider-sense is tingling …
> Remove invalid dot from email and URL validation strings

- libs/entity-action/actions/delete-folder/delete-folder.action.ts
- libs/entity-action/actions/delete/delete.action.ts
- libs/entity-action/actions/move/move.action.ts
- libs/entity-action/actions/trash/trash.action.ts
- libs/repository/data-source/data-source-response.interface.ts
- libs/repository/data-source/index.ts
- libs/repository/data-source/move-data-source.interface.ts
- libs/repository/index.ts
- libs/repository/move-repository.interface.ts
- src/backoffice/settings/data-types/entity-actions/manifests.ts
- src/backoffice/settings/data-types/entity-actions/move/manifests.ts
- src/backoffice/settings/data-types/entity-actions/move/move.action.ts
- src/backoffice/settings/data-types/index.ts
- src/backoffice/settings/data-types/repository/data-type.repository.ts
- src/backoffice/settings/data-types/repository/sources/data-type-move.server.data.ts
- src/core/mocks/data/entity.data.ts
- src/core/mocks/domains/data-type/index.ts
- src/core/mocks/domains/data-type/move.handlers.ts
- src/core/mocks/domains/media.handlers.ts
Merge #651 first
This PR adds move functionality to the data type tree. 
**What to test:**
* Test that you can use the move action to move a data type into a folder.
**Known issues:**
* It is currently possible to move to other items than folders
* It is currently not possible to move to the root.
> Feature: Data Type Move Action

- vite.config.ts
Vite couldn't load the mocked extension beacuse the files were not copied to the public folder. The PR adds the App_Plugin files to be copied to bypass Vites dynamic import limit.
> Bugfix: Load plugins from mocked App_Plugins folder

- src/backoffice/settings/data-types/repository/sources/data-type.server.data.ts
The server complained about a missing values prop when creating new data types. I have added it to the scaffold so you can create a new data type without updating any of the config values in the UI.
> Bugfix: add all props to scaffold model

- libs/id/index.ts
- libs/modal/modal-handler.ts
- libs/modal/modal-route-registration.ts
- libs/notification/notification-handler.test.ts
- libs/notification/notification-handler.ts
- libs/utils/generate-guid.ts
- libs/utils/index.ts
- src/backoffice/documents/documents/repository/sources/document.server.data.ts
- src/backoffice/settings/data-types/repository/sources/data-type-folder.server.data.ts
- src/backoffice/settings/data-types/repository/sources/data-type.server.data.ts
- src/backoffice/shared/components/table/table.stories.ts
- src/backoffice/shared/components/workspace/workspace-context/entity-manager-controller.ts
- src/backoffice/shared/components/workspace/workspace-context/workspace-structure-manager.class.ts
- src/backoffice/templating/templates/repository/sources/template.detail.server.data.ts
- src/backoffice/translation/dictionary/repository/sources/dictionary.detail.server.data.ts
- src/core/mocks/data/entity.data.ts
- src/core/mocks/data/template.data.ts
- src/core/mocks/domains/package.handlers.ts
- src/core/mocks/domains/users.handlers.ts
- tsconfig.json
- web-test-runner.config.mjs
A small util to generate and validate ids. 
I realised too late that we already had one, but it was only used in a few places.
I have kept the naming to id, so it matches the code where we need to generate an id.
The util is made so we only have one reference to the uuid external package.
```ts
import { UmbId } from '@umbraco-cms/backoffice/id'
const id = UmbId.new();
const validId = UmbId.validate(id);
```
> Feature: UmbId Lib

- libs/extensions-registry/models/index.ts
- libs/extensions-registry/models/modal.model.ts
- src/backoffice/core/index.ts
- src/backoffice/core/modals/tree-picker/tree-picker-modal.element.ts
When doing the tree picker modals I started out with a kind type. I later switched to another solution. This is leftover files that didn't get cleanup up.
> Remove Tree Picker Modal Kind

- eslint-local-rules.cjs
- src/apps/app/app.element.ts
- src/libs/extension-api/load-extension.function.ts
- src/packages/core/workspace/workspace-editor/workspace-editor.element.ts
Ensures that dynamic imports use the same enforcement of file extensions as our traditional imports.
To ensure corrections like this:
> ESLint rule for Dynamic Imports

- src/apps/installer/database/installer-database.element.ts
The database types from the server has a int property designed for the sortOrder to ensure SQLite is first.
With this PR applied the installer will now show SQLite first as opposed to the Custom DB option (which is the first item in the array)
> Sort Database install types by sortOrder int value from server

- src/libs/extension-api/types.ts
34K lines down to about 2K lines.
Originally it was including a lot about HTMLElements, Window, Document, CSS attributes etc was way too generic and too much info.
Still need to improve the JSON Schema and ensure all properties have good descriptions or examples etc...
> ElementType & ClassType causing WAY too much info in JSON Schema

- src/packages/core/components/extension-slot/extension-slot.element.ts
- src/packages/core/section/section-default.element.ts
- src/packages/core/tree/tree.context.ts
- src/packages/core/tree/tree.element.ts
We had an issue of the tree not loading at first view.
this was because it was connected, disconnected and then connected.
This PR fixes so extension-slot updates at the right times, making it less likely to happen — hopefully not happen.
> Bug-fix: elements being connected-disconnected and then connected

- src/packages/core/property-actions/common/copy/property-action-copy.element.ts
- src/packages/core/workspace/workspace-property/workspace-property.context.ts
- src/packages/core/workspace/workspace-property/workspace-property.element.ts
- src/packages/documents/document-types/workspace/views/structure/document-type-workspace-view-structure.element.ts
- src/packages/documents/document-types/workspace/views/templates/document-type-workspace-view-templates.element.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
- src/packages/documents/documents/workspace/views/edit/document-workspace-view-edit.element.ts
- src/packages/templating/templates/components/input-template/input-template.element.ts
- src/packages/templating/templates/repository/manifests.ts
- src/packages/templating/templates/repository/sources/template.item.server.data.ts
- src/packages/templating/templates/repository/template-item.store.ts
- src/packages/templating/templates/repository/template.repository.ts
Its not possible to Publish with current end-points.
Instead this covers:
Displaying allowed child items
Display picked templates (And items store/Source for template item models)
Display tabs when 'root tab'(Content) and one tab.
How can Property Actions talk to the Property Editor.
> More tidying up

- .storybook/main.ts
Pointing to the Chromatic Storybook built exactly for the release commit. We can try later on to experiment getting Storybook to update automatically.
> add uui as ref to storybook

- src/packages/core/picker-input/picker-input.context.ts
- src/packages/media/media/repository/media.repository.ts
- src/packages/members/members/repository/member.repository.ts
- src/packages/settings/logviewer/repository/log-viewer.repository.ts
- src/packages/templating/stylesheets/repository/stylesheet.repository.ts
- src/shared/repository/repository-items.manager.ts
Cleans up old ways of making a init promise, instead using the asPromise() method for generating await init promises.
> use the asPromise() method for generating await init promises

- src/apps/app/app.element.ts
- src/shared/auth/auth.context.ts
- src/shared/auth/auth.interface.ts
Due to needs from the backend, we should not store any tokens on the installer, since they will be invalid anyway.
* extract auth initialization to another method and only invoke it if we are not in INSTALL state
* clear any cached tokens if we are in INSTALL state
> Remove tokens in INSTALL state

- src/packages/settings/dashboards/published-status/dashboard-published-status.element.ts
fix for #800 - add warning dialog to internal cache button on the settings published status dashboard. 
NOTE: Current CMS functionality does not include a warning dialog for this action so the dialog text is new.
> add warning dialog to internal cache button

- index.html
- src/apps/app/app.element.ts
- src/external/rxjs/index.ts
- src/libs/element-api/element.mixin.ts
- src/libs/extension-api/registry/extension.registry.ts
- src/libs/localization-api/manager.ts
- src/packages/core/localization/registry/translation.registry.ts
- src/shared/lit-element/lit-element.element.ts
we cannot have lit properties on the UmbElementMixin since we are not guaranteed it's a Lit element
> move lit properties to UmbLitElement

- src/rollup.config.js
We were missing the type declaration files for the external libs, which made it problematic to work with typescript. Ex. A package developers wants to extend some element from the UI Library.
The problem was that we deleted the entire external folder (including d.ts. files) when preparing the external libs for the browser through rollup.
I have made a small change that only removes the non browser compatible .js files, before creating the correct .js files. This leaves all the d.ts files behind and typescript is able to pick them up.
I have done a small prepack test of the final output which you can see in the screenshots below.
Be aware, if you set up a custom tsconfig.json file. `moduleResolution` should be set to `bundler` to support the exports field in the backoffice npm package.
> Bugfix: keep d.ts files for external libs

- src/packages/users/user-groups/workspace/user-group-workspace.context.ts
Currently, the user group workspace editor can't render a user group because it doesn't return anything from the getEntityType method. The result is that the workspace context never gets consumed.
This PR quick fixes the problem, and returns the 'user-group' entityType from the workspace context. Ideally, we should get the entity type from the User Group Repository, because a workspace could consist of multiple entity types, but I think we need to change this in many places.
> Bugfix: Return entity type from workspace context method

- src/apps/app/app.element.ts
- src/shared/auth/auth-flow.ts
When installing the Backoffice we didn't fetch the server configuration. That resulted in a js-error when the installation was done.
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/apps/app/app.element.ts#L122
I have added a call to always fetch the server configuration (unless auth is bypassed).
> Bugfix: Fix Missing server configuration in installer

- src/packages/core/content-type/content-type-property-structure-helper.class.ts
- src/packages/core/modal/common/property-settings/property-settings-modal.element.ts
- src/packages/core/modal/token/property-settings-modal.token.ts
- src/packages/documents/document-types/index.ts
- src/packages/documents/document-types/repository/document-type.store.ts
- src/packages/documents/document-types/repository/index.ts
- src/packages/documents/document-types/workspace/views/design/document-type-workspace-view-edit-properties.element.ts
- src/packages/documents/document-types/workspace/views/design/document-type-workspace-view-edit-property.element.ts
Ability to toggle Vary by Culture for a property on a document type.
This does depend on the Document Type setting, as it has to be set to Allow for vary by culture. But the way this is written it only works when the document type has been saved. This must be solved later when we have made a proxy for the context consumption event, so it can reach a context from a parent layer/modal, so solve getting the draft version in another way.
> Vary by culture toggle

- src/packages/settings/dashboards/performance-profiling/dashboard-performance-profiling.element.ts
The profiling toggle will now not toggle in case of API error, to reflect the current status.
Also added localizations.
> profiling reflecting correct status

- src/packages/documents/documents/repository/sources/document.server.data.ts
For some reason, we sent the wrong model to the server which resulted in a validation error.
We should look into why TypeScript didn't complain about the wrong model being passed to the method. 
How to test:
* Test that it is possible to save a document.
> Bugfix: Save validation error - wrong update model passed to server

- src/packages/documents/documents/workspace/manifests.ts
A clean-up PR that removes the nonworking document workspace buttons for the preview release.
The PR also makes the save button green. Only because it is the only button now. We will change back later.
> Chore: Temp remove non working document workspace actions

- src/packages/core/localization/index.ts
- src/packages/core/localization/localize-date.element.ts
- src/packages/core/localization/localize-number.element.ts
- src/packages/core/localization/localize-relative-time.element.ts
- src/packages/core/localization/localize.element.ts
- src/packages/documents/documents/workspace/views/info/document-info-workspace-view.element.ts
I added type to the <umb-localize element... it should probably be individual elements instead, since the input "key" is weird for the input for dates, numbers etc... Could we reworked later!
> localize document-info

- src/packages/log-viewer/workspace/views/overview/components/log-viewer-saved-searches-overview.element.ts
This PR fixes the bug addressed in #885.
Removed `href` and used `inputQuery` state to persist the change in `inputQuery`. Replaced `/overview` path with `/search` to route the path to `/search` page.
> fix: fixed a bug related to search on log viewer page

- src/packages/core/components/input-markdown-editor/input-markdown.element.ts
- src/packages/core/modal/common/link-picker/link-picker-modal.element.ts
Toolbar and basic actions of Markdown Editor (PropertyEditor).
The toolbar has most actions, but not all. Press F1 or click the F1 button on the toolbar for all actions.
The actions are:
- Bold text
- Italic
- Heading (H1 - H6)
- Quote
- Ordered list
- Unordered list
- Code
- Fenced Code
- Linebreak
- Inserting links (via modal)
- Inserting image (via modal)
Some actions have additional logic behind them. Try selecting a string of text, use the bold text action vs not selecting any text, and then use the bold action.
Ordered list will automatically find the next number in the list when inserted or pressing enter.
> Markdown Edtior Actions

- package.json
- web-test-runner.config.mjs
A couple of paths were forgotten when the user group folder was renamed.
Please review this at the same time for the razor files in the CMS: https://github.com/umbraco/Umbraco-CMS/pull/14952
> Bugfix: Fix user group paths

- src/packages/core/workspace/workspace-action/common/save/save.action.ts
- src/packages/core/workspace/workspace-context/property-structure-workspace-context.interface.ts
- src/packages/core/workspace/workspace-context/saveable-workspace-context.interface.ts
- src/packages/core/workspace/workspace-context/variant-workspace-context.token.ts
- src/packages/core/workspace/workspace-context/workspace-context.interface.ts
- src/packages/core/workspace/workspace-context/workspace-context.token.ts
- src/packages/log-viewer/workspace/logviewer.context.ts
The interface for the workspace context had a lot of requirements that isn't needed. I have cleaned it up a bit, and moved most of them to the SaveableWorkspaceContext instead.
> Improvement: Simplify requirements for the workspace context interface

- .storybook/preview-head.html
- vite.config.ts
Storybook doesn't really work in the latest ui-api deployment. This should fix it.
> load msw from local to avoid storybook failures

- src/packages/log-viewer/workspace/logviewer/logviewer-workspace.element.ts
A minor typo in workspace editor alias in LogViewer workspace, which seems to be a leftover from a copy of dictionary workspace.
> Fix workspace editor alias in LogViewer

- src/packages/core/modal/common/link-picker/link-picker-modal.element.ts
- src/packages/documents/documents/index.ts
- src/packages/documents/documents/tree/index.ts
After a change in the document tree alias, the document picker inside the URL picker was missing. I have updated the code so it now uses an exported const from the document module.
It feels a bit off to import something from the document from within the core package, but it just shows that we need to have all property editors moved into individual (or combined for now) packages.
> Bugfix: Url picker missing document picker

- .storybook/preview.js
Fixes this issue: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/997
The refactoring of `UmbDocumentTypeStore` to `UmbDocumentTypeDetailStore` made Storybook throw errors.
> Fix import in preview.js to make Storybook work

- src/packages/documents/documents/entity-actions/permissions/permissions-modal.element.ts
- src/packages/user/user-group/components/input-user-group/user-group-input.element.ts
We were using the wrong attribute name to pass the icon name into an `uui-icon` element. This PR updates the code to use the correct attribute.
How to test
* Make sure that a user group ref renders an icon. (Test the user group picker on a user)
> Bugfix: Render User Group Ref icon

- src/packages/settings/languages/workspace/language-root/components/language-root-table-boolean-column-layout.element.ts
- src/packages/settings/languages/workspace/language-root/language-root-workspace.element.ts
Changes the language table to use checkmarks for boolean values instead of true/false
> Languages: Use checkmarks in table instead of true/false

- src/packages/core/data-type/workspace/data-type-workspace.element.ts
- src/packages/dictionary/dictionary/workspace/dictionary-workspace.element.ts
- src/packages/documents/document-types/workspace/document-type-workspace.element.ts
- src/packages/documents/documents/workspace/document-workspace.element.ts
- src/packages/media/media-types/workspace/media-type-workspace.element.ts
- src/packages/media/media/workspace/media-workspace.element.ts
- src/packages/members/member-groups/workspace/member-group-workspace.element.ts
- src/packages/members/member-types/workspace/member-type-workspace.element.ts
- src/packages/members/members/workspace/member-workspace.element.ts
- src/packages/settings/languages/workspace/language/language-workspace.element.ts
- src/packages/settings/relation-types/workspace/relation-type-workspace.element.ts
- src/packages/templating/partial-views/workspace/partial-view-workspace.element.ts
- src/packages/templating/scripts/workspace/script-workspace.element.ts
- src/packages/templating/stylesheets/workspace/stylesheet-workspace.element.ts
- src/packages/templating/templates/workspace/template-workspace.element.ts
- src/packages/user/user-group/workspace/user-group-workspace.element.ts
- src/packages/user/user/workspace/user-workspace.element.ts
make sure workspaces reinitializes all main routes when they change
some workspaces such as data type had a problem when you switched from one datatype to another that it wouldn't refresh the sub-routes
> fix: workspace router re-initialization

- src/packages/core/property-editor/schemas/Umbraco.Integer.ts
I'd noticed that "Integer" was named "Decimal" whilst browsing.
> Integer schema name correction

- src/packages/core/modal/common/tree-picker/tree-picker-modal.element.ts
- src/packages/documents/documents/components/input-document/input-document.element.ts
- src/packages/media/media/components/input-media/input-media.element.ts
Based on https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1012#issuecomment-1830837623 I've changed the button labels for buttons in the pickers and the associated modals.
Not all pickers in the issue is implemented so consider this a "partial" PR.
> #1012 label changes for pickers

- src/packages/core/modal/token/member-type-picker-modal.token.ts
- src/packages/members/member-types/components/index.ts
- src/packages/members/member-types/components/input-member-type/input-member-type.context.ts
- src/packages/members/member-types/components/input-member-type/input-member-type.element.ts
- src/packages/members/member-types/index.ts
- src/packages/members/member-types/manifests.ts
- src/packages/members/member-types/repository/index.ts
For development related to the Multinode Treepicker property-editor implementation, we needed a placeholder component for a member-type picker. I've added the basis for the `<umb-input-member-type>` component.
The code was largely duplicated from the `<umb-document-type-input>` component, but I didn't copy over the modal context code as that requires additional development work to implement the frontend code for the Member Type repository.
_(I've left the `#pickerContext`/`UmbMemberTypePickerContext` code in-place for ease when the implementation work is done.)_
> Member Type picker (`<umb-input-member-type>`)

- src/packages/members/manifests.ts
- src/packages/members/members/components/index.ts
- src/packages/members/members/components/input-member/input-member.element.ts
- src/packages/members/members/components/input-member/input-member.stories.ts
- src/packages/members/members/components/input-member/input-member.test.ts
- src/packages/members/members/index.ts
For development related to the Multinode Treepicker property-editor implementation, we needed a placeholder component for a member picker. I've added the basis for the `<umb-input-member>` component.
The code was largely duplicated from the `<input-document>` component, but I didn't copy over the modal context code as that requires additional development work to implement the frontend code for the Member repository.
_(I've left the `#pickerContext`/`UmbMemberPickerContext` code in-place (commented out), for ease when the implementation work is done.)_
> Member picker (`<umb-input-member>`)

- src/shared/utils/selection-manager/selection.manager.ts
Whilst working on the Tree Picker editor, I discovered an issue where the selected values always had an `undefined` as the first item in the array. I've pinpointed it down to how the Selection Manager is setting the initial selection/value.
When the modal initially opens, the `#multiple` is `false`, (regardless of how the `multiple` property/attribute is configured), so the initial value, e.g. `value[0]` gets set to `[undefined]`. Then when the `#multiple` is observed as `true`, _(there must be an underlying bug with the modal context code somewhere),_ then the `#selection` array would already have an initial value of `[undefined]` so any selected items would be appended that array.
This patch will check if the initial `value` (in `setSelection()`) has any items, if so, it'll use the …
> Selection manager: fixes initial value

- .github/localization_overview.md
- src/assets/lang/da-dk.ts
- src/assets/lang/en-us.ts
- src/packages/core/components/input-start-node/input-start-node.element.ts
- src/packages/core/property-editor/uis/tree-picker/config/start-node/property-editor-ui-tree-picker-start-node.element.ts
- src/packages/documents/documents/components/index.ts
- src/packages/documents/documents/components/input-document-picker-root/input-document-picker-root.element.ts
- src/packages/documents/documents/components/input-document-source/input-document-source.element.ts
Updates the Tree Picker's Start Node configuration to include a placeholder for the Dynamic Root functionality.
Introduces a `<umb-input-document-picker-root>` component for selecting the initial root node for the Multinode Treepicker editor.
> Tree Picker: Start Node / Document Picker Root

- src/packages/core/modal/common/link-picker/link-picker-modal.element.ts
- src/packages/core/modal/common/tree-picker/tree-picker-modal.element.ts
- src/packages/core/tree/tree.element.ts
- src/packages/dictionary/dictionary/entity-actions/import/import-dictionary-modal.element.ts
- src/packages/templating/modals/partial-view-picker-modal.element.ts
> **This supersedes pull-request #1098.**
Introduces a `selectionConfiguration` property (and new type `UmbTreeSelectionConfiguration`) to the `<umb-tree>` element.
As discussed on https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1098#issuecomment-1883001464, this property is a container for the required configuration of a tree-picker selection.
I have attempted to update the other uses of `<umb-tree>` that I could find within the codebase, namely the Multi-URL Picker editor, Import Dictionary modal and the Partial View Picker.
> Tree Element: Adds selection configuration property

- src/packages/core/property-editor/uis/tiny-mce/property-editor-ui-tiny-mce.element.ts
- src/packages/core/property-editor/uis/tiny-mce/property-editor-ui-tiny-mce.stories.ts
When creating a new document with an RTE, (against the Management API), the initial value is `undefined` and threw an error. So I have set the `value` to be nullable.
I've also updated the `value` data structure in the story.
> TinyMCE initial value (patch for PR #1105)

- src/packages/core/property-editor/uis/image-cropper/manifests.ts
Just a minor update to change icon of Image Cropper property editor to use crop icon instead of color picker icon.
Some else to consider.
- Change icon for dropdown to something else than time icon.
- Maybe toggle icon from Lucide icons as icon for Toggle property editor as it hasn't been a checkbox for a long time.
- Some other icon updates.
- Maybe all configuration editors should be under a "Configuration" group? And does it need configuration in name? Alternatively under a tab/app "Configuration" and a setting in manifest?
- Should there be a User Group Picker as well?
> Change icon of Image Cropper property editor

- src/packages/core/components/input-tree-picker-source/input-tree-picker-source.element.ts
- src/packages/core/property-editor/uis/tree-picker/config/source-picker/property-editor-ui-tree-picker-source-picker.element.ts
- src/packages/core/property-editor/uis/tree-picker/config/source-type-picker/property-editor-ui-tree-picker-source-type-picker.element.ts
- src/packages/core/property-editor/uis/tree-picker/property-editor-ui-tree-picker.element.ts
- src/packages/core/tree/components/input-tree/input-tree.element.ts
- src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
- src/packages/documents/documents/components/input-document/input-document.element.ts
- src/packages/media/media-types/components/input-media-type/input-media-type.element.ts
- src/packages/media/media/components/input-media/input-media.element.ts
- src/packages/members/member-types/components/input-member-type/input-member-type.element.ts
Current working state of the Multinode Treepicker property-editor.
This branch has merged/rebased on the features/patches from #1082, #1083, #1091, #1093, #1102. It is in a state to merge in the `main` branch, then any amends to specific areas can be made separately, (for fear of this specific PR getting too large).
> Multinode Treepicker property-editor amends

- src/packages/core/components/property-type-based-property/property-type-based-property.element.ts
- src/packages/core/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
- src/packages/core/data-type/components/ref-data-type/ref-data-type.element.ts
- src/packages/core/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
- src/packages/core/data-type/repository/detail/data-type-detail.server.data-source.ts
- src/packages/core/data-type/repository/detail/data-type-detail.store.ts
- src/packages/core/data-type/types.ts
- src/packages/core/data-type/workspace/data-type-workspace.context.ts
- src/packages/core/data-type/workspace/data-type-workspace.modal-token.ts
- src/packages/core/data-type/workspace/index.ts
- src/packages/core/data-type/workspace/views/info/workspace-view-data-type-info.element.ts
- src/packages/core/modal/token/workspace-modal.token.ts
A specific token for the data-type workspace modal
And then as part of my work i renamed the propertyEditorAlias fields to editorAlias, similar to the server model. That showed later not to be needed, but I think its okay to align. so kept it anyway.
> Datatype workspace modal token

- src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
- src/packages/media/media-types/components/input-media-type/input-media-type.element.ts
- src/packages/members/member-types/components/input-member-type/input-member-type.element.ts
Sets the icons for the selected content types in the Document Type, Media Type and Member Type pickers.
I've also normalized the `#renderItem` private method calls, (from `private` to `#` prefix).
> Content Type pickers - sets icons

- src/libs/extension-api/registry/extension.registry.ts
- src/packages/block/block-rte/workspace/views/manifests.ts
- src/packages/documents/manifests.ts
- src/packages/media/media-types/entity-actions/manifests.ts
This PR fixes an issue with the `registerMany` method on the extensionRegistry where it was possible to have multiple manifests in the same array with the same alias.
Now we ensure that each manifest is validated before registering the next.
> Bugfix: Prevent extension double registration

- src/packages/core/components/backoffice-notification-container/backoffice-notification-container.element.ts
This PR makes notifications alway be on top of the page by using the popover API.
Before, notifications would be hidden behind modals, sidebars, dialogs and so on.
Explanation:
This solution is a little hacky, as the only way for content be at the very top of the #top-layer is to be the most recently added element. So  we close and instantly open the popover (notification container) when a new notification is added. The closing and opening happens in the same frame/tick, so it is not visible.
> Make notifications always be on top of the page

- src/packages/core/property-editor/uis/tree-picker/property-editor-ui-tree-picker.element.ts
- src/packages/core/tree/components/input-tree/input-tree.element.ts
- src/packages/documents/documents/components/input-document/input-document.element.ts
- src/packages/media/media/components/input-media/input-media.element.ts
- src/packages/members/members/components/input-member/input-member.element.ts
For Multinode Treepicker, the "filter" option is passed in to the corresponding Document/Media/Member picker.
This is then used by the `pickableFilter` option on the Tree modal to filter out the selectable items.
For the Member picker, I've put placeholder code and commented out, (until the Member repository code has been implemented).
> Tree Picker: Pass in "filter" to picker

- src/packages/core/components/input-tiny-mce/input-tiny-mce.element.ts
Fixes this issue: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1019
Changed the `z-index` on the `.tox-editor-header` for TinyMCE - I've tested this quite a bit and could not find anything that was broken by this - might be missing something but hopefully not.
1. Before
2. After
> Lower z-index to not hide actions menu

- src/assets/lang/en-us.ts
- src/packages/core/modal/common/property-settings/property-settings-modal.element.ts
Partial PR for this issues: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/844
After this change the headline and buttons is "contextual" based on if we're adding or updating:
> #844 fixes headline and button label for content type edit property

- src/packages/core/modal/token/data-type-picker-flow-modal.token.ts
Fix for the data type picker modal size: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/846
> Make data type picker modal medium

- src/mocks/data/document/document.data.ts
- src/packages/core/components/input-multi-url/input-multi-url.element.ts
- src/packages/core/modal/common/link-picker/link-picker-modal.element.ts
- src/packages/core/modal/token/link-picker-modal.token.ts
- src/packages/core/property-editor/uis/tiny-mce/plugins/tiny-mce-linkpicker.plugin.ts
As part of the process to remove UDI support from the client UI, the Multi-URL Picker has re-introduced a "Link Type" property (of either `document`, `external` or `media`).
The Management API will support this change in due course.
> Multi-URL Picker: Removing UDI support

- examples/sorter-with-nested-containers/sorter-dashboard.ts
- examples/sorter-with-nested-containers/sorter-group.ts
- examples/sorter-with-two-containers/sorter-dashboard.ts
- examples/sorter-with-two-containers/sorter-group.ts
> beautify example

- src/packages/core/components/input-tree-picker-source/input-tree-picker-source.element.ts
- src/packages/documents/documents/components/index.ts
- src/packages/documents/documents/components/input-document-root-picker/input-document-root-picker.element.ts
A small follow up chore to PR #1164 (Dynamic Root), I wasn't happy with the naming of `input-document-picker-root`, as the editor is a picker of the "document root", not the root of the document picker, (a la "the cart before the horse").
I'm suggesting this as a separate change as I didn't want to pollute PR #1164.
> Rename `input-document-picker-root` to `input-document-root-picker`

- src/packages/core/property-editor/uis/collection-view/config/bulk-action-permissions/property-editor-ui-collection-view-bulk-action-permissions.element.ts
As part of reviewing the Collections (formerly List View) data-type configuration, I spotted a small bug in the bulk action permissions UI. The `allowBulkPublish` flag was checking the value of `allowBulkUnpublish`.
> Bugfix: Collection View Bulk Action Permissions - `allowBulkPublish` flag

- src/packages/documents/documents/workspace/document-workspace.context.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
This allows us to show a razor template on the frontend:
> add crude way to select a template

- src/packages/documents/documents/conditions/document-workspace-has-collection.condition.ts
- src/packages/documents/documents/conditions/index.ts
- src/packages/documents/documents/conditions/manifests.ts
- src/packages/documents/documents/index.ts
- src/packages/documents/documents/manifests.ts
- src/packages/documents/documents/workspace/manifests.ts
- src/packages/documents/documents/workspace/views/collection/document-workspace-view-collection.element.ts
This PR adds a Manifest Condition for the Document Workspace, to check if the Document Type is configured as a Collection (container) and display the Collection workspace view.
Note, this isn't fully wired up yet, as we are awaiting the relevant Management API endpoints, hence the TODO comments.
This PR contains the rest of the boilerplate code.
> Document Collection: Document Workspace Collection Condition

- devops/build/create-umbraco-package.js
- devops/importmap/index.js
- devops/package/meta.js
- devops/tsconfig/index.js
- package.json
- src/packages/core/extension-registry/umbraco-package.ts
- web-test-runner.config.mjs
Generate an umbraco-package.json file for the backoffice containing data useful to serve the backoffice such as the importmap.
There is now also a new definition added to the UmbracoPackage type to allow to define an importmap.
Fixes #1178
Note: When this is merged, we can also merge https://github.com/umbraco/Umbraco-CMS/pull/15710 to generate the importmap dynamically on the server.
> Generate umbraco package

- src/packages/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
- src/packages/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
Following up on a chat with @nielslyngsoe, I've swapped the `map` directive for `repeat`.
> Dynamic Root: Modal code tidy up

- src/packages/core/components/table/table.element.ts
The `item.icon` is `string | null`, which isn't handled by the `ifDefined()` check, so causes a Typescript error, so falls back on `undefined`.
Also amends CSS to vertically align the icon with the swappable checkbox.
> `umb-table` fix issue with `icon`

- src/packages/core/components/table/table.element.ts
- src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-name.element.ts
- src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-state.element.ts
- src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
Introduces the `UmbTableColumnLayoutElement` interface, for using custom elements for table cells within `umb-table`.
Adds table column layouts for the Document Collection item's `name` and `state`.
> Feature: `UmbTableColumnLayoutElement` interface

- src/packages/media/media/entity-bulk-actions/delete/delete.action.ts
- src/packages/media/media/entity-bulk-actions/manifests.ts
- src/packages/media/media/entity-bulk-actions/move/move.action.ts
Added "Collection Bulk Action Permission Condition" to Media's Entity Bulk Action manifests.
Also renamed the "Trash" action to "Delete", for consistency with the action name in the Documents package.
> Feature: Media Collection Entity Bulk Action Conditions

- src/packages/media/media/collection/index.ts
- src/packages/media/media/collection/manifests.ts
- src/packages/media/media/collection/media-collection.context.ts
- src/packages/media/media/collection/media-collection.element.ts
- src/packages/media/media/collection/repository/index.ts
- src/packages/media/media/collection/repository/manifests.ts
- src/packages/media/media/collection/repository/media-collection.repository.ts
- src/packages/media/media/collection/repository/media-collection.server.data-source.ts
- src/packages/media/media/collection/types.ts
- src/packages/media/media/manifests.ts
Adds the Media Collection repository and corresponding manifests, along with the associated element and context.
Note, the `umb-media-collection` element adds the placeholder for the media upload dropzone component, (currently non-functional).
> Feature: Media Collection Repository

- src/packages/media/media/manifests.ts
- src/packages/media/media/section-view/manifests.ts
- src/packages/media/media/section-view/media-section-view.element.ts
- src/packages/media/section.manifests.ts
- Updates the Media Section manifest
- Adds a Media Section View
- Removes the Media "dashboardCollection"
I'd appreciate a sanity check on these changes from @madsrasmussen and @nielslyngsoe, to make sure it is on the right track. Personally, I'm not 100% happy with the "media-management" section path.
> Feature: Media Section View

- src/mocks/data/media-type/media-type.data.ts
- src/mocks/data/media-type/media-type.db.ts
- src/mocks/handlers/media-type/index.ts
- src/mocks/handlers/media-type/structure.handlers.ts
Adds mock API for Media Type structure, e.g. `getAllowedAtRoot` and `getAllowedChildren`
This is to add mock data support for PR #1263.
> Adds mock API for Media Type structure

- src/packages/core/collection/index.ts
I wasn't sure whether to be specific with the exports or do a generic `export type * from './types.js';`?
---
Once this is merged in, I can mark PRs #1275 and #1277 as ready for re-review.
> Exports types for `UmbCollectionBulkActionPermissions` and `UmbCollectionConfiguration`

- src/packages/core/entity-action/entity-action.ts
- src/packages/core/entity-bulk-action/entity-bulk-action.ts
Ensures the `execute` method is on the base interface for both `UmbEntityAction` and `UmbEntityBulkAction`.
Resolves #1288.
> Entity Action: Adds the `execute` abstract method

- src/mocks/data/media-type/media-type.data.ts
- src/mocks/data/media-type/media-type.db.ts
- src/mocks/data/media/media.data.ts
- src/packages/core/property-editor/uis/collection-view/property-editor-ui-collection-view.element.ts
- src/packages/media/media/conditions/index.ts
- src/packages/media/media/conditions/manifests.ts
- src/packages/media/media/conditions/media-workspace-has-collection.condition.ts
- src/packages/media/media/index.ts
- src/packages/media/media/manifests.ts
- src/packages/media/media/repository/detail/media-detail.server.data-source.ts
- src/packages/media/media/types.ts
- src/packages/media/media/workspace/manifests.ts
- src/packages/media/media/workspace/media-workspace.context.ts
- src/packages/media/media/workspace/views/collection/media-workspace-view-collection.element.ts
- Adds mock data
- Adds Media workspace condition
- Adds Media workspace view for collection
- Updates existing Collection property-editor (to work with both Documents and Media)
> [!NOTE]
> We'll need to review how `<umb-property-editor-ui-collection-view>` is wired up, as it is currently hardcoded to be either Document or Media. Ideally, it should be abstracted to work with any Entity type that supports ContentType structures.
> To be discussed further...
> Feature: Media Collection UI (workspace and property-editor)

- src/packages/core/action/repository-action.ts
- src/packages/core/entity-action/entity-action.ts
Follow up to #1288 and #1291.
Adds the `getHref` method to the `UmbEntityAction<>` interface. The `UmbEntityActionBase` base class implements both the `getHref` and `execute` methods, and marks them with JSDocs `@abstract` to define them as overridable.
> Entity Action: Adds the `getHref` inteface method

- src/packages/core/models/index.ts
- src/packages/documents/documents/conditions/document-workspace-has-collection.condition.ts
- src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts
- src/packages/documents/documents/repository/item/document-item.server.data-source.ts
- src/packages/documents/documents/repository/item/types.ts
- src/packages/documents/documents/tree/document-tree.server.data-source.ts
- src/packages/documents/documents/tree/types.ts
- src/packages/documents/documents/types.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
- src/packages/media/media/conditions/media-workspace-has-collection.condition.ts
- src/packages/media/media/repository/detail/media-detail.server.data-source.ts
- src/packages/media/media/repository/item/media-item.server.data-source.ts
- src/packages/media/media/repository/item/types.ts
- src/packages/media/media/tree/media-tree.server.data-source.ts
- src/packages/media/media/tree/media-tree.store.ts
- src/packages/media/media/tree/types.ts
- src/packages/media/media/types.ts
- src/packages/members/member/repository/item/member-item.server.data-source.ts
- src/packages/members/member/repository/item/types.ts
We shouldn't reference by id as most models are mapped to a unique identifier.
This PR updates the models and the implementations to keep are models aligned.
> Bugfix: Reference by unique instead of id

- src/packages/core/property-editor/uis/text-box/property-editor-ui-text-box.element.ts
Sets a placeholder Config for the PropertyEditorUi TextBox
> Feature: PropertyEditorUI TextBox Config Placeholder

- src/libs/controller-api/controller-alias.type.ts
- src/libs/controller-api/controller.test.ts
- src/libs/extension-api/controller/base-extension-initializer.controller.test.ts
- src/libs/extension-api/controller/extension-api-initializer.test.ts
- src/libs/extension-api/controller/extension-element-initializer.test.ts
- src/libs/observable-api/observer.controller.test.ts
- src/libs/observable-api/observer.controller.ts
- src/libs/observable-api/utils/index.ts
- src/libs/observable-api/utils/simple-hash-code.function.ts
- src/packages/core/collection/collection-view.manager.test.ts
- src/packages/core/utils/selection-manager/selection.manager.test.ts
If implementor did not provide a controller alias for their observer, then this PR makes it use a hash code of the method provided for it. Making it clear up it self though the developer did not implement a controller alias.
> Use method hash for controller alias if not provided

- src/packages/core/property-action/shared/property-action-menu/property-action-menu.element.ts
- src/packages/core/workspace/components/index.ts
- src/packages/core/workspace/components/workspace-action-menu/index.ts
- src/packages/core/workspace/components/workspace-entity-action-menu/index.ts
- src/packages/core/workspace/components/workspace-entity-action-menu/workspace-entity-action-menu.element.ts
- src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts
- storybook/stories/extending/entity-actions.mdx
it is now called "workspace-entity-action-menu" which is more befitting for its placement and also allows us to re-use the name "workspace-action-menu" for the upcoming popover menu on workspace actions
> rename the workspace action menu

- src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
- src/packages/templating/templates/components/input-template/input-template.element.ts
- The document's status is now showed from the server instead of mock data
- Document's id is showed rather than the document type
- Can now open template and document type workspace
- Added localizations
- Template section in document type can also open the template workspace now.
- Removed the rollback button for each history item. Added the rollback button at the top of the uui-box with a TODO alert.
> Feature: Document Workspace Info Cleanup

- src/packages/media/media/collection/repository/media-collection.server.data-source.ts
- src/packages/media/media/section-view/media-section-view.element.ts
Updates to Media section-view collection as the server no longer needs a `dataTypeId` value for the Media root.
> Chore: Media Collection section-view amend (empties `dataTypeId` for server)

- src/assets/lang/da-dk.ts
- src/assets/lang/en-us.ts
- src/packages/core/components/index.ts
- src/packages/core/components/input-collection-configuration/index.ts
- src/packages/core/components/input-collection-configuration/input-collection-configuration.element.ts
- src/packages/core/content-type/types.ts
- src/packages/data-type/repository/index.ts
- src/packages/documents/document-types/repository/detail/document-type-detail.server.data-source.ts
- src/packages/documents/document-types/workspace/document-type-workspace.context.ts
- src/packages/documents/document-types/workspace/views/structure/document-type-workspace-view-structure.element.ts
Adds a new component `umb-input-collection-configuration` for picking an existing collection configuration (data-type), or to create a new one.
@nielslyngsoe may want to review my usage of the `UMB_DATA_TYPE_PICKER_FLOW_DATA_TYPE_PICKER_MODAL`, _(as the naming may feel wrong in this scenario)_.
The rest is to wire up the UI with the server calls to save the data.
> Feature: Document Type Structure - configure collection UI

- src/assets/lang/da-dk.ts
- src/assets/lang/en-us.ts
- src/packages/documents/document-types/workspace/views/structure/document-type-workspace-view-structure.element.ts
- src/packages/media/media-types/workspace/views/structure/media-type-workspace-view-structure.element.ts
Following on from https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1306#discussion_r1506289825, this PR adds and wires up the missing localization keys.
> Chore: Document Type Structure View localizations

- src/packages/core/property-editor/schemas/Umbraco.ContentPicker.ts
- src/packages/documents/documents/property-editors/document-picker/manifests.ts
Adds `ignoreUserStartNodes` setting to the server schema; and moves `startNodeId` to the UI settings, as it is not used by the server.
> Chore: Data Type Config clean-up: ContentPicker

- src/packages/core/property-editor/schemas/Umbraco.MultiNodeTreePicker.ts
- src/packages/core/property-editor/uis/tree-picker/manifests.ts
Moves the `startNode` setting to the schema, as this is used by the server.
> Chore: Data Type Config clean-up: MultiNodeTreePicker

- src/packages/core/property-editor/schemas/Umbraco.ListView.ts
- src/packages/core/property-editor/uis/collection-view/manifests.ts
Moves the unused schema fields, e.g. `pageSize`, `orderDirection`, `orderBy`, `bulkActionPermissions` to the UI settings.
The server only uses `includeProperties`.
> Chore: Data Type Config clean-up: List View

- src/packages/core/property-editor/schemas/Umbraco.RichText.ts
- src/packages/tiny-mce/property-editors/tiny-mce/manifests.ts
Moved `blocks` from the UI settings to the schema, as the server uses it.
Changed the `mediaParentId` field to use the MediaPicker UI instead of the generic TreePicker.
Additional work will need to be done to restrict the select to a Folder type only.
> Chore: Data Type Config clean-up: RichText

- src/packages/core/components/multiple-color-picker-input/multiple-color-picker-input.element.ts
- src/packages/core/property-editor/uis/color-swatches-editor/property-editor-ui-color-swatches-editor.element.ts
Whilst reviewing the ColorPicker configuration, I reviewed the Color Swatches Editor.
It appears that the `items` isn't being used within our codebase, but more that it didn't make sense, as it attempts to populate the `value`, which isn't a configuration. e.g. what would be populating it? (rather than setting the element's `value`?)
> Chore: Color Swatches Editor tidy-up/refactoring

- src/packages/core/property-editor/schemas/Umbraco.RadioButtonList.ts
- src/packages/core/property-editor/uis/radio-button-list/manifests.ts
Moves `items` from the UI to the schema settings, as they are used on the server.
> Chore: Data Type Config clean-up: RadioButtonList

- src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
- src/packages/core/property-editor/schemas/Umbraco.Dropdown.Flexible.ts
- src/packages/core/property-editor/uis/dropdown/manifests.ts
- src/packages/core/property-editor/uis/multiple-text-string/property-editor-ui-multiple-text-string.element.ts
Moves `multiple` and `items` from the UI to the schema settings, as they are used on the server.
Refactored MultipleTextString value structure, the server now sends back a `string[]` instead of an `MultipleTextStringValueItem[]`.
Also tidied up the MultipleTextString's sorter code whilst I was in there.
> Chore: Data Type Config clean-up: Dropdown

- src/packages/media/media/property-editors/image-crops-configuration/property-editor-ui-image-crops-configuration.element.ts
@iOvergaard I wasn't sure about this one. In the current backoffice the MediaPicker's `crops` setting has the "Label" field (per row), but our implementation in Bellissima does not.  Following a conversation with @kjac (a few weeks ago), I had a to-do note to include it.  We can discuss further.
> MediaPicker: Adds label field to the `crops` setting

- src/packages/block/block-grid/components/block-grid-area-config-entry/workspace/block-grid-area-type-workspace.context.ts
- src/packages/block/block-type/workspace/block-type-workspace.context.ts
- src/packages/block/block/workspace/block-workspace.context.ts
- src/packages/core/workspace/workspace-context/editable-workspace-context-base.ts
- src/packages/data-type/workspace/data-type-workspace.context.ts
- src/packages/dictionary/workspace/dictionary-workspace.context.ts
- src/packages/documents/document-types/workspace/document-type-workspace.context.ts
- src/packages/documents/documents/modals/pick-document-variant-modal.controller.ts
- src/packages/documents/documents/modals/variant-picker/document-variant-picker-modal.element.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
- src/packages/media/media-types/workspace/media-type-workspace.context.ts
- src/packages/media/media/workspace/media-workspace.context.ts
- src/packages/members/member-group/workspace/member-group-workspace.context.ts
- src/packages/members/member-type/workspace/member-type-workspace.context.ts
- src/packages/members/member/workspace/member-workspace.context.ts
- src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts
- src/packages/templating/scripts/workspace/script-workspace.context.ts
- src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts
- src/packages/templating/templates/workspace/template-workspace.context.ts
- src/packages/user/user/workspace/user-workspace.context.ts
* change saveComplete to workspaceComplete, for more clear purpose. As it should be called when a modal is ready to close.
* Fix saving and publishing of modals, so it only sends of the variants that was an actual option. — In this way we should also be ready to fit with permissions on variants.
> Fix document publishing variants

- src/packages/block/block-grid/property-editors/block-grid-editor/manifests.ts
- src/packages/block/block-grid/property-editors/block-grid-type-configuration/manifests.ts
- src/packages/block/block-list/property-editors/block-list-type-configuration/manifests.ts
- src/packages/block/block-type/property-editors/block-type-group-configuration/manifests.ts
- src/packages/core/components/input-number-range/input-number-range.element.ts
- src/packages/core/modal/common/property-settings/property-settings-modal.element.ts
- src/packages/core/property-editor/schemas/Umbraco.BlockGrid.ts
- src/packages/core/property-editor/uis/collection-view/config/bulk-action-permissions/manifests.ts
- src/packages/core/property-editor/uis/collection-view/config/column-configuration/manifests.ts
- src/packages/core/property-editor/uis/collection-view/config/layout-configuration/manifests.ts
- src/packages/core/property-editor/uis/collection-view/config/order-by/manifests.ts
- src/packages/core/property-editor/uis/number-range/manifests.ts
- src/packages/core/property-editor/uis/order-direction/manifests.ts
- src/packages/core/property-editor/uis/overlay-size/manifests.ts
- src/packages/core/property-editor/uis/tree-picker/config/source-picker/manifests.ts
- src/packages/core/property-editor/uis/tree-picker/config/source-type-picker/manifests.ts
- src/packages/core/workspace/components/variant-selector/variant-selector.element.ts
- src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
- src/packages/data-type/workspace/data-type-workspace.context.ts
- src/packages/media/media/property-editors/image-crops-configuration/manifests.ts
- src/packages/tags/property-editors/tags/config/storage-type/manifests.ts
- src/packages/tiny-mce/property-editors/manifests.ts
what it says + minor few render html corrections like adding label and moving getter/setter
Mainly this makes only the real property editors appear in the property editor picker modals. (real property editors, are property editors with a schema... )
> clean up property editor manifests

- src/packages/documents/documents/collection/views/index.ts
`creator` was missed off during the initial implementation. 🤦
> Bugfix: Document Collections: Adds `creator` to the views label lookup

- src/packages/core/extension-registry/collection/views/extension-table-action-column-layout.element.ts
Whilst testing out the remove action on the Extensions workspace, I'd noticed that they weren't being removed in the UI.
> Extension Workspace: Refreshs collection after removal action

- src/packages/templating/partial-views/tree/reload-tree-item-children/manifests.ts
- src/packages/templating/scripts/tree/reload-tree-item-children/manifests.ts
- src/packages/templating/stylesheets/tree/reload-tree-item-children/manifests.ts
File system files can't be nested. This PR removes the option to reload children of such.
> Bugfix: Remove option to reload children of file system file

- src/packages/templating/components/templating-item-menu/templating-item-menu.element.ts
- src/packages/templating/modals/templating-item-picker/templating-item-picker-modal.element.ts
- src/packages/templating/partial-views/workspace/partial-view-workspace-editor.element.ts
- src/packages/templating/stylesheets/components/stylesheet-rule-input/stylesheet-rule-input.element.ts
- src/packages/templating/templates/workspace/template-workspace-editor.element.ts
Remove console warnings when closing a modal (templating section)
> Bugfix: (Templating section) Remove console warnings when closing modal

- src/libs/controller-api/controller-host.mixin.ts
Improving the message in regards to the conversation with Matt who experienced this error.
> improve error message on Controller Destroy mistake

- src/libs/context-api/consume/context-consumer.ts
- src/libs/controller-api/controller-host.mixin.ts
- src/libs/element-api/element.test.ts
- src/packages/core/modal/common/property-settings/property-settings-modal.element.ts
Just a few minor updates.
renaming to skipHost is breaking, but I assume no one uses this jet.
> Rename to contextConsumer method to skipHost + one more test

- src/libs/class-api/class.interface.ts
- src/libs/class-api/class.mixin.ts
- src/libs/element-api/element.mixin.ts
- src/libs/element-api/element.test.ts
Correcting type case, to match the expected + correcting test.
The type correction is moving the | undefined, so the type extend test actually take undefined into account.
the test correction removes the hasController check as that is an illegal check when the controller is undefined.
> bugfix: Callback value type should be undefined-able where the given observable is undefined-able

- src/mocks/handlers/user/filter.handlers.ts
At one point the filter endpoints were change in the management api and we never got our mocks updated.
This PR updates the url to match the management api so we now can see mocked users in the collection
> Chore: update user filter request handler to use the correct path

- src/packages/core/router/generate-route-path-builder.function.test.ts
- src/packages/core/router/generate-route-path-builder.function.ts
Add support for having paramater-like segments of a url that shouldn't be replaced + tests
> Route parameters such as `uc:store` are being falsely replaced

- src/packages/data-type/tree/reload-tree-item-children/manifests.ts
It is not possible to reload children of a data type so this PR removes that option.
> Don't allow reload of data type children

- src/packages/core/modal/common/icon-picker/icon-picker-modal.element.ts
Just went to search for an icon and nothing showed up. I realised it was because I searched for "Home" instead of "home".
Figured this should probably be case insensitive (it is in current backoffice).
I also terminated an `: any` ☠️
Search for an icon using upper or mixed case characters.
> Makes icon search case insensitive

- src/packages/documents/documents/components/input-document-root-picker/input-document-root-picker.element.ts
- src/packages/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
- src/packages/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
- src/packages/dynamic-root/modals/index.ts
- src/packages/dynamic-root/modals/manifests.ts
Refactored the modals for the Dynamic Root Origin picker and Query Step picker, as they were performing an extra call to the `umbExtensionsRegistry` to re-get the associated manifests.
> Refactor: Dynamic Root modals

- src/packages/core/components/index.ts
- src/packages/core/components/input-content-type-property/index.ts
- src/packages/core/components/input-content-type-property/input-content-type-property.element.ts
- src/packages/core/modal/common/item-picker/item-picker-modal.element.ts
- src/packages/core/modal/common/manifests.ts
- src/packages/core/modal/token/index.ts
- src/packages/core/modal/token/item-picker-modal.token.ts
- src/packages/core/property-editor/uis/collection-view/config/column-configuration/property-editor-ui-collection-view-column-configuration.element.ts
For the Collections data-type configuration, when adding a column to the Collection View we needed a way to pick a property from a Document Type or Media Type (and also potentially Element Types and Member Types).
For the Template editor, we have the `<umb-field-dropdown-list>` component, but I wanted to explore an alternative flow for selecting a content-type, then be presented the list of properties (both system fields and user-defined properties) in a modal.
To achieve this I have introduced an **"Item Picker" modal**, _(for want of a better name),_ which will let us reuse a modal with lists of different items.  @nielslyngsoe may wish to give this a sanity check.
This PR doesn't make many changes to the `<umb-property-editor-ui-collection-view-column-configuration>` component, that'll …
> Feature: Content Type Property Picker

- src/packages/core/models/index.ts
- src/packages/core/property-editor/uis/tree-picker/property-editor-ui-tree-picker.element.ts
- src/packages/core/tree/components/input-tree/input-tree.element.ts
> [!NOTE]
> This PR can be merged after the corresponding backend PR has been merged in: https://github.com/umbraco/Umbraco-CMS/pull/15684
The Management API will update the Multinode Treepicker's value data structure to the following...
```
[
{ type: "document", unique: "9394af8f-d306-4778-9f03-2431eb8f5b6b" },
{ type: "document", unique: "15b092f0-66b5-40e5-aa1b-25b71b2bd81a" },
{ type: "document", unique: "4e02a6bf-5ab6-4b55-8f06-c6d24e892f8c" }
]
```
This PR updates the UI accordingly.
> Feature: TreePicker aligns value data structure with backend API

- src/packages/language/app-language-select/app-language-select.element.ts
Update the data attribute to use unique instead of iso code.
It is now possible to select a language in the app language dropdown.
> Bugfix: change app language in dropdown

- src/mocks/data/data-type/data-type.data.ts
- src/packages/core/property-editor/schemas/Umbraco.MultipleTextString.ts
- src/packages/core/property-editor/uis/multiple-text-string/manifests.ts
Whilst testing the property-editors, I'd noticed that the Multiple Textstring editor wasn't loading correctly, this is because the schema alias on the server is `Umbraco.MultipleTextstring` (lowercase 's') and on the client it is `Umbraco.MultipleTextString` (uppercase 'S'). I've corrected this to align with the server.
I assume that the intent was to lowercase the 'S' on the server, but this didn't happen before the beta release.
> Chore: Corrected casing of "MultipleTextString"

- src/packages/core/entity-action/common/sort-children-of/manifests.ts
- src/packages/core/entity-action/common/sort-children-of/sort-children-of.action.kind.ts
- src/packages/core/entity-action/manifests.ts
- src/packages/core/tree/reload-tree-item-children/reload-tree-item-children.action.kind.ts
- src/packages/documents/documents/entity-actions/create/manifests.ts
- src/packages/documents/documents/entity-actions/culture-and-hostnames/manifests.ts
- src/packages/documents/documents/entity-actions/manifests.ts
- src/packages/documents/documents/entity-actions/permissions.action.ts
- src/packages/documents/documents/entity-actions/public-access/manifests.ts
This adds a weight + a few missing actions to signal where the Core actions will be located and under which weight. This enables extension developers to be aware of which weight the built-in actions have so that they may place their own actions.
> add weight + icons + missing stubs for entity actions

- src/packages/core/components/input-dropdown/input-dropdown-list.element.ts
- src/packages/core/property-editor/uis/dropdown/property-editor-ui-dropdown.element.ts
With recent changes to how the Management API sends the data structure for the Dropdown, the UI was completely broken™. This PR fixes that.
A slight complexity with the Dropdown property-editor, due to legacy support for multiple values, the input value needs to support both `string` and `string[]` value types. This PR also handles those scenarios. However the UI currently only supporting the single value (non-multiple) UI, (e.g. `uui-select` instead of `uui-combobox-list`) This will need a separate review/fix.
> Bugfix: Dropdown data structure

- src/packages/core/components/input-slider/input-slider.element.ts
- src/packages/core/components/input-slider/input-slider.stories.ts
- src/packages/core/property-editor/uis/slider/property-editor-ui-slider.element.ts
Wires up the persisted value with the Slider UI.
Renames the component's `initVal1` and `initVal2` properties to `valueLow` and `valueHigh` respectively.
> Bugfix: Slider value

- src/packages/core/components/input-eye-dropper/input-eye-dropper.element.ts
- src/packages/core/property-editor/uis/eye-dropper/property-editor-ui-eye-dropper.element.ts
Wires up the persisted value with the UI.
The `“showPalette”` configuration wasn’t being wired up correctly. Also there’s a disconnect between the `“showPalette”` value (a boolean) and the default value for “swatches” (an array of string hex colour values).
I've added temporary values for the swatch colours. Hex values have been taken from the UUI Library example:
https://uui.umbraco.com/?path=/docs/uui-color-picker--docs
> Bugfix: Eye Dropper UI

- src/packages/core/components/input-color/input-color.element.ts
- src/packages/core/property-editor/uis/color-picker/property-editor-ui-color-picker.element.ts
Wires up the correct value data structure, and corrects the `items` configuration value to prefix a `#` onto the hex colour values.
> Bugfix: Color Picker amends

- src/libs/context-api/provide/context-provider.controller.ts
- src/libs/context-api/provide/context-provider.element.ts
- src/libs/context-api/provide/context-provider.ts
- src/libs/context-api/provide/index.ts
Remove potential cyclic dependency (even though it is a `type` import).
> ensure that context-provider imports relative from itself

- src/packages/core/menu/menu-item-layout/menu-item-layout.element.ts
- src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
- src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts
This PR adds an active state to a menu/tree item. The active state is based on whether the path of the navigation item is part of the current location. This also means that there is no need for a custom implementation of the active state.
Uploading Kapture 2024-03-20 at 13.53.19.mp4…
**Known missings:**
* This PR only implements the active state. The tree won't unfold to the active item. That will be fixed in another PR.
> Feature: Active menu/tree item

- src/packages/core/components/index.ts
- src/packages/core/components/ref-item/index.ts
- src/packages/core/components/ref-item/ref-item.element.ts
- src/packages/core/modal/common/item-picker/item-picker-modal.element.ts
- src/packages/core/modal/token/item-picker-modal.token.ts
- src/packages/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
- src/packages/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
Adds a `umb-ref item` component, for use within the Item Picker modal.
This component and the Item Picker modal are used in the Collection View configuration fields, (upcoming in separate PRs).
Also, updated the Dynamic Root modals to use `umb-ref-item` for UI consistency.
> Feature: `umb-ref item`

- src/packages/core/components/input-content-type-property/input-content-type-property.element.ts
- src/packages/core/property-editor/uis/collection-view/config/column-configuration/property-editor-ui-collection-view-column-configuration.element.ts
- src/packages/members/member-type/index.ts
> [!NOTE]
> This PR has been marked as draft until PR #1463 is merged in.
> - #1463
Updates the Collection View columns configuration UI, to align with the layout configuration UI.
Updates to `umb-input-content-type-property` component to enable the Content Type picker to submit on first/single selection for a smoother UX flow.
> Feature: Collection View columns configuration

- examples/manifest-picker/README.md
- examples/manifest-picker/index.ts
- examples/manifest-picker/manifest-picker-dashboard.ts
- src/packages/core/components/index.ts
- src/packages/core/components/input-manifest/index.ts
- src/packages/core/components/input-manifest/input-manifest.element.ts
> [!NOTE]
> This PR has been marked as draft until PR #1463 is merged in.
> - #1463
The `umb-input-manifest` component is a button that opens the Item Picker modal, populating it will the manifests of the selected extension type. It will be used in the Collection View layout configuration.
> Feature: Manifest input

- src/packages/core/property-editor/schemas/Umbraco.Decimal.ts
Just a small fix that when toggling value up/down, increases value by 0.01 for decimals and avoid showing error when number is decimal 😊
> Bugfix: Use decimals in step property for decimals

- src/packages/data-type/collection/repository/data-type-collection.server.data-source.ts
- src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
- src/packages/data-type/components/ref-data-type/ref-data-type.element.ts
- src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-data-type-picker-modal.element.ts
- src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
- src/packages/data-type/repository/item/data-type-item.server.data-source.ts
- src/packages/data-type/repository/item/types.ts
- src/packages/data-type/tree/data-type-tree.server.data-source.ts
Added icons added in datatypeflowpicker based on propertyEditorUi
Added icons for data-type tree based on propertyEditorUi
Some datatypes still shows `icon-circle-dotted` due to the property `propertyEditorUiAlias` received from endpoint is `undefined`.
> Feature: Datatypepickerflow - Property Icons

- examples/dashboard-with-property-dataset/dataset-dashboard.ts
- src/mocks/data/data-type/data-type.data.ts
With the recent changes to the CheckboxList, DropdownList and RadioButtonList editors, I'd noticed some of the mock data wasn't aligned with the updated data structure, (`string[]`).
> Chore: Mock data - corrects list item data structure

- src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
We have missed passing the meta object to the highlighted entity action on a tree item. That result in the entity action not working. 
How to test:
* Test that it is possible to delete a member type or data type trough the "highlighted" action.
> Bugfix: Pass meta to highlighted entity action

- src/packages/data-type/entity-actions/create/modal/data-type-create-options-modal.element.ts
- src/packages/media/media-types/entity-actions/create/modal/media-type-create-options-modal.element.ts
This PR fixes the data type and media type tree to update correctly after a new folder is created.
Notice:
It looks like there is a server issue creating nested media-type folders.
> Bugfix: Reload data type media type folders on create

- src/packages/core/modal/common/icon-picker/icon-picker-modal.element.ts
- src/packages/core/property-editor/uis/collection-view/config/layout-configuration/property-editor-ui-collection-view-layout-configuration.element.ts
- src/packages/user/user/collection/views/manifests.ts
> [!NOTE]
> This PR has been marked as draft until PR #1465 is merged in.
> - #1465
Updates the UI to make use of the `umb-input-manifest` component.
Plus small amends to the Icon Picker modal for colour selection; and corrected "User Grid Collection View" manifest.
> Feature: Collection View layouts configuration

- src/packages/core/extension-registry/collection/extension-collection.element.ts
- src/packages/core/utils/index.ts
- src/packages/core/utils/string/from-camel-case.function.ts
Adds a `fromCamelCase` utility function, this is used to display a friendlier label from a camelCased alias.
This was extracted from the `extension-collection.element.ts` code for reusability.
> Feature: `fromCamelCase` function

- src/packages/data-type/tree/data-type-tree.server.data-source.ts
- src/packages/dictionary/tree/dictionary-tree.server.data-source.ts
- src/packages/documents/documents/recycle-bin/tree/document-recycle-bin-tree.server.data-source.ts
- src/packages/documents/documents/tree/document-tree.server.data-source.ts
- src/packages/media/media-types/tree/media-type-tree.server.data-source.ts
- src/packages/media/media/tree/media-tree.server.data-source.ts
- src/packages/static-file/tree/static-file-tree.server.data-source.ts
- src/packages/templating/partial-views/tree/partial-view-tree.server.data-source.ts
- src/packages/templating/scripts/tree/script-tree.server.data-source.ts
- src/packages/templating/stylesheets/tree/stylesheet-tree.server.data-source.ts
- src/packages/templating/templates/tree/template-tree.server.data-source.ts
We have forgot to pass the skip take values to the server in some cases. This PR fixes that.
> Bugfix: Add missing skip + take values

- src/packages/documents/documents/collection/repository/document-collection.server.data-source.ts
- src/packages/documents/documents/collection/types.ts
- src/packages/documents/documents/collection/views/index.ts
I'd spotted that the `contentTypeAlias` value was missing from the Document Collection table view, so have now wired it up.
> Feature: Document Collection: Adds `contentTypeAlias` to the column property values

- src/packages/core/collection/collection-bulk-action-permission.condition.ts
- src/packages/core/collection/collection-view.manager.test.ts
- src/packages/core/collection/collection-view.manager.ts
- src/packages/core/collection/collection.element.ts
- src/packages/core/collection/components/collection-view-bundle.element.ts
- src/packages/core/collection/default/collection-default.context.ts
- src/packages/core/components/icon/icon.element.ts
- src/packages/core/property-editor/uis/collection-view/property-editor-ui-collection-view.element.ts
- src/packages/documents/documents/collection/document-collection-toolbar.element.ts
- src/packages/documents/documents/collection/document-collection.context.ts
Wired up the final pieces for the configuration of the Collection View layouts.
**Testing notes**: If a Collection has a data-type configuration with layout options, then they will be mapped to the `collectionView` manifests that are allowed on that Collection, (e.g. the manifest matches the condition), and the custom icon, label and order will be displayed.
If there is no layout configuration for the Collection, it will default to the `collectionView` manifests for that Collection (e.g. that match the condition).
> Feature: Collection View Layouts

- src/packages/core/components/index.ts
- src/packages/core/components/input-entity/index.ts
- src/packages/core/components/input-entity/input-entity.element.ts
- src/packages/core/picker-input/picker-input.context.ts
> [!NOTE]
> This component is a work-in-progress and needs feedback from the team.
Introduces a generic picker component that can select entities from a provided `pickerContext`.
The reason for this component was for the Package Builder feature, the workspace has several picker inputs from across the CMS, which has exposed gaps or potential misconfigurations:
- missing pickers for: Dictionary Items, Scripts and Partial Views
- reusing the Media picker; the UI is cosmetically different, and has (or will have) extra features to define crops and alt-text
- reusing the Template picker; the UI is cosmetically different, and has an extra feature to select a default template, (as used on the Document Type workspace)
The code for the UI across these pickers is largely the same, so could be …
> Feature: Entity Picker Input

- src/packages/packages/package-section/views/market-place/packages-market-place-section-view.element.ts
- src/packages/packages/package/repository/package.repository.ts
- src/packages/packages/package/repository/package.store.ts
- src/packages/packages/package/repository/sources/package.server.data.ts
Wires up the Packages configuration from the Management API, to populate the Packages Marketplace URL.
Adds a loader to `umb-packages-market-place-section-view` whilst the request is loading.
> Chore: Packages Marketplace URL

- src/packages/block/block-grid/components/block-grid-area-config-entry/workspace/manifests.ts
- src/packages/block/block-type/workspace/manifests.ts
- src/packages/block/block/workspace/manifests.ts
- src/packages/core/workspace/components/workspace-action/common/index.ts
- src/packages/core/workspace/components/workspace-action/common/save/index.ts
- src/packages/core/workspace/components/workspace-action/common/submit/index.ts
- src/packages/core/workspace/components/workspace-action/common/submit/submit.action.ts
- src/packages/data-type/workspace/manifests.ts
- src/packages/dictionary/workspace/manifests.ts
- src/packages/documents/document-types/workspace/manifests.ts
- src/packages/documents/documents/workspace/manifests.ts
- src/packages/language/workspace/language/manifests.ts
- src/packages/media/media-types/workspace/manifests.ts
- src/packages/media/media/workspace/manifests.ts
- src/packages/members/member-group/workspace/manifests.ts
- src/packages/members/member-type/workspace/manifests.ts
- src/packages/members/member/workspace/manifests.ts
- src/packages/templating/partial-views/workspace/manifests.ts
- src/packages/templating/scripts/workspace/manifests.ts
- src/packages/templating/stylesheets/workspace/manifests.ts
- src/packages/templating/templates/workspace/manifests.ts
- src/packages/user/user-group/workspace/manifests.ts
- src/packages/user/user/workspace/manifests.ts
Rename the save action api to fit with the rest of the code. aka. submit.
This is a little bit breaking but there is a deprecated JSDocs  on it, and it follows along the other PRs. so I dont think we need to mark this one as breaking.
> rename our save workspace action api to submit

- src/packages/core/utils/download/blob-download.function.ts
- src/packages/core/utils/index.ts
- src/packages/dictionary/entity-action/export/export.action.ts
- src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
Adds a `blobDownload` utility function, used to prompt a browser download of content delivered from the server.
This was extracted from the `export.action.ts` code and reused in `workspace-package-builder.element.ts`.
> Feature: `blobDownload` function

- src/packages/core/section/components/input-section/input-section.element.ts
- src/packages/data-type/components/data-type-input/data-type-input.element.ts
- src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
- src/packages/documents/documents/components/input-document/input-document.element.ts
- src/packages/language/components/input-language/input-language.element.ts
- src/packages/media/media-types/components/input-media-type/input-media-type.element.ts
- src/packages/media/media/components/input-media/input-media.element.ts
- src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
- src/packages/members/member-type/components/input-member-type/input-member-type.element.ts
- src/packages/members/member/components/input-member/input-member.element.ts
- src/packages/static-file/components/input-static-file/input-static-file.element.ts
- src/packages/templating/stylesheets/components/stylesheet-input/stylesheet-input.element.ts
- src/packages/user/user-group/components/input-user-group/user-group-input.element.ts
- src/packages/user/user/components/user-input/user-input.element.ts
The `super` context does not exist within a callback.
This has been exclusively within the various Picker input components for the `selection` callback.
> Chore: Replace `super.value` in Picker callbacks

- src/packages/core/debug/stories/debug.mdx
Adjustments for the Storybook docs about umb-debug, I guess it would be valuable to move them into the official docs in the future but this ensures to reflect the change of the property `enabled` to `visible`
> Update outdated docs for <umb-debug>

- src/packages/core/components/extension-with-api-slot/extension-with-api-slot.element.ts
This PR fixes the problem where entity actions didn't run on the current entity if the context menu isn't closed between actions.
The problem was that the extensions weren't reinitialized when there were new constructor args. It would have been better to be able to also set the values on the API, but it is currently not supported by the API. In the end we need to make this update if the args should change over time.
* Make sure that an entity action is run on the correct entity unique. One way to do it is:
* Open the context menu for a tree item
* Try to delete the item and notice the name of the item in the delete dialog
* Cancel the delete dialog
* Open the context menu for another tree item without closing it
* Try to delete the item and notice that the name has changed to the new tree …
> Bugfix: Reinitialize Extensions when constructor args changes

- src/libs/context-api/consume/context-consumer.ts
- src/libs/extension-api/controller/base-extension-initializer.controller.ts
- src/libs/extension-api/controller/base-extensions-initializer.controller.ts
- src/packages/core/components/extension-slot/extension-slot.element.ts
- src/packages/core/components/extension-with-api-slot/extension-with-api-slot.element.ts
- src/packages/core/entity-action/entity-action-list.element.ts
- src/packages/user/user/workspace/user-workspace-editor.element.ts
Extension-slots require an unknown set of properties to be set before it makes sense for them to start initialising extensions.
This life-cycle has been improved as of this PR. and fixes an issue on the user-workspace.
> fix: extension-slot life cycle issue

- src/packages/user/current-user/history/current-user-history-user-profile-app.element.ts
Whilst looking at PR #1575, I wanted to bring the same UI consistency for the "Your recent history" panel, (inside the Current User Profile modal).
- Reverses the history list, most recent at the top
- Cleans up the `<uui-box>` usage
- Makes use of `<uui-ref-list>` and `<uui-ref-node>`
- Truncates the path/URL display text
- Reduces custom styles
> Chore: Profile History refactor

- src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
Url was not constructed correctly, making it hard for the modal context to remove the path when closed.
> fix: Block Type Modals removing url when done.

- src/packages/core/workspace/components/workspace-breadcrumb/workspace-menu-breadcrumb/workspace-menu-breadcrumb.element.ts
I'd noticed in the DocumentType and DataType workspaces that the localization key, e.g. `#treeHeaders_dataTypes` was being displayed.
@madsrasmussen I wasn't sure whether the localization should happen further up the chain, or at the point of render? I'm happy to update the PR accordingly.
> Bugfix: Workspace Breadcrumb: Localizes ancestor names

- src/packages/core/components/extension-slot/extension-slot.element.ts
- src/packages/core/components/extension-with-api-slot/extension-with-api-slot.element.ts
Fixing a JS error where extensionsController has been destroy but is still set as a property.
> Fix: unset extensionsController when destroyed

- src/packages/core/components/input-date/input-date.element.ts
- src/packages/core/property-editor/schemas/Umbraco.DateTime.ts
- src/packages/core/property-editor/uis/date-picker/property-editor-ui-date-picker.element.ts
Refactors the Date Picker property-editor and input.  The server-time offset has been deemed no longer required, as the underlying value is stored in UTC format.
Also fixed a bug where the value wasn't being wired up and persisted to the server.
> Bugfix: Date Picker server-time offset refactor

- src/libs/extension-api/registry/extension.registry.test.ts
- src/libs/extension-api/registry/extension.registry.ts
Ability to exclude extensions(Not kinds) + tests
> exclusion feature

- src/mocks/data/data-type/data-type.data.ts
- src/packages/core/components/input-entity/input-entity.element.ts
- src/packages/core/property-editor/schemas/Umbraco.MediaPicker.ts
- src/packages/core/property-editor/schemas/Umbraco.RichText.ts
- src/packages/media/media/property-editors/index.ts
- src/packages/media/media/property-editors/manifests.ts
- src/packages/media/media/property-editors/media-entity-picker/index.ts
- src/packages/media/media/property-editors/media-entity-picker/manifests.ts
- src/packages/media/media/property-editors/media-entity-picker/property-editor-ui-media-entity-picker.element.ts
I'd noticed that both the Media Picker and RTE data-type configurations were using the new Media Picker property-editor UI to set the Start Node field, however that UI is intended for selecting media items with support for crops and focal points, e.g. more meta-data than just the media's unique ID.
This PR adds a new "Media Entity Picker" property-editor UI, with support for only selecting the Media entity unique ID.
The Media Picker and RTE data-type configurations have been updated.
This PR aligns with https://github.com/umbraco/Umbraco-CMS/pull/16042, but is not dependent on it, so can be merged in separately.
> Feature: Media Entity Picker property-editor UI

- src/packages/core/components/index.ts
- src/packages/core/components/stack/index.ts
- src/packages/core/components/stack/stack.element.ts
- src/packages/core/components/stack/stack.stories.ts
The PR introduces a new `umb-stack` element. The purpose of this element is to provide consistent spacing between stacks of items.
There is a default and a compact mode, as well as a flag to include a dividing line. 
I was finding myself adding the same styles in a lot of places to space items in a list. These were becoming inconsistent and a annoying to copy. I thought it would be good if we had a component that applied the spacing when needed. This should also be useful for things like `umb-property` which is currently struggling to align correctly in places. With this, we can remove any styling from individual elements, and let the stack do the layout.
Create a `umb-stack` element and create any number of items inside of it. These should all be spaced nicely.
```javascript
<umb-stack> …
```
> `umb-stack` element

- src/packages/core/components/input-entity/input-entity.element.ts
- src/packages/core/models/index.ts
- src/packages/members/member-type/components/input-member-type/input-member-type.element.ts
Straddling between chore and bugfix, I'd noticed that an issue in the MemberType picker where the `MemberTypeItemResponseModel` had bled through, whereas the `UmbUniqueTreeItemModel` could be used. Which also solved an issue I had with the Entity picker input component.
> Bugfix: Picker inputs, updated to use `UmbUniqueTreeItemModel`

- src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
Removes the parentheses around invariant document names. It will also show for variant documents where the variant doesn't have a name.
> Bugifx: correct display of document tree item invariant name

- src/packages/core/components/input-color/input-color.element.ts
- src/packages/core/property-editor/uis/color-picker/property-editor-ui-color-picker.element.ts
This PR fixes a bug introduced in PR #1443, where the color hex value is prefixed with a hash inside the `umb-input-color` component. The reason behind this was that the data-type configuration for the Color Picker property-editor did not prefix the color hex values with a hash, _(this may or may not be a bug in the `umb-property-editor-ui-color-swatches-editor` component)_.
In order to keep the `umb-input-color` component "pure", the logic has been moved to the Color Picker property-editor itself, by ensuring the `"items"` configuration (color swatches) and the `value` are prefixed with a hash.
> Bugfix: Color Picker prefix hex values with a hash

- src/packages/core/property-editor/uis/collection-view/config/column/column-configuration.element.ts
- src/packages/core/property-editor/uis/collection-view/config/layout/layout-configuration.element.ts
For new/empty Collection View configurations, the fields for Columns and Layout did not show a "Choose" input (add button).
This PR fixes that.
> Bugfix: Collection View configuration fixes empty inputs

- src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
Fixed a bug where you could not create a new document when no blueprints were available for the picked document type.
> Bugfix: Create a document when no blueprint available

- src/packages/core/content-type/structure/content-type-container-structure-helper.class.ts
- src/packages/core/content-type/structure/content-type-property-structure-helper.class.ts
- src/packages/core/content-type/structure/content-type-structure-manager.class.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
Minor correction of errors, so far:
Rename property, does not make a duplicate any longer.
Delete a tab, does not require the tab to get focus first any longer.
When adding a tab and a group, the group does no longer look like an inherited one.
When adding a composition to my Document Type, a root group(of the owner document) does no longer look like its inherited.
> Fix: Content Type Design Editor fixes

- src/packages/log-viewer/workspace/logviewer-workspace.context.ts
In the Log Viewer's Saved searches, any queries clicked on that contained a percentage sign `%` would throw an malformed URI error, this was because the value was being double-decoded, (since the router-slot `query()` function we're using already handles the URL decoding).
This PR removes the extra `decodeURIComponent` call, so clicking on the saved searches (that contain percentage signs) now work.
> Bugfix: Logviewer: removes the `decodeURIComponent`

- src/packages/core/content-type/structure/content-type-structure-manager.class.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
Ah, I guess i was tired when i wrote this originally. here is a fix. :-)
> fix: delete tab in content-type design editor

- src/packages/core/content-type/modals/property-type-settings/property-type-settings-modal.element.ts
- src/packages/core/content-type/structure/content-type-property-structure-helper.class.ts
- src/packages/core/content-type/structure/content-type-structure-manager.class.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
Correct the code for Content Type Property Inheritance, so it actually work, I do not think the previous code was ever really implemented.
> Fix: Content Type property Inheritance

- src/apps/backoffice/backoffice.context.ts
- src/apps/backoffice/components/backoffice-header-logo.element.ts
- src/apps/backoffice/components/backoffice-header.element.ts
- src/apps/backoffice/components/index.ts
Adds the header logo modal, that contains the Umbraco logo, version number and link to the umbraco.com website.
For this initial implementation, I chose to use `tryExecute` directly inside the `UmbBackofficeContext`. Ideally, I assume this would be separated out to its own repository, but I was unsure of the naming (and which package it should reside?).
The ad-hoc SemVer regex parser is there to remove the unwanted bits of the version number, namely the build suffix as it starts to look a overwhelming, but we can adjust this as required.
I'm happy to restructure this PR as needed.
> Feature: Umbraco version number (header logo modal)

- src/packages/core/components/input-collection-configuration/input-collection-configuration.element.ts
Simplifies the `umb-input-collection-configuration` component, by making use of `umb-ref-data-type` component, and removing the need to have our own `UmbRepositoryItemsManager<>` instance (for observing the data-type repo).
Also, wires up the ref's `@open` event so that it opens the data-type's edit workspace modal.
> Bugfix: Simplifies `umb-input-collection-configuration` (refactor)

- src/packages/core/property-editor/uis/color-picker/property-editor-ui-color-picker.element.ts
Following on from a conversation on PR #1606, this PR adds a RegEx to check whether the hex color value is valid (e.g. `0-9a-f` and 3 or 6 characters in length), and doesn't have a hash prefix `#`.  This is to support current usage (pre-v14 migrated data) and accommodate future usage, for those wishing to use alternative CSS value formats.
> Bugfix: ColorPicker: Regex to ensure hex color hash prefix

- src/packages/core/components/input-number-range/input-number-range.element.ts
- src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
- src/packages/core/property-editor/uis/number-range/property-editor-ui-number-range.element.ts
- src/packages/core/validation/controllers/bind-validation-message-to-form-control.controller.ts
- src/packages/core/validation/controllers/form-control-validator.controller.ts
- src/packages/core/validation/mixins/form-control.mixin.ts
- src/packages/umbraco-news/umbraco-news-dashboard.element.ts
Contains this:
* Removed DefaultValueType generic type for a simpler implementation.
* Corrected implementations that did set one generic, when setting one generic all of them has to be defined, so before the superClassType was missing.
* Simple small type rename.
> Chore: minor corrections for form control

- src/packages/core/components/input-toggle/input-toggle.element.ts
- src/packages/core/components/multiple-color-picker-input/multiple-color-picker-input.element.ts
- src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
- src/packages/core/property-editor/uis/color-swatches-editor/property-editor-ui-color-swatches-editor.element.ts
For the Color Picker property-editor, on initial data-type configuration, the `useLabel` value defaults to `false` (as expected, as it's a toggle), but the UI code assumes the default value is `true`, which doesn't align with the UX, e.g. `useLabel=false` but the color swatch input showed the label input.
This PR aligns the UX for the `useLabel` default value.
Also, I'd spotted a bug in the `umb-input-toggle` related to a custom 'change' event that was both bubbles & composed, which was throwing a devtools console error.
> Bugfix: Color Picker: default value for `useLabel` configuration

- src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
Both the `uui-radio-group` and `uui-radio` dispatch a 'change' event, which triggers the `#onChange` method twice.
The `uui-radio` component is the one that contains the changed value, so updated the code to only use that.
> Bugfix: Radio Button List: prevent triggering double 'change' event

- src/packages/core/property-editor/schemas/Umbraco.Decimal.ts
- src/packages/core/property-editor/schemas/Umbraco.Integer.ts
Corrects two typos in the numeric property editors. 
Currently the `Decimal` and `Numeric` property editors say on the `Maximum` property "enter the minimum amount...". This change updates to "enter the **maximum** amount..."
- [ ✅ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)
Just a typo
Open a property editor for `Numeric` or `Decimal`, check the `Maximum` property text now describes `Maximum` instead of `Minimum`
- [ ✅] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/.github/CONTRIBUTING.md)>)** document.
> Corrects "minimum" to "maximum" in the integer and decimal property editors

- src/packages/tiny-mce/plugins/tiny-mce-linkpicker.plugin.ts
This PR fixes a bug that would ignore any query string value added to the anchor/query input of the link picker in the RTE.
Main issue is described here: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1674
It also ensures that a bugfix from v13 is applied: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1169
I do think that it would be good to maybe extract (or at least export) some functions for the logic here so that it can be tested but I'm not sure how to approach this so I started with this PR to fix the bug.
Create a RTE and insert links, try:
* Adding query string like this: `?foo=bar`
* Adding query string like this: `?foo=bar&lroem=ipsum`
* Adding anchor like this: `#something`
> Fixes issue with RTE query string links #1674 and ensures #1169

- src/packages/core/content-type/modals/composition-picker/composition-picker-modal.element.ts
- src/packages/core/content-type/modals/composition-picker/composition-picker-modal.token.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
- src/packages/documents/document-types/types.ts
Fixes an error when opening the composition modal while the document type is still not saved.
Issue & details can be found here https://github.com/umbraco/Umbraco-CMS/issues/16091
> Bugfix: Composition Modal when document type isNew

- src/packages/core/property-editor/uis/dropdown/property-editor-ui-dropdown.element.ts
Adds "multiple" feature to the Dropdown property-editor UI.
This PR resolves issue: https://github.com/umbraco/Umbraco-CMS/issues/16081
> [!NOTE]
> Since the UUI Library does not (currently) support the `multiple` flag on the `<uui-select>` component, we are (currently) using a native HTML `<select multiple>` element, applied with Umbraco styling.
> This is an interim measure for Umbraco 14.0 and will be reviewed in due course.
> Feature: Adds "multiple" feature to Dropdown property-editor UI

- src/packages/core/property-editor/schemas/Umbraco.Tags.ts
- src/packages/core/property-editor/uis/manifests.ts
- src/packages/core/property-editor/uis/select/manifests.ts
- src/packages/core/property-editor/uis/select/property-editor-ui-select.element.ts
- src/packages/core/property-editor/uis/select/property-editor-ui-select.stories.ts
- src/packages/core/property-editor/uis/select/property-editor-ui-select.test.ts
Adds a **Select** property-editor UI, wrapping the `<uui-select>` component.
This differs from the Dropdown property-editor UI, so that it doesn't need to support the `multiple` configuration and will expect a uses a single `string` value, as opposed to an `Array<string>`.
This PR updates the `Umbraco.Tags` schema to use this property-editor UI, which will fix a bug raised in RC1: https://github.com/umbraco/Umbraco-CMS/issues/16084
> Feature: "Select" Property Editor UI

- src/packages/core/modal/context/modal.context.ts
Update `setValue` method of Modal Context, to use `setValue` of its value state. This was before using `updateValue` of the state. Meaning it only updated the value, but never set it to the given data. If you still want to partial update your value, you will now have to change your code to use the other method called `updateValue` on the modal context.
> Fix: use setValue for setValue on modal context

- src/packages/core/components/input-upload-field/input-upload-field.element.ts
This fixes a bug where when no file extensions were set, the file upload field wouldn't show up.
> Bugfix: Upload files with no extensions

- src/packages/language/components/input-language/input-language.element.ts
- src/packages/language/modals/language-picker/language-picker-modal.element.ts
- src/packages/language/repository/detail/language-detail.server.data-source.ts
Fixes a bug where the iso code showed up as a guid
Closes issue: https://github.com/umbraco/Umbraco-CMS/issues/16090
Fixes a bug where the fallback language picker would always allow to pick multiple languages.
> Bugfix: Language isocode and fallback picker

- src/packages/core/components/input-upload-field/input-upload-field.element.ts
Fixes not being able to remove an item from file input
> remove files

- src/packages/block/block/conditions/block-entry-show-content-edit.condition.ts
- src/packages/block/block/conditions/block-workspace-has-settings.condition.ts
- src/packages/block/block/conditions/index.ts
- src/packages/block/block/index.ts
- src/packages/core/extension-registry/conditions/index.ts
- src/packages/core/extension-registry/conditions/types.ts
The core package is currently depending on the block package. It uses an import to `@umbraco-cms/backoffice/block` which it cannot. This PR is a temporary solution to solve the block circular dependency.
The PR moves the block condition types from the block package to the extension registry module. It is not the ideal solution but as long as we have the type unions this is the best we can do.
You will no longer find imports from the core package to the `@umbraco-cms/backoffice/block` module.
> [!CAUTION]
> Breaking change
> import of `BlockEntryShowContentEditConditionConfig` and `BlockWorkspaceHasSettingsConditionConfig` is moved from `@umbraco-cms/backoffice/block` to `@umbraco-cms/backoffice/extension-registry`;
> Bugfix: Remove block circular dependency

- .github/workflows/build_test.yml
- src/packages/core/components/history/history-item.element.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
- src/packages/media/media/workspace/views/info/media-workspace-view-info-history.element.ts
The History Item component depends on the `APP_CONTEXT` to render the avatar. I have changed the component to slot in the avatar element instead. This is closer to how other generic components work. This also moves the `APP_CONTEXT` responsibility to the implementing part.
On a side note. We shouldn't rely on the `serverUrl` to create the full avatar URL. This can change on the server. I have asked for a change in the Management API to include the absolute URL as we have in other places that expose the avatar URLs.
> [!CAUTION]
> Breaking Change
> It is no longer possible to pass a `src` prop to the `umb-history-item` element to render an avatar. Use the avatar slot instead.
> Bugfix: Remove History Item circular dependency

- src/packages/members/member/components/input-member/input-member.element.ts
- src/packages/members/member/property-editor/member-picker/property-editor-ui-member-picker.element.ts
- src/packages/user/user/components/user-input/user-input.element.ts
- src/packages/user/user/property-editor/user-picker/property-editor-ui-user-picker.element.ts
Corrected the Member Picker property-editor to have a maximum of 1 selectable item, for backwards-compatibility with previous Umbraco versions.
> Bugfix: Member Picker property-editor, `max` = 1

- src/packages/property-editors/collection-view/config/column/column-configuration.element.ts
- src/packages/property-editors/collection-view/config/layout/layout-configuration.element.ts
When a new Collection View data-type is created, the Columns and Layout fields are empty, which exposed a bug with the sorting feature. This PR rectifies the bug.
/cc @elit0451
> Bugfix: Fixed sorting of Collection configuration editors (on new data-types)

- src/packages/property-editors/collection-view/manifests.ts
When creating a new Collection View data-type (e.g. from a document-type), the configuration was empty, whereas in previous Umbraco versions the List View had a default configuration. This PR aligns this.
> Bugfix: Collection View default data-type configuration

- src/packages/data-type/workspace/views/details/data-type-details-workspace-view.element.ts
When in the Data Type's Details Workspace View, cancelling the Property Editor picker modal would empty out the current selection. This PR fixes that.
Also, wired up the `@open` event of the picker to open the Property Editor selection modal.
Plus, some general code/markup tidy-up, for consistency.
> Bugfix: Data Type Details Workspace View - Picker fixes

- src/packages/core/components/input-collection-configuration/input-collection-configuration.element.ts
- src/packages/core/picker-input/picker-input.context.ts
- src/packages/documents/document-types/components/input-document-type/input-document-type.context.ts
- src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
- src/packages/documents/document-types/workspace/views/structure/document-type-workspace-view-structure.element.ts
Also a bug fix as this fixes the Allow Children Picker of the Document Type Workspace Settings View, which with this only can select none elementTypes and none folders.
> Feat: accept tree-item-type as a generic type on the picker context

- src/packages/core/settings/manifests.ts
- src/packages/dictionary/section/manifests.ts
- src/packages/documents/section.manifests.ts
- src/packages/media/section.manifests.ts
- src/packages/members/member-section/manifests.ts
- src/packages/members/member/section-view/manifests.ts
- src/packages/packages/package-section/manifests.ts
- src/packages/user/user-section/manifests.ts
This sets the weight on the sections according to Umbraco 13.
**Before**
**After**
> Chore: Sort top level menu items

- src/mocks/data/data-type/data-type.data.ts
- src/packages/documents/documents/collection/repository/document-collection.server.data-source.ts
- src/packages/documents/documents/collection/types.ts
- src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
- src/packages/documents/documents/collection/views/index.ts
- src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-name.element.ts
- src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
- src/packages/media/media/collection/repository/media-collection.server.data-source.ts
- src/packages/media/media/collection/types.ts
- src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
- src/packages/property-editors/collection/config/column/components/input-collection-content-type-property.element.ts
- src/packages/property-editors/collection/manifests.ts
- src/packages/templating/modals/templating-page-field-builder/components/template-field-dropdown-list/template-field-dropdown-list.element.ts
Fixes for various bugs that @elit0451 has spotted during her testing.
- Replaces `"owner"` with `"creator"` (for consistency with Management API)
- Replaces `"entityName"` with `"name"` (for consistency with Management API)
- Replaces `"entityState"` with `"state"` (for consistency with Management API)
- Disables sorting of `"state"` column, (as current List View Table did not support this)
- Implemented `"sortOrder"` property, (this may have not been available when the Collection View Table was initially developed, so it was faked).
Updated PR with fixes for bugs raised by @Zeegaan and @bergmania.
- Fixes server error when `pageSize` is `NaN`
- Fixes the item's name button to open the document editor modal
> Bugfix: Collection View Table fixes

- src/packages/dictionary/index.ts
- src/packages/language/index.ts
- src/packages/media/media-types/index.ts
- src/packages/members/member-group/index.ts
- src/packages/members/member/index.ts
- src/packages/static-file/index.ts
- src/packages/templating/partial-views/index.ts
- src/packages/templating/stylesheets/index.ts
- src/packages/user/user-group/index.ts
- src/packages/user/user/index.ts
- src/packages/webhook/index.ts
Adds exports for missing entity types
Adds missing exports for entity types across package (#1740)
There were missing exports of entity types meaning that externally you couldn't access several extension points. 
Adds the export of entities for: 
- Dictionary
- Languages
- Media-types
- Members
- Member-Groups
- static-files ?
- partial-views
- stylesheets
- users
- user-groups
- webhooks.
Without the exports external packages can't add to action menus or workspaces.
NOT SURE? - I don't think this changes any core functionality it simply exposes the entity types in the library. ??
> Add missing entity type exports

- src/packages/core/collection/default/collection-default.context.ts
- src/packages/core/collection/default/collection-default.element.ts
- src/packages/documents/documents/collection/types.ts
- src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
- src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-name.element.ts
- src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-state.element.ts
- src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
Resolves a few outstanding issues with the Document Collection Views (both Table and Grid).
- Wires up the loading indicator, (one for the initial load, another for pagination/filtering/sorting)
- Wires up the modal routing with the document editor modal, (registering the route once per Collection View)
- Configure a collection on a document (which has child documents) and click around
- Does the loading indicator (3 circles) appear when you first load?
- Can you open a document (in the modal)?
- Can you sort, paginate and filter?
- Can you switch between the collection view layouts?
- Does the loading indicator (bar at the bottom, it's quite subtle) appear when you sort/filter/paginate?
> Bugfix: Document Collection View - loading state + opens modal

- src/packages/core/content-type/structure/content-type-structure-manager.class.ts
Also removing properties when removing a container, also works for properties of a container which is child of the container begin removed.
This fixes an issue where a Implementor(user) has a tab with a group with a property, and decides to remove the tab. then the property was not removed before this PR.
> Feat: Content Type editor — remove props when removing container

- src/packages/core/components/index.ts
- src/packages/core/components/input-slider/input-slider.element.ts
- src/packages/core/components/input-with-alias/input-with-alias.element.ts
- src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
- src/packages/documents/document-types/workspace/document-type-workspace.context.ts
- src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
- src/packages/media/media-types/workspace/media-type-workspace.context.ts
- src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
- src/packages/members/member-type/workspace/member-type-workspace.context.ts
Input with alias component + fixing isNew implementations of ContentType Editors, as they were slightly off, this might fix a few known issues. Like not turning into edit when creating the contentTypes.
> Feat: input with alias

- .github/localization_overview.md
- src/assets/lang/da-dk.ts
- src/assets/lang/en-us.ts
- src/assets/lang/en.ts
- src/packages/core/settings/welcome-dashboard/settings-welcome-dashboard.element.ts
Adds different content for `Community` and `Support` blocks in the Settings->Welcome dashboard
See issue here: https://github.com/umbraco/Umbraco-CMS/issues/16209
- Updates the localization in the _Community_ widget so that it pulls from a new `communityDescription` property
- Updates the text in the _Support_ widget so that it reads "Extend your team with a highly skilled and passionate bunch of Umbraco know-it-alls" (text taken from here https://umbraco.com/products/support/ )
- Removed the `dk` file's entry for `supportDescription` (I'm not a native speaker, so wouldn't want to attempt a translation)
localization + content
- [ ✅ ] Bug fix (non-breaking change which fixes an issue)
Open the Settings tab, see new content
https://localhost:44320/umbraco/section/settings/dashboard/welcome …
> Adds different content for `Community` and `Support` blocks

- src/packages/block/block-grid/property-editors/block-grid-column-span/property-editor-ui-block-grid-column-span.element.ts
- src/packages/block/block-grid/property-editors/block-grid-group-configuration/property-editor-ui-block-grid-group-configuration.element.ts
- src/packages/block/block-grid/property-editors/block-grid-layout-stylesheet/property-editor-ui-block-grid-layout-stylesheet.element.ts
- src/packages/markdown-editor/property-editors/markdown-editor/property-editor-ui-markdown-editor.element.ts
- src/packages/media/media/property-editors/image-crops-configuration/property-editor-ui-image-crops-configuration.element.ts
- src/packages/property-editors/icon-picker/property-editor-ui-icon-picker.element.ts
- src/packages/property-editors/overlay-size/property-editor-ui-overlay-size.element.ts
- src/packages/property-editors/text-box/property-editor-ui-text-box.element.ts
- src/packages/property-editors/textarea/property-editor-ui-textarea.element.ts
- src/packages/property-editors/upload-field/property-editor-ui-upload-field.element.ts
- src/packages/property-editors/value-type/property-editor-ui-value-type.element.ts
- src/packages/static-file/property-editors/static-file-picker/property-editor-ui-static-file-picker.element.ts
- src/packages/tags/property-editors/tags/property-editor-ui-tags.element.ts
- src/packages/tiny-mce/property-editors/toolbar/property-editor-ui-tiny-mce-toolbar-configuration.element.ts
this updates (essentially search/replaces) all instances of hardcoded `property-value-change` with the `UmbPropertyValueChangeEvent` class
> `property-value-change` should not be hardcoded

- tsconfig.json
Today when using ES2020 there are some of the modern JS features that TypeScript compiles into js-polyfills, which result in some issues when we use the feature in some special ways.
Here is a screendump from front-end build for the CMS (build `via :for:cms` script) and running purely on the server(not Vite)
Error originates from the polyfill code, like this:
Which looks like this in TypeScript:
Which is from the JS polyfill, which sees the internal property setting as coming from an outside, but is actually not.
So to fix the bad polyfill, I'm changing our compiler to ES2022 so it doesn't polyfill it. And that simplifies code and makes it work :-)
> set es2022 for tsconfig

- src/packages/core/auth/auth-flow.ts
The `isValid` method only checks the lifetime of the access_token, but you may still have a valid refresh_token in your storage, so it doesn't do any good to stop the flow
Instead we will assume that you are always logged in if there is a token in local storage
The end effect of this fix is that you will see the login screen far less often.
> fix: assume you are logged in if there is a token persisted

- src/packages/property-editors/entry-point.ts
We forgot to register the content picker components on startup.
> Bugfix: Register content picker components on startup

- src/packages/core/modal/common/icon-picker/icon-picker-modal.element.ts
Fixed a bug where picking an icon weren't doing anything.
Closes the issue: https://github.com/umbraco/Umbraco-CMS/issues/16206
> Bugfix: Fix picking bug in icon picker modal

- src/mocks/data/data-type/data-type.data.ts
- src/packages/property-editors/number/Umbraco.Integer.ts
- src/packages/property-editors/number/manifests.ts
this aligns the "numeric" and "decimal" property editors with V13
fixes #1660
> remove the unused 'allowDecimals' configuration and the "Integer" property editor

- src/packages/property-editors/collection/config/order-by/order-by.element.ts
- src/packages/property-editors/collection/manifests.ts
On the Collections configuration, previously the Order By field was hardcoded to 3 options.
This PR aligns the options with the items used in the Columns Displayed field. This is useful for when a user would like to set the default order by on their own column configuration.
On a data type for a Collection configuration, add, remove, sort the Columns Displayed items, see the changes reflected in the Order By dropdown field.
> Feature: Collection - syncs Order By with Columns Displayed field

- src/apps/backoffice/backoffice.context.ts
- src/apps/backoffice/backoffice.element.ts
- src/packages/language/global-contexts/app-language.context.ts
Some requests need to be called when the user is logged in, but if the user starts out with a timeout, these requests are never called again, and we need to make absolutely sure that they are being executed
> Retry requests after log in

- src/packages/core/modal/common/confirm/confirm-modal.element.ts
- src/packages/core/modal/token/confirm-modal.token.ts
Adds `cancelLabel` option to the Confirm Modal.
This PR also localizes the fallback labels for "Cancel" and "Confirm".
I needed this as part of the Document Preview feature #1778, when exiting the Preview mode a confirmation prompt modal is opened, with two options: "Preview latest version" (confirm) or "View published version" (cancel). Having "Cancel" didn't seem friendly in this scenario, _(it may be that it needs it's own modal, we can discuss)_.
> Feature: Confirm Modal: Adds `cancelLabel` option

- src/packages/core/auth/auth-flow.ts
When your access_token expires, we exchange the refresh_token for a new access_token, however this new token is never persisted in local storage meaning, that next time you refresh you are "logged out" prematurely
1. Let your access token expire (usually 5 minutes but configurable with "TimeOut" in appsettings) and check that the client exchanges its refresh token to new access token
2. Now refresh the browser (F5) and verify that you are still logged in
> fix: token after refresh is not persisted

- src/packages/webhook/components/input-webhook-events.element.ts
I noticed remove button at events had label "remove" unlike other places in UI where it is "Remove".
Furthermore I added localized value and at think "Choose" was a better term at events at one is choosing from available events registered in application to react on. It doesn't add any new events here.
> Change labels of buttons in webhook

- src/packages/search/examine-management-dashboard/views/section-view-examine-indexers.ts
In new backoffice labels of `fieldCount` and `documentCount` is camel case, which is different from current backoffice, and not consistent with the additional properties shown :)
> Update label of count properties in Examine dashboard

- src/packages/core/components/body-layout/body-layout.element.ts
Hides empty slots in `umb-body-layout`
Empty slots previously caused layout issues because of padding.
Notice the empty header slot taking up space, squishing the rest of the content, which causes the navigation to collapse into a dropdown
Before:
After:
> Feature: umb-body-layout - Hide empty slots

- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.defaults.ts
- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
Specifically for height, width, content_css, and style_formats, tinymce did not use its fallbacks if they were not provided through the data type.
This is particularly useful to have something visible in the "styles" menu.
> fix: tinymce does not use its default config

- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
TinyMCE does not support having the same html id for its elements (even though it's inside a Shadow DOM). By changing this to html classes, tiny now works when you have mulitiple instances on the same page, e.g. on a document.
Fixes #1233
> fix: multiple TinyMCE's on the same page does not work

- src/apps/app/app.element.ts
- src/assets/lang/da-dk.ts
- src/assets/lang/en-us.ts
- src/assets/lang/en.ts
- src/packages/core/auth/modals/umb-app-auth-modal.element.ts
Currently, when you have more than one provider, we are logging you in through a popup. This is a major difference from the normal flow where you are just redirected to the login screen. This PR aims to align the two, so regardless whether you have 1 or 3 login providers, you always get the same experience.
Log in (no previous session): You click a login provider, you get sent to the login screen of that provider
Login (no previous session, no providers): You get automatically redirected to the login screen (this experience has not been altered with this PR)
Timed out (all cases): You see the login modal on top of your backoffice, you click a login provider and log in through a popup
This PR also fixes a small-ish issue where the redirect back to the frontpage could happen even if there …
> Feature: Login without popup

- src/apps/app/app-auth.controller.ts
- src/packages/core/auth/auth-flow.ts
- src/packages/core/auth/auth.context.ts
If the client thinks it has a valid token (i.e. if the token was set on another umbraco instance or it has expired on the server or been revoked), it will still try and use it. The first authenticated request will then return a 401 prompting the client to show the "time out" screen. This is not entirely correct, as the user might simply expect to see the login screen directly.
This PR aims to introduce a simple server request to validate the token if one is present. We do this by trying to exchange the stored refresh_token to an access_token only on the first load. This has two benefits:
1. We let the server tell us directly if it thinks the stored token is useful.
2. We get a freshly minted access_token that is now valid for the configured timeout period and wont accidentally expire …
> Feature: Validate the token on first load

- src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
Fixes the Color Picker configuration to prevent losing focus on initial colour selection.
This will resolve https://github.com/umbraco/Umbraco-CMS/issues/16157
> Bugfix: Color Picker modal focus

- src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
Following on from #1769, this PR wires up the Document Picker's (root) start node configuration, (this is the separate editor from MNTP).
I've also included some code tidy-up and configuration validation, (for min/max values).
> Bugfix: Document Picker: Start node

- src/packages/core/components/input-eye-dropper/input-eye-dropper.element.ts
- src/packages/core/components/input-eye-dropper/input-eye-dropper.stories.ts
- src/packages/property-editors/eye-dropper/property-editor-ui-eye-dropper.element.ts
It was bothering me that the swatch colour values was being hard-coded in the Eye Dropper property-editor, (which was a duplicate of UUI's default colour swatches).
Investigating how the swatches palette was rendered from the UUI component, it turns out not to be straight-forward to hide the palette, as the object-type of the `swatches` property is non-nullable. So a little creative coding was necessary. _(I've left a big note about the logic.)_ 😂  
In this PR...
- Adds a `showPalette` property to the Eye Dropper input component
- Allows for the `swatches` to be undefined, so that it can fallback on UUI default swatches
- Removes the hard-coded swatches from the property-editor
- Updates Storybook story with the `showPalette` option
> Bugfix: Eye Dropper: Show Palette / Swatches

- src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
In the Document Collection, the Create action was broken when using the "Edit in Infinite Editor" configuration option.
This PR attempts to generate the correct modal route, by accounting for the current Collection View path-name.
Also includes UI amends, for limiting the height of the available document-types in the Create popover container, _(as my development database has over 30 available document-types in the list, it went off-screen, without a scrollbar!)_ 😱
> Bugfix: Document Collection: Create action modal route

- src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
- src/packages/property-editors/checkbox-list/components/input-checkbox-list/input-checkbox-list.element.ts
- src/packages/property-editors/checkbox-list/property-editor-ui-checkbox-list.element.ts
- src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
- src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
- src/packages/property-editors/select/property-editor-ui-select.element.ts
- src/packages/property-editors/select/property-editor-ui-select.test.ts
Adds support for name/value items to populate options data in the following list property-editors:
- Checkbox List
- Dropdown List
- Radio Button List
- Select (internal property-editor)
Backwards compatibility remains to continue support for legacy/migrated list data.
> Feature: Support for name/value options in list property editors

- src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
A `ts-ignore` hid some code during a refactor. The ts-ignore is now removed, the code is updated, and the tree will refresh again when something requests it.
How to test:
* When trashing a document. The document tree is refreshed.
> Bugfix: tree refresh

- src/packages/log-viewer/index.ts
Fixed https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1832 by exporting the donut chart from the log viewer as aggreged with @iOvergaard on Discord.
> fix: donut chart components are not exported

- src/apps/app/app.element.ts
- src/apps/preview/apps/manifests.ts
- src/apps/preview/apps/preview-culture.element.ts
- src/apps/preview/apps/preview-device.element.ts
- src/apps/preview/apps/preview-exit.element.ts
- src/apps/preview/apps/preview-open-website.element.ts
- src/apps/preview/preview.context.ts
- src/apps/preview/preview.element.ts
- src/apps/preview/preview.stories.ts
- src/apps/preview/preview.test.ts
- src/packages/core/extension-registry/models/index.ts
- src/packages/core/extension-registry/models/preview-app.model.ts
- src/packages/documents/documents/repository/index.ts
- src/packages/documents/documents/repository/preview/document-preview.repository.ts
- src/packages/documents/documents/repository/preview/index.ts
- src/packages/documents/documents/workspace/actions/save-and-preview.action.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
Adds the Document Preview feature to Bellissima.
https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/209066/36d4e1ec-b062-4354-a78e-f9e790d5bb59
This introduces a new extension type called `previewApp`, upon registration they will appear in the Preview window's menu (anchored to the bottom of the screen). This follows a similar approach to 'headerApp' extensions.
The core logic of the preview feature is within the `UmbPreviewContext`, with the preview-apps interacting with it, keeping it as generic as possible; e.g. context knows nothing about "devices", that is isolated within the devices preview-app, the context exposes the iframe wrapper element, so that the device dimensions can be applied directly.
> [!NOTE]
> Outstanding tasks, _(that are outside the remit of this PR)._
> - The …
> Feature: Document Preview

- src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
- src/packages/media/media/property-editors/image-cropper/property-editor-ui-image-cropper.element.ts
Fixed an issue where the image would not be removed in `Image Cropper` if it was a image that came from the server.
> Bugfix: Fix image cropper remove issue

- src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
- src/packages/media/media/components/input-image-cropper/image-cropper-preview.element.ts
- src/packages/media/media/components/input-image-cropper/image-cropper.element.ts
Fixes an issue where size calculation would happen before the image was loaded resulting in large images overflowing the borders of the image focus setter and the previews
> Bugfix: Image Cropper Overflow

- src/packages/media/media/components/input-media/input-media.element.ts
- src/packages/media/media/property-editors/media-entity-picker/property-editor-ui-media-entity-picker.element.ts
- src/packages/media/media/property-editors/media-picker/components/index.ts
- src/packages/media/media/property-editors/media-picker/components/input-rich-media/index.ts
- src/packages/media/media/property-editors/media-picker/components/input-rich-media/input-rich-media.element.ts
- src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
- src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
@loivsen, I was looking over PR #1840 (branch `feature/media-picker-filter-and-media-input-config`), and noticed properties added to the `umb-input-media` component (for focal point and crops), which may cause us a potential issue with the different use-cases between the **Media entity picker** (that stores the Guid values) and the **richer Media Picker** (that stores the focal/crop data).
This PR adds in a `umb-input-rich-media` component (that inherits from `umb-input-media`, so not to duplicate too much code), and adds the newer features.
Let me know what you think about these changes.
> Feature: Adds `umb-input-rich-media` component

- src/packages/core/property/property/property.element.ts
This ensures that if, say, a textarea is saved with "rows=10" without touching the input box at all
**Before**
**After**
1. Create a new data type
2. Select textarea
3. Hit save
4. Verify that the default configuration is saved, i.e. rows=10
> fix: ensure any property editor UIs save their initial value on the context

- src/packages/documents/documents/entity-actions/unpublish.action.ts
- src/packages/documents/documents/entity-bulk-actions/unpublish/unpublish.action.ts
Dispatch request reload event after unpublish and unpublish bulk actions.
* Test that a collection publishing state is updated when using the bulk actions.
* Test that a collection publishing state is updated when using the tree item actions
> Bugfix: request reload of entity after unpublish

- src/packages/core/icon-registry/icon.stories.ts
The Icons docs in Storybook was displaying all icons, including those marked as `legacy`.
https://apidocs.umbraco.com/v14/ui/?path=/docs/umb-icons--docs
I have updated the story to only display the icons approved for use in the backoffice.
> Chore: Storybook: Hide legacy icons

- src/libs/extension-api/functions/create-extension-element.function.ts
Stop firing a console error when there is a elementName defined.
> Bugfix: using elementName should not fire console error 

- src/packages/documents/documents/entity-actions/manifests.ts
- src/packages/documents/documents/entity-bulk-actions/manifests.ts
- src/packages/user/user/entity-bulk-actions/manifests.ts
I don't think there is a point in rendering these actions in the UI as the implementation hasn't been started yet. I think it adds to the impression of "things not working" that these are present but only show a console.log or an alert. We can add these back as soon as they are implemented.
The removed actions are:
* Document - set user group
* Document - notifications
* Document - bulk move
* Document - bulk copy
* Document - bulk trash
* User - bulk set user group
> Chore: Temp remove not started entity actions

- src/packages/core/property/property-layout/property-layout.element.ts
adds `overflow-x: auto` to both the label and the description in case very wide content has been added such as an image
**before**
**after**
> Feature: allow wide content in property descriptions

- src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
Fixes issue #1663
Lower the document tree item opacity when the document is a draft.
> Bugfix: lower document tree item opacity on drafts

- src/packages/documents/documents/tree/manifests.ts
- src/packages/media/media/tree/manifests.ts
The media tree was throwing a js error when rendering the root (ex: in pickers). It is now fixed by using a default tree item for the media root.
* When you try to move a media item underneath a media "folder" the tree wouldn't show up in the picker.
* Make sure you can see the media tree when trying to move a media item
> Bugfix: Fix media tree root element

- src/packages/core/collection/default/collection-default.context.ts
In the default Collection context, determine if `filter.skip` has a preconfigured value.
/cc @nathanwoulfe
> Bugfix: Collection: determine if `filter.skip` has preconfigured value

- src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
To support the legacy data format of the [Content Picker](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/content-picker), and the backend will only accept a single `Guid` (`string`) value, not a comma-separated string, so we need to enforce that `max = 1`.
> Bugfix: Document Picker: Ensures `max = 1`

- src/packages/core/components/input-entity/input-entity.element.ts
- src/packages/documents/documents/components/input-document/input-document.element.ts
- src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
- src/packages/members/member/components/input-member/input-member.element.ts
In the input components for some of the picker editors, the `addValidator()` was being made inside the `connectedCallback()`, this could lead to potential issues as the component may be added to the DOM multiple times. This PR moves the `addValidator()` calls to the `constructor()`.
> Bugfix: Picker inputs - moved `addValidator()` calls to `constructor()`

- src/packages/core/property/property-layout/property-layout.element.ts
Instead of `overflow-x` we should use `uui-scroll-container` which preserves some styling choices.
I have also made sure that the title field works with very long word.
I also considered using `word-break: break-word` on the description, but as we don't know what's in there and it now has a scroll container, I don't think it's a good idea to limit the width of regular text to the outer width of the box.
**Before**
**After**
> Bugfix: Property descriptions should use uui-scroll-container

- src/packages/core/property/property/property.element.ts
- src/packages/data-type/repository/detail/data-type-detail.repository.ts
- src/packages/data-type/workspace/data-type-workspace.context.ts
- src/packages/data-type/workspace/views/details/data-type-details-workspace-view.element.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
Revert some potentially bad code and correcting the way we set default values in data-type workspace
The code to be reverted is of this PR:https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1760
That code seems to work fine, but could lead to unexpected results and would be hard to debug in the future.
Also the scenario that was built on top of was wrong, which leads to the rest of the changes of this PR.
In data-type configuration editor, Instead of setting a default value when a value is undefined, we now will only set the default values when a data-type is new or when the property editor is changed.
problem with old approach was that if new default came along after the creation of a data-type then you might get that set without your awareness.
before this PR your values was also …
> Reset data-type configs when switching property editor

- src/packages/documents/documents/entity-actions/public-access/public-access.action.ts
The entity action didn't await the modal finishing its flow before the action was done executed. It resulted in the section sidebar menu closing before the entity action opened its modal.
> Bugfix: fix public access opened from the tree

- src/assets/lang/en.ts
- src/packages/core/content-type/modals/property-type-settings/property-type-settings-modal.element.ts
If there is a custom regex for validation on a property editor, and we cannot match it with our existing regex'es, it is always a custom one, and we should just show it to the user.
Also added localization to the area.
Also added a default "custom validation" regex string, so the user doesn't save an empty regex. This also lets the uui-select underneath actually show it as selected (for some reason it cannot immediately select an empty value, which I think is a bug in UUI).
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16356
1. Create a property editor on a document and choose one of the predefined validations, e.g. validate as number
2. Test that the regex is saved, and after reload, that it is still visible
3. Now change it to "...or enter a custom validation" and set a custom …
> Bugfix: Restore custom validation on property editors

- src/apps/app/app.element.ts
- src/packages/core/utils/index.ts
- src/packages/core/utils/path/has-own-opener.function.test.ts
- src/packages/core/utils/path/has-own-opener.function.ts
Only assume we are in iframe mode if the origin of the opener matches the current origin. This allows the user to open the Backoffice with `window.open` without staying in this "iframe mode" where the user just sees a message to close the window again.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16373
1. Make sure you dont have any tokens in local storage
2. Now open a fresh Backoffice with `window.open("https://localhost:44339/umbraco")`
3. Ensure that you are redirected to the content section after login and dont get stuck on the "You may now close this window" page
4. (Optional) Let the session time out, so you see the timeout screen and make sure that the _actual_ iframe mode still works
> fix: the backoffice does not work with window.open

- src/packages/media/media/section-view/media-section-view.element.ts
There was a bug on the Media section (default view) with the Collection's configured layouts not being displayed (defaulting to loading from the `collectionView` manifests, for Media).
This PR fixes this by including the `layouts` configuration.
Partial fix for https://github.com/umbraco/Umbraco-CMS/issues/16374
> Bugfix: Media Collection (Section View) missing layouts

- src/packages/relations/relation-types/collection/manifests.ts
- src/packages/relations/relation-types/collection/relation-type-collection.element.ts
- src/packages/relations/relation-types/collection/relation-types-collection.element.ts
- src/packages/relations/relation-types/workspace/relation-type-root/relation-type-root-workspace.element.ts
- src/packages/relations/relation-types/workspace/relation-type/views/relation-type-detail-workspace-view.element.ts
UI amends to the Relation Types workspace:
- Adds a toolbar, to remove the visual gap in the header
- Adds a `<uui-loader>` on the Relation Types workspace (collection)
- Localizes the headline in the Relation Type root workspace
> Chore: Relation Types UI amends

- src/assets/lang/en.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
- src/packages/documents/documents/workspace/views/info/utils.ts
- src/packages/media/media/workspace/views/info/media-workspace-view-info-history.element.ts
Maps up the rest of the audit items with translation keys.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16293
> Bugfix: Audit log are missing a few translations

- src/packages/core/extension-registry/models/index.ts
- src/packages/core/extension-registry/models/section-route.model.ts
- src/packages/core/router/index.ts
- src/packages/core/router/types.ts
- src/packages/core/section/section-default.element.ts
- src/packages/core/utils/path/path-encode.function.ts
- src/packages/core/workspace/manifests.ts
- src/packages/core/workspace/section-routes/manifests.ts
- src/packages/core/workspace/section-routes/workspace-section-route.route-entry.ts
This PR introduces a new extension point to the default section element. Section routes make it possible to add custom routes to all sections. We use it ourselves to register the workspace route. This is the solution To fix up a circular dependency between the section and workspace route constants.
***Manifest example***
``` js
const manifest = {
type: 'sectionRoute',
alias: 'Umb.SectionRoute.Workspace',
name: 'Workspace Section Route',
element: () => import('../workspace.element.js'),
api: () => import('./workspace-section-route.route-entry.js'),
meta: {
path: '/some-path' // optional
}
};
```
***API example***
``` ts
export class UmbWorkspaceSectionRouteEntry implements UmbApi, UmbRouteEntry {
getPath(): string {
return UMB_WORKSPACE_PATH_PATTERN.toString();
}
setup(element: …
```
> Feature: Extendable section routes

- .eslintrc.json
When PR #1897 and #1898 are merged. This PR should hopefully go through 🤞 
This PR bumps the `maxDepth` setting from `2` -> `6` for the eslint rule to check for circular dependencies. I am unsure how tough it will be for VS Code, but we will have to evaluate it after some time. The goal is to delete the max depth setting.
This will help us better prevent circular dependencies moving forward.
> Chore: Bump no cycle max depth to 6

- src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts
In the Media info tab, when there are no links the message was incorrect as it was referencing the wrong localization key.
This PR corrects the localization key. Also removed the culture from being displayed, as media doesn't (currently) have variants.
This fixes https://github.com/umbraco/Umbraco-CMS/issues/16395.
> Bugfix: Media info links, corrected localization for no links

- src/packages/documents/document-types/workspace/document-type-workspace.context.ts
- src/packages/documents/document-types/workspace/views/settings/document-type-workspace-view-settings.element.ts
In the Document Type settings tab, the **History Cleanup** fields were not wired up yet.
This PR wires up the UI and updates the Document Type structure data in the context.
I have also added the localization keys for the other labels.
This fixes https://github.com/umbraco/Umbraco-CMS/issues/16295.
> Bugfix: Document Type: History Cleanup UI

- src/packages/documents/documents/entity-actions/public-access/modal/public-access-modal.element.ts
In a Document's Public Access modal, the member group field was using the **member type** picker component. 
This PR corrects this to use the **Member Group** picker component.
This fixes https://github.com/umbraco/Umbraco-CMS/issues/16259.
> Bugfix: Public Access, corrected Member Group picker

- src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
In the Document info tab, the clicking on the Document Type opened a blank modal. The bug was due to the Template modal route controller was overwriting the Document Type modal route, so didn't work.
This PR fixes that bug, and also tidies up the cod and markup.
This will fix https://github.com/umbraco/Umbraco-CMS/issues/16283.
> Bugfix: Document workspace info, fixes document type modal

- src/packages/core/components/code-block/code-block.element.ts
I was looking to reuse the `umb-code-block` component, (still a work-in-progress). I didn't need the `language` property, but then the header doesn't display, so I've refactored accordingly.
> Chore: `umb-code-block`, display header (without language)

- src/apps/backoffice/backoffice.context.ts
- src/apps/backoffice/components/backoffice-main.element.ts
- src/packages/user/current-user/current-user.context.ts
This PR fixes the section you get redirected to when opening the backoffice at the "root" location: "/". 
The PR removes the "magic" fallback to the first section and instead relies on the first section the user is allowed to see.
This solution is not bulletproof as we still rely on the "correct" section to be registered when we look them up. Unfortunately, we need to get the metadata from the manifest to get the section path. Using the section manifest alias as the path would probably have been better than a custom path value. Then we would have it available at all times and it also ensured a unique path.
Unfortunately, it also removes the redirect from a section that doesn't exist to the first one. But as we currently don't know what and when a section exists in the system then we don't …
> Bugfix: Initial section

- src/packages/search/search-modal/search-modal.element.ts
Fixes: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1875
Temp solution to add light dismiss (closing on outside click) to the global search modal.
We should look into adding a property in UI Library that allows for native light dismiss on all our modals.
> Bugfix: Close global search on outside click

- src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
- src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
This adds the description field to the document type editor. It also adds the description to the Document Create Options Modal.
This partly fixes https://github.com/umbraco/Umbraco-CMS/issues/16391
NB! We are now able to save descriptions, and not lose migrated data, however we still lack descriptions on the different item pickers because the item models do not carry the description with them.
Add a description to a doc type:
Make sure it shows up in the options creator modal:
> Feature: Document Type Descriptions

- src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
Adds descriptions to member types.
NB! There are currently no usages for this description as we do not have the create options modal for members, because the member section is currently implemented as a section without folders or a menu tree, where that options modal would normally be used.
1. Add a description to a member type
2. Verify the description is still set upon reload
> Feature: Member Type Descriptions

- src/apps/app/app.element.ts
- src/packages/core/auth/auth.context.ts
- src/packages/core/auth/models/openApiConfiguration.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16431
The generated OpenAPI client runs `encodeURI` on all URLs, which works nicely except for files, where we query with a filepath. The problem is that `encodeURI` doesn't care about slashes, but it cares about many other things, so when we encode `/file.css` it becomes `%2Ftest.css` which then gets further encoded by OpenAPI to `%252Ftest.css`, which is handled well by Kestrel but not by IIS. This fix essentially turns off the built-in encoding from the OpenAPI client and relies on the implementor to encode everything manually, which we already do.
The problem is most apparent in "static files" which lead with a slash, which gets double-encoded (stylesheets, scripts, partials).
> fix: turn off generated url encoding for `OpenAPI`

- src/packages/block/block-grid/context/block-grid-entries.context.ts
- src/packages/block/block-list/context/block-list-entries.context.ts
- src/packages/block/block-rte/context/block-rte-entries.context.ts
- src/packages/block/block-rte/workspace/block-rte-workspace.modal-token.ts
- src/packages/block/block/context/block-entries.context.ts
- src/packages/block/block/workspace/block-workspace.context.ts
Fixes a problem where a Block Modal does not have enough data about the area of which the editing is taking place, resulting in the Block begin appended to the root, not in the area.
To fix this I move the workspace modal registration into each implementation to ensure type awareness — This can maybe be optimised later, but for now it gives clarity.
Simply because the problem was that the modal did not knew about the areaKay or parentUnique, which resulted in the update taking place in the root.
Create similar scenario like this. Explore when adding another Block and editing that block, a copy will be placed in the root.
> Fix: editing block in Area

- src/external/diff/index.ts
- src/packages/documents/documents/modals/rollback/rollback-modal.element.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
Fixes missing colors on some properties in the diff text
Adds description of diffs and the meaning of the colors
Adds better styling including a table for properties and support for themes:
> Bugfix: Rollback diff text

- src/packages/core/collection/collection.element.ts
- src/packages/core/collection/default/collection-default.context.ts
- src/packages/core/extension-registry/collection/repository/extension-collection.repository.ts
- src/packages/core/extension-registry/extension-element-and-api-slot-element-base.ts
- src/packages/data-type/collection/repository/data-type-collection.repository.ts
- src/packages/dictionary/collection/repository/dictionary-collection.repository.ts
- src/packages/documents/documents/collection/repository/document-collection.repository.ts
- src/packages/language/collection/repository/language-collection.repository.ts
- src/packages/media/media/collection/repository/media-collection.repository.ts
- src/packages/members/member-group/collection/repository/member-group-collection.repository.ts
- src/packages/relations/relation-types/collection/repository/relation-type-collection.repository.ts
- src/packages/relations/relations/collection/repository/relation-collection.repository.ts
- src/packages/webhook/collection/repository/webhook-collection.repository.ts
Refactored `UmbCollectionElement` to reuse `UmbExtensionElementAndApiSlotElementBase`.
> Bugfix: Clean up event listeners when collection context is destroyed

- src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
- src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
- src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts
Following on from #1948, I'd noticed that the "Reset focal point" button wasn't working correctly. This PR fixes the functionality.
> Bugfix: Image Cropper, focal point reset

- devops/localization/unused-language-keys.js
- src/packages/documents/documents/workspace/views/info/utils.ts
Adds missing localization variable for the "Custom" status and improves the Node.js devops script to find unused keys.
> The document `Custom` status is not translated correctly

- src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts
Redirects the partial view on create correctly.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16451
> Bugfix: Redirects the Partial View on Create

- .eslintrc.json
- devops/eslint/rules/no-relative-import-to-import-map-module.cjs
- eslint-local-rules.cjs
- src/libs/class-api/class.interface.ts
- src/libs/class-api/context-base.class.ts
- src/libs/class-api/context.interface.ts
- src/libs/class-api/controller-base.class.ts
- src/libs/controller-api/controller-host.mixin.ts
- src/libs/element-api/element.interface.ts
- src/packages/property-editors/collection/property-editor-ui-collection.element.ts
- src/packages/property-editors/date-picker/property-editor-ui-date-picker.element.ts
- src/packages/property-editors/multiple-text-string/property-editor-ui-multiple-text-string.element.ts
- src/packages/property-editors/number-range/property-editor-ui-number-range.element.ts
- src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
- src/packages/property-editors/slider/property-editor-ui-slider.element.ts
- src/packages/property-editors/toggle/property-editor-ui-toggle.element.ts
- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
- web-test-runner.config.mjs
This PR adds an es lint rule to help us import modules with an import alias instead of a relative import. The relative import becomes problematic when we start bundling each module because then the module will include the relatively imported code instead of leaving the import as an external dependency.
> Chore: EsLint Rule No relative import to import map module

- src/packages/core/components/input-with-alias/input-with-alias.element.ts
- src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
- src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
- src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
- src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts
In the Document Type Workspace, the "Enter a name..." and "Enter an alias..." placeholder labels for the inputs were hardcoded to English. This PR updates with the localization keys.
> Bugfix: Document Type Workspace, localizes the name and alias input placeholders

- src/packages/media/media/workspace/views/info/media-workspace-view-info-reference.element.ts
When a Media item hasn't been references elsewhere, the text in the workspace info references panel displayed `"This Data Type has no references."`, as it was using the incorrect localization key. This PR corrects the localization key.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16485
> Bugfix: Media workspace info references correct localization

- src/packages/core/components/input-with-alias/input-with-alias.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-tab.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
- src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
- src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
- src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
- src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts
Cosmetics to Content Type workspace header UIs, to help towards tightening up the layout and aligning a little more with v13 UI.
I've applied the following...
- Icon picker, added border and positioning, to align with the property group panels
- Fixed the height of the tabs bar, as it changed when a tab was added
- Used flexbox for the tab bar actions, e.g. Composition/resize buttons, for spacing consistency
- Extra height on the "add property" and "add group" buttons, for prominence and alignment with v13 UI
- Property group's name input, made full width and transparent border, (border shows on hover), to align with v13 UI
- Added `auto-width` to the alias input-lock, so that the full alias can be displayed
**Before**
**After**
I have applied these amends to the **Document Type**, …
> Bugfix: Content Type workspace header UI cosmetics

- src/packages/media/media-types/entity-actions/move-to/manifests.ts
- src/packages/media/media-types/tree/media-type-tree.server.data-source.ts
Only render folders when moving a media type
* Make sure that you can only see folders in the tree when selecting a destination for the media type
> Bugfix: Only render folders for move media type

- package-lock.json
- package.json
- src/packages/dictionary/package.json
- src/packages/dictionary/vite.config.ts
This is the beginning of bundling our modules. Unfortunately, bundling all the modules before v15 might not be possible because some files are located incorrectly. These files can't be moved without a breaking change. Therefore, We will go through the modules one by one, and bundle the possible ones.
This PR sets up the basic build script for bundling. The build is made with npm workspaces which makes it possible to run a "local" build script in each package. The bundling is done by Vite.
We now have one for the npm package, which is not bundled, and one for the CMS which will be partly bundled. 
The idea is to build the same way as before but swap out the "old" module files for the bundled ones when a module is ready. 
1. Run the `npm run build:for:cms` script in the CMS project. 
2. …
> Chore: Bundling dictionary module

- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
Removes older CSS additions that should no longer be relevant to TinyMCE v6 such as z-index, which messes with the box-shadow.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16518
There is now a box-shadow under the toolbar:
> Bugfix: TinyMCE does not show its box-shadow

- public-assets/App_Plugins/tinyMcePlugin.js
- src/mocks/handlers/manifests.handlers.ts
- src/packages/core/extension-registry/models/tinymce-plugin.model.ts
- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
Some configurations such as `statusbar`, `menubar`, and other visuals are invalid to add after the editor has been rendered. To accommodate this, we are adding a `config` object to the manifest file which essentially supports the same options as the former `CustomConfig` in V13.
There is also a fix for async-loaded extensions, which were previously not considered after the editor was rendered. Now we have an observer on the extensions registry and in case a `tinyMcePlugin` is added or removed, we will re-render the editor and merge the new configuration.
**Dev server**
1. Turn on the `VITE_UMBRACO_EXTENSION_MOCKS=on` environment variable
2. Notice that the RTE on the "All properties" page are shown with a statusbar and the wordcount plugin
You have to remove these lines from …
> Feature: TinyMce Custom Configuration

- .eslintrc.json
- package-lock.json
- package.json
- src/packages/data-type/entity-actions/manifests.ts
- src/packages/data-type/package.json
- src/packages/data-type/repository/detail/constants.ts
- src/packages/data-type/repository/detail/index.ts
- src/packages/data-type/repository/detail/manifests.ts
- src/packages/data-type/repository/item/constants.ts
- src/packages/data-type/repository/item/index.ts
- src/packages/data-type/repository/item/manifests.ts
- src/packages/data-type/vite.config.ts
- src/packages/dictionary/package.json
- src/packages/dictionary/vite.config.ts
- src/packages/webhook/package.json
- src/packages/webhook/vite.config.ts
- src/vite-config-base.ts
Please review #1980 first
This PR adds bundling for the Data Type package.
> Chore: Bundling data type package

- src/packages/templating/stylesheets/components/stylesheet-rule-input/stylesheet-rule-settings-modal.element.ts
- src/packages/templating/stylesheets/utils/stylesheet-rule-manager.ts
- In stylesheets, the "styles" and "preview" is no longer showing as required.
- Leaving the styles empty in a stylesheet no longer results in "undefined" being printed in the css stylesheet.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16500
> Makes the styles optional in stylesheets

- src/packages/core/menu/menu-tree-structure-workspace-context-base.ts
When creating a new entity at the root, the workspace breadcrumbs (menu-tree-structure) code will throw an error in the console...
```
menu-tree-structure-workspace-context-base.ts:65 Uncaught (in promise) Error: Unique is not available
at #requestStructure (menu-tree-structure-workspace-context-base.ts:65:22)
```
This is because the entity root's unique value is typically set to `null`.
This fix moves the `entityType` observer before the `unique` observer, then checks if the entity-type is the same as the root's entity-type, if so, then there is no need to request the ancestor tree items.
> Bugfix: Workspace breadcrumbs, error when new at root

- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
This sets `convert_unsafe_embeds` to true to act as a workaround for CVE-2024-29881 seeing that we cannot upgrade to tinymce 7 at the moment. The only difference from TinyMCE 6 to 7 in this regard is that this option is set to true and is the official workaround.
Fixes https://github.com/umbraco/Umbraco.CMS.Backoffice/security/dependabot/44
> Bugfix: Tinymce allows potentially unsafe embeds

- src/assets/lang/en-us.ts
- src/assets/lang/en.ts
- src/packages/documents/documents/entity-actions/public-access/manifests.ts
- src/packages/documents/documents/entity-actions/public-access/modal/public-access-modal.element.ts
- src/packages/documents/documents/entity-actions/public-access/public-access.action.ts
- src/packages/documents/documents/entity-actions/public-access/repository/public-access.repository.ts
- src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16548
This PR ensures that the "Public Access"-entity action is wired up. The PR also adds an icon to the document tree item to show when a document is protected.
The member endpoints require access to the member section to work. We have the same limitation in V13. I have decided to hide the "Public Access"-entity access if a user doesn't have access to the member section. Then we prevent the UI from exploding.
**What to test:**
* Set public access settings for a document
* individual members
* member groups
* Remove public settings for a document
* Check that the protected icon is shown in the tree
> Bugfix: Document Public Access cancelled server requests

- src/libs/context-api/consume/context-consumer.test.ts
- src/packages/core/property/property-dataset/property-dataset.element.test.ts
- src/packages/core/utils/pagination-manager/pagination.manager.test.ts
The method only takes 2 arguments, but we pass 3. I don't know why this hasn't shown up before.
> Chore: Remove arg passed to oneEvent method

- src/packages/templating/modals/templating-page-field-builder/templating-page-field-builder-modal.element.ts
Fixes overflow in modal when inserting a field value 
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16491
> Bugfix: Insert field value overflow

- examples/sorter-with-nested-containers/sorter-dashboard.ts
- examples/sorter-with-nested-containers/sorter-group.ts
- src/packages/core/sorter/sorter.controller.ts
Improved example to actually demonstrate how nested sorter controller can work in a infinite group situation.
As well this does a minor refactor of the Sorter Controller, while thinking about supporting ability to define a Handle Selector, but this is instead created as a task in the backlog.
> Improved example + minor code refactor

- src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
- src/packages/media/media/tree/tree-item/media-tree-item.element.ts
Fixes our custom menu item labels in documents and media so that it correctly shows ellipsis
Before:
After:
> Bugfix: Custom menu item label ellipsis

- src/packages/property-editors/text-box/property-editor-ui-text-box.element.ts
This PR adds `readonly` mode to the Text Box Property Editor UI
> Feature: Readonly mode for Text Box Property Editor UI

- src/packages/property-editors/number/property-editor-ui-number.element.ts
This PR adds `readonly` mode to the Number Property Editor UI
> Feature: Readonly mode for Number Property Editor UI

- src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
- src/packages/documents/document-types/repository/item/document-type-item.server.data-source.ts
- src/packages/documents/document-types/repository/item/types.ts
This maps the `description` property to the doc type model and displays it for block types.
Since the `description` field was added in https://github.com/umbraco/Umbraco-CMS/pull/16503 it is now possible to fix this issue.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16642
1. Add a description to an element type and add that type to a block property editor
2. Add at least an addition block type (otherwise the block catalogue will not be shown)
3. Verify that the description is shown underneath the name
**Before**
**After**
> Bugfix: Block types do not show their descriptions

- src/packages/block/block-grid/context/block-grid-entry.context.ts
- src/packages/block/block/context/block-entries.context.ts
- src/packages/block/block/context/block-entry.context.ts
Makes a Block with no Column Span options, get corrected to the local layout columns(if in area, then that is the columns of the area).
Before this did no happen and a Block would not get any column span, it would look 1 column wide, aka. spanning only one column.
> Block Grid: fallback to layout columns if no proper options

- src/packages/block/block-grid/components/block-grid-area-config-entry/workspace/block-grid-area-type-workspace.context.ts
- src/packages/block/block-grid/property-editors/block-grid-type-configuration/property-editor-ui-block-grid-type-configuration.element.ts
- src/packages/block/block-grid/workspace/block-grid-type-workspace.modal-token.ts
- src/packages/block/block-grid/workspace/block-grid-workspace.modal-token.ts
- src/packages/block/block-grid/workspace/index.ts
- src/packages/block/block-list/workspace/block-list-workspace.modal-token.ts
- src/packages/block/block-rte/workspace/block-rte-workspace.modal-token.ts
- src/packages/block/block-type/workspace/block-type-workspace.context.ts
- src/packages/block/block/workspace/block-workspace.modal-token.ts
- src/packages/core/modal/context/modal.context.ts
- src/packages/data-type/workspace/data-type-workspace.modal-token.ts
- src/packages/documents/document-types/workspace/document-type-workspace.modal-token.ts
- src/packages/language/workspace/language/language-workspace.modal-token.ts
Makes `Allow in root` checked when creating a new Block Type
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16466
> Make allowAtRoot preset for Block Grid Types

- src/packages/media/media/components/input-media/input-media.element.ts
The last image card would not be removed (when trashing it) from `umb-input-media` when outside a property editor.
Fixes https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/2032
> Bugfix: Remove image card when trashed outside a property editor

- src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
Fixes: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1905
Enables the user to focus the trash button with keyboard navigation
> Bugfix: Content type editor keyboard navigation

- src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
- src/packages/data-type/components/data-type-input/index.ts
- src/packages/data-type/components/index.ts
- src/packages/dictionary/components/index.ts
- src/packages/dictionary/components/input-dictionary/index.ts
- src/packages/dictionary/index.ts
- src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
- src/packages/templating/partial-views/components/index.ts
- src/packages/templating/partial-views/components/input-partial-view/index.ts
- src/packages/templating/partial-views/index.ts
- src/packages/templating/scripts/components/index.ts
- src/packages/templating/scripts/components/input-script/index.ts
- src/packages/templating/scripts/index.ts
- src/packages/templating/stylesheets/components/index.ts
- src/packages/templating/stylesheets/components/stylesheet-input/index.ts
- src/packages/templating/stylesheets/index.ts
- src/packages/templating/templates/components/index.ts
- src/packages/templating/templates/components/input-template/index.ts
The Package builder was using relative imports across different packages. That doesn't work anymore because files are bundled. The correct way to import from another package is through the exposed importmap.
> Bugfix: Package Builder import errors

- src/packages/block/block-grid/components/block-grid-area-config-entry/block-grid-area-config-entry.context.ts
Making the Block Grid Areas Property Editor UI propagate changes to the property value, so it can be persisted.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16640
> Hotfix: Propagate data changes for Block Grid Area Types

- src/packages/core/components/split-panel/split-panel.element.ts
You can't scroll in the side panel, only make the panel wider.
Example of the issue.
You can only make the panel wider. 
From a users point of view, you can't scroll down to select any other items that might be visible in the left hand side.
The issue is the div with the class id divider-touch-area is sitting over the top of the scroll bar. The fix was to move this div 5px to the left and this then allows the user to scroll and still make the panel wider. 
See screenshot above, and the fix demo :
> [FIX] Scroll Bar / Panel Width Adjustment cursor

- src/packages/core/components/table/table.element.ts
Adds `background-color` to `<umb-table>` header, so that it is visible (non-transparent) on scroll/sticky.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16467.
_(Also did some text/whitespace formatting on the code file.)_
> Adds background-color to umb-table header

- web-test-runner.config.mjs
The current Log filter, to filter out 'Lit is in dev mode', didn't seem to do the job. I have added an alternative implementation to filter out unwanted logs.
* The test logs should no longer include a warning about Lit being in dev mode.
> Chore: Fix test runner log filter

- src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
- src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
The dropzones for media picker and upload field are now clickable.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16450
> Bugfix: Dropzones should be clickable

- eslint.config.js
Eslint is complaining a lot on windows now.
Changing to warn and allowing linebreaks.
Example on windows without the changes:
after
> ESLint linebreak on windows

- src/packages/block/block/workspace/block-workspace.context.ts
Makes Block Grid Editor only set its data if its not in Live Editing Mode. Cause otherwise they end up competing with each other and eventually out rule the corrections made by the Property Editor.
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16227
This makes sure the Block Workspace observes data of the Property Editor while in create-state, in this way the corrections made of the Property Editor, like rowSpan setting, gets set and the Block Workspace receives that correction.
Only sets the Blocks data if its not in live editing mode. Cause setting these will eventually overwrite the corrections from the Property Editor.
> hotfix: block grid live editing race condition

- src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
Creates a new data type configuration directly when this option is picked, rather than going through a second modal.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16472
> Bugfix: Create new datatype configuration directly

- src/packages/core/collection/components/collection-view-bundle.element.ts
Hides the Collection View menu popover when an option is selected.
A timeout of 100ms is in place, as the Collection View is routable, so gives a small delay on the interaction.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16273
Also fixed a couple of minor cosmetic issues with the Collection View menu.
> Bugfix: Collection View menu close on selection

- src/packages/core/content-type/components/property-type-based-property/property-type-based-property.element.ts
- src/packages/core/property/property-layout/property-layout.element.ts
- src/packages/core/property/property/property.context.ts
- src/packages/core/property/property/property.element.ts
Adds mandatory indicator to a property's label.
The `validation` object is also exposed in the property's context (observing `UmbPropertyContext`'s `validation`).
> Feature: Property label mandatory indicator

- src/packages/media/imaging/constants.ts
- src/packages/media/imaging/imaging.repository.ts
- src/packages/media/imaging/imaging.store.token.ts
- src/packages/media/imaging/imaging.store.ts
- src/packages/media/imaging/manifests.ts
- src/packages/media/media/collection/media-collection.context.ts
- src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Some web servers carry a limit to the length of the request path. This harms the media thumbnail generator, which is a GET endpoint. We cannot change the backend as that would be a breaking change, nor do we wish to do it because of the purity of REST. So we are going to make a network request for each thumbnail instead. This is exactly what the old Backoffice did as well.
There are some advantages to doing this besides fixing the web servers: We can now space out the calls and wait until the elements are visible before initiating the request -- we will look into some of this in subsequential PRs.
The thumbnails are now also being cached in memory through a store in a nested map based on the media key (GUID) and thumbnail options (width, height, mode). This results in far fewer network …
> Bugfix: Resized media urls result in the request path being too long

- src/packages/ufm/components/ufm-render/ufm-render.element.ts
Hotfix for 14.1.
Ensures word-wrapping for child elements inside the `<umb-ufm-render>` component.
Before
After
> Hotfix: Ensures word-wrap for `<umb-ufm-render>` component

- src/packages/media/imaging/components/imaging-thumbnail.element.ts
- src/packages/media/imaging/components/index.ts
- src/packages/media/imaging/imaging.repository.ts
- src/packages/media/imaging/index.ts
- src/packages/media/imaging/types.ts
- src/packages/media/media/collection/media-collection.context.ts
- src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
- src/packages/media/media/components/input-media/input-media.element.ts
- src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
- src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Adds a `<umb-imaging-thumbnail>` element to fetch and show thumbnails. This replaced manual logic in the Media picker, media picker modal, input-media, and media collection.
The thumbnail component also holds an IntersectionObserver to ensure the images are not fetched (neither the thumbnail URL nor the image resource) before they are visible.
We want to achieve the following:
1. Thumbnails are loaded in parallel
2. Thumbnails are loaded in the same way across the application (shared logic)
3. Thumbnails are only loaded when needed (intersected)
4. The fallback logic is the same across
5. Ensure good a11y for thumbnail figures
6. Ensure images are loaded in the expected size and no bigger than what is needed
1. Upload more than a couple of rows of media to a folder in the Media Library
2. …
> Feature: Imaging thumbnail component to load thumbnails in parallel

- src/packages/property-editors/date-picker/property-editor-ui-date-picker.element.ts
- src/packages/property-editors/date-picker/property-editor-ui-date-picker.test.ts
The server always expects a regular DateTime string because the property value converter does not consider the config. The value will be unset if the string does not validate as a DateTime.
This PR aims to differentiate between input and output dates to communicate the expected value to the underlying date input component. The UI component expects the following:
| Format | Inner input | Output |
|--------|-------|--------|
| datetime-local | YYYY-mm-dd HH:ii(:ss) | YYYY-mm-dd HH:ii:ss |
| date | YYYY-mm-dd | YYYY-mm-dd HH:ii:ss |
| time | HH:ii(:ss) | YYYY-mm-dd HH:ii:ss |
Because of this, we have to patch the value coming out of the UI into a regular DateTime. Vice-versa we have to patch the value from the database into the expected _inner input_ value.
Fixes …
> Bugfix: Date Picker with only "date" or "time" does not display correctly

- src/assets/lang/en.ts
- src/packages/core/section/section-sidebar-menu-with-entity-actions/section-sidebar-menu-with-entity-actions.element.ts
- src/packages/core/section/section-sidebar-menu/section-sidebar-menu.element.ts
- src/packages/core/settings/manifests.ts
- src/packages/dictionary/section/manifests.ts
- src/packages/documents/section/manifests.ts
- src/packages/media/media-section/manifests.ts
- src/packages/templating/menu/manifests.ts
Localizes the 'sectionSidebarApp' headers. Updates the manifests to use the relevant localization keys, also added the missing ones for Setting's "Structure" and "Advanced".
> Bugfix: Localizes 'sectionSidebarApp' headers

- src/packages/core/collection/action/collection-action-button.element.ts
- src/packages/core/collection/types.ts
- src/packages/dictionary/collection/action/manifests.ts
- src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
- src/packages/documents/documents/collection/action/manifests.ts
- src/packages/language/collection/action/manifests.ts
- src/packages/media/media/collection/action/create-media-collection-action.element.ts
- src/packages/webhook/collection/action/manifests.ts
Localizes the 'collectionAction' labels.
The Document and Media create actions use their own elements, so the localization had to be added within their own components.
> Bugfix: Localizes collection create action labels

- src/packages/core/collection/components/collection-selection-actions.element.ts
Localizes the Collection view's "Clear" button label to be "Clear selection".
> Bugfix: Localizes the Collection view's "Clear" button label

- src/packages/core/entity-bulk-action/common/duplicate-to/duplicate-to-repository.interface.ts
- src/packages/core/entity-bulk-action/common/duplicate-to/duplicate-to.action.kind.ts
- src/packages/core/entity-bulk-action/common/duplicate-to/duplicate-to.action.ts
- src/packages/core/entity-bulk-action/common/duplicate-to/index.ts
- src/packages/core/entity-bulk-action/common/duplicate-to/manifests.ts
- src/packages/core/entity-bulk-action/common/duplicate-to/types.ts
- src/packages/core/entity-bulk-action/common/index.ts
- src/packages/core/entity-bulk-action/manifests.ts
- src/packages/core/extension-registry/models/entity-bulk-action.model.ts
- src/packages/documents/documents/entity-bulk-actions/duplicate-to/index.ts
- src/packages/documents/documents/entity-bulk-actions/duplicate-to/manifests.ts
- src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/constants.ts
- src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/duplicate-to.repository.ts
- src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/index.ts
- src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/manifests.ts
- src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/types.ts
- src/packages/documents/documents/entity-bulk-actions/duplicate/duplicate.action.ts
- src/packages/documents/documents/entity-bulk-actions/manifests.ts
- src/packages/documents/documents/entity-bulk-actions/move/move.action.ts
- src/packages/property-editors/collection/config/bulk-action-permissions/permissions.element.ts
Implements the Document collection bulk duplicate (copy) feature, (as a Entity Bulk Action `duplicateTo` kind).
To note, I haven't implemented the Media equivalent feature, as the "copy" endpoint (for media) doesn't exist in the Management API. 
- Ensure that "Allow bulk duplicate" is enabled in the Collection (data-type) configuration.
- In a document that has a Collection enabled, select 1 or more document items.
- In the Collections actions toolbar (at the bottom), select the "Duplicate to" action button.
- A document picker modal should appear to select the destination/target of the items, select an item.
- If an item is selected where child document items are not allowed, an error will be displayed.
- If an item is selected where child document items are allowed, then the items will …
> Feature: Document entity bulk action "duplicate to"

- src/packages/user/user/collection/utils/index.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16252
Remove the "All" filter option from User Status
> Remove all filter option from User Status

- src/packages/documents/documents/entity-bulk-actions/delete/delete.action.ts
- src/packages/documents/documents/entity-bulk-actions/manifests.ts
- src/packages/documents/documents/entity-bulk-actions/trash/index.ts
- src/packages/documents/documents/entity-bulk-actions/trash/manifests.ts
- src/packages/documents/documents/entity-bulk-actions/trash/repository/constants.ts
- src/packages/documents/documents/entity-bulk-actions/trash/repository/index.ts
- src/packages/documents/documents/entity-bulk-actions/trash/repository/manifests.ts
- src/packages/documents/documents/entity-bulk-actions/trash/repository/trash.repository.ts
> [!CAUTION]
> This PR is marked as draft until the following PR has been merged in...
> - #2127
Implements the Document collection bulk trash feature, (as a Entity Bulk Action `trash` kind).
- Ensure that "Allow bulk trash" is enabled in the Collection (data-type) configuration.
- In a document that has a Collection enabled, select 1 or more document items.
- In the Collections actions toolbar (at the bottom), select the "Trash" action button.
- The items will be moved to the Recycle Bin, a success notification should be displayed and the Document Collection UI should be automatically refreshed.
- Expand the Recycle Bin to check that the trashed document items are there.
> Feature: Document entity bulk action "trash"

- index.html
- src/css/user-defined.css
- web-test-runner.config.mjs
> [!CAUTION]
> Merge after https://github.com/umbraco/Umbraco-CMS/pull/16792
There is not a need to have this empty file `user-defined.css` in the Backoffice client anymore.
> Chore: Remove the `user-defined.css` as it is not needed

- src/external/monaco-editor/index.ts
- src/packages/core/modal/common/code-editor/code-editor-modal.element.ts
- src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
- src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
- src/packages/templating/code-editor/code-editor-loaded.event.ts
- src/packages/templating/code-editor/code-editor.controller.ts
- src/packages/templating/code-editor/code-editor.element.ts
- src/packages/templating/code-editor/index.ts
- src/packages/templating/partial-views/workspace/partial-view-workspace-editor.element.ts
- src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts
- src/packages/templating/scripts/workspace/script-workspace-editor.element.ts
- src/packages/templating/scripts/workspace/script-workspace.context.ts
- src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts
- src/packages/templating/stylesheets/workspace/views/code-editor/stylesheet-code-editor-workspace-view.element.ts
- src/packages/templating/templates/workspace/template-workspace-editor.element.ts
- src/packages/templating/templates/workspace/template-workspace.context.ts
Refactors the `<umb-code-editor>` component to asynchronously load the Monaco editor dependencies.
The `loadCodeEditor` function has been marked as deprecated.
With the recent bundling efforts, the existing `loadCodeEditor` function has become legacy code.
Check that the following areas load in the Code Editor (Monaco editor)...
- Template workspace
- Partial View workspace
- Stylesheets workspace
- Scripts workspace
- Rich Text Editor property-editor (TinyMCE) view source button, opens a Code Editor modal
- Markdown property-editor, loads and plugins are functional
> Feature: Improve when `umb-code-editor` loads Monaco

- src/packages/core/components/split-panel/split-panel.element.ts
- src/packages/core/temporary-file/components/temporary-file-badge.element.ts
- src/packages/core/utils/math/math.ts
The UI Library already exports a `clamp` function, so use that instead of redefining it.
Ref https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1021#issuecomment-2118387247
> Chore: Do not redefine `clamp`

- src/external/router-slot/util/url.ts
- src/packages/log-viewer/workspace/logviewer-workspace.context.ts
This fixes https://github.com/umbraco/Umbraco-CMS/issues/16767
The Log Viewer should not show "undefined" in the search field if you do not have a search string.
> Bugfix: Log Viewer shows `undefined` in search field

- src/packages/property-editors/date-picker/property-editor-ui-date-picker.element.ts
- src/packages/property-editors/date-picker/property-editor-ui-date-picker.test.ts
This fixes https://github.com/umbraco/Umbraco-CMS/issues/16793
The Datepicker UI should be allowed to send empty values to clear the saved value.
> fix: allow datepicker to send empty values

- .github/localization_overview.md
- src/assets/lang/da-dk.ts
- src/assets/lang/en-us.ts
- src/assets/lang/en.ts
- src/packages/core/components/body-layout/body-layout.element.ts
- src/packages/documents/document-blueprints/entity-actions/create/modal/document-blueprint-options-create-modal.element.ts
- src/packages/documents/document-blueprints/menu-item/manifests.ts
- src/packages/documents/document-blueprints/tree/document-blueprint-tree.repository.ts
- src/packages/documents/document-blueprints/workspace/document-blueprint-root-workspace.element.ts
- src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
- src/packages/documents/document-blueprints/workspace/manifests.ts
- src/packages/log-viewer/workspace/logviewer-workspace.context.ts
- Following the changes in PR #893 the `en.ts` file was introduced with the former name of Document Blueprints (content templates). This has been corrected.
- Introduced a routable workspace for blueprint root so that the previously hidden element detailing how to use blueprints is now being shown
- Introduced new variables to account for new texts in the Create modal
- Replaced static texts with localization keys everywhere I could think of
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16410
- Check that all static texts are localized
- Try to create a Folder and check that the name of the folder is used correctly in the Create dialog when creating a new blueprint underneath a folder
- Check that notifications show the correct localization when creating, deleting, etc.
> Bugfix: Document Blueprints are not named consistently

- src/packages/property-editors/text-box/property-editor-ui-text-box.element.ts
- src/packages/property-editors/textarea/property-editor-ui-textarea.element.ts
The textarea property editor ui should show validation. This is fixed by converting the element into a form mixin that supports validation.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16436
1. Set the "max length" of a textarea data type
2. Verify that a validation message is shown in the UI
> Bugfix: Textarea does not show validation

- src/packages/core/workspace/components/workspace-action-menu/workspace-action-menu.element.ts
- src/packages/core/workspace/components/workspace-action/default/workspace-action.element.ts
By moving the calculation of the extension controllers from the action-menu element into the action element itself, we can save a few states, simplify the calculation, and conditionally render the action-menu element ensuring, that the UUI styling is correctly applied
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16362
> Bugfix: Show the action button inside a button-group only if there are extensions registered

- src/packages/core/components/table/table.element.ts
- src/packages/core/extension-registry/models/ufm-component.model.ts
- src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
- src/packages/ufm/components/ufm-render/ufm-render.element.ts
- src/packages/ufm/manifests.ts
- src/packages/ufm/plugins/marked-ufm.plugin.ts
- src/packages/ufm/plugins/marked-ufm.test.ts
- src/packages/ufm/ufm-components/label-value.component.ts
- src/packages/ufm/ufm-components/label-value.element.ts
- src/packages/ufm/ufm-components/localize.component.ts
- src/packages/ufm/ufm-components/ufm-component-base.ts
Review of UFM code, made fixes and amends, includes...
- Introduces `UfmToken` interface type, so to no longer expose Marked library's `Tokens.Generic`.
- This isn't a breaking-change, as `UfmToken` extends `Tokens.Generic`, which itself was an extendable interface.
- Adds tests for parsing the UFM syntax
- Simplified the UFM regular expression; also handles whitespace better.
- For Collection Views (Table and Grid), wraps the value in an object property, e.g. `{ value }`.
- So that accessing the value it works similar to v13 ListView. UFM syntax is now `{=value}`.
- Loosened the rendering in `<ufm-label-value>` so that non-undefined falsy values can be rendered.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16776.
General testing for dynamic labels in Collection Views, Block …
> Bugfix: UFM review, fixes and amends

- src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
The Document Blueprint create menu wasn't displaying, now it does.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16721.
- Create a document blueprint (from an existing document type).
- Try to create new content from the document blueprint, if the menu appears and you can select a blueprint, then all good.
> Bugfix: Enables document blueprint create menu

- examples/property-editor/README.md
- examples/property-editor/index.ts
- examples/property-editor/property-editor.ts
- src/assets/lang/en.ts
- src/packages/data-type/components/property-editor-config/property-editor-config.element.ts
- src/packages/data-type/workspace/data-type-workspace.context.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16808
The code was a bit messy, so i refactored so the 'flow' got simpler.
> Use the right property editor UI alias for config options

- src/packages/language/workspace/language/constants.ts
- src/packages/language/workspace/language/language-workspace.context.ts
- src/packages/language/workspace/language/manifests.ts
This add a constant for language workspace alias similar to other `ManifestWorkspaces`.
However it doesn't really seems consistent. Some are included in `manifests.ts` as here:
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/4e840b9de043f8ddb03352897c5ef2a575ca8776/src/packages/documents/document-blueprints/workspace/manifests.ts#L14C14-L14C52
while other are just in a constant.ts as here:
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/4e840b9de043f8ddb03352897c5ef2a575ca8776/src/packages/user/user/workspace/constants.ts
or  `index.ts`:
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/4e840b9de043f8ddb03352897c5ef2a575ca8776/src/packages/block/block/workspace/index.ts#L5
It would be great if it could be more consistency and easier to work with codebase.
Some places I …
> Use constant for language workspace alias

- src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
- src/packages/documents/document-types/property-editors/document-type-picker/property-editor-ui-document-type-picker.element.ts
- src/packages/webhook/workspace/webhook/views/webhook-details-workspace-view.element.ts
I'd noticed when configuring a Block type (in Block Grid, Block List or RTE Blocks), the Document Type picker UI was ignoring the `"onlyPickElementTypes"` configuration. It turns out that the `elementTypesOnly` property wasn't reading the attribute value.
Also, in a Webhook edit workspace, the "Content Type" option should only be enabled for `documentTypesOnly`, but element-types were selectable.
**Blocks**
Go to any of the Block editor data-type configurations, create a new or select an existing Block type, in the configuration modal panel, open the document-type picker modal for either "Content model" or "Settings model"... you should see that only element-types are selectable.
**Webhooks**
In the Webhooks section, create a new or select an existing webhook, open the document-type …
> Bugfix: Document Type Picker - enable boolean properties

- src/packages/members/member/workspace/views/member/member-workspace-view-member-info.element.ts
- src/packages/members/member/workspace/views/member/member-workspace-view-member.element.ts
Provides a partial fix for https://github.com/umbraco/Umbraco-CMS/issues/16079, by adding the `mandatory` markers for Username, Email and Passwords fields.
The validation mechanism still needs further development, but I wanted to try get the mandatory markers in for the 14.2.0-RC release.
This PR also has markup amends, for consistency across the other content workspace components.
> Bugfix: Member workspace, mandatory markers

- src/packages/core/components/input-with-alias/input-with-alias.element.ts
- src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
- src/packages/core/property-type/workspace/views/settings/property-workspace-view-settings.element.ts
- src/packages/templating/templates/workspace/template-workspace-editor.element.ts
Makes use of the `<uui-input-lock>` component for workspace name/alias combinations.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16246.
This PR separates out part of PR #2092, to focus on the `<uui-input-lock>` component, so to fix [the accessibility/tabbing issue](https://github.com/umbraco/Umbraco-CMS/issues/16246) (for v14.2.0-RC).
Auto-generating the alias is not part of this PR.
Test that the padlocked alias UI is accessible in the following areas:
- Document Type workspace header, name/alias field
- Media Type workspace header, name/alias field
- Member Type workspace header, name/alias field
- User Group workspace header, name/alias field
- Template workspace header, name/alias field
- Document Type > Property modal > label/alias field (inside the modal UI)
- Document Type …
> Bugfix: Use `<uui-input-lock>` for workspace aliases

- src/packages/core/property-type/workspace/manifests.ts
I've noticed that the Property Type workspace manifests had "Block" in their names.
> Chore: Property Type manifest name correction

- src/packages/core/property-action/manifests.ts
The initial property-actions (Clear and Copy) were a proof-of-concept and should not have been released with 14.0.
> Chore: Remove property-actions for textbox property-editor

- package-lock.json
- package.json
- src/packages/static-file/modals/static-file-picker-modal.token.ts
- src/packages/static-file/package.json
- src/packages/static-file/tree/constants.ts
- src/packages/static-file/tree/index.ts
- src/packages/static-file/tree/manifests.ts
- src/packages/static-file/vite.config.ts
This PR bundles the Static File Package including all modules.
> Chore: Bundle Static File Package

- package.json
The 14.2-rc package can't be installed because the `generate:tsconfig` script can't run. The issue is caused by the `postinstall` script that runs when the package is installed from npm. We don't ship any of our `devops` files which makes the script fail.
You can test a local version of the package to check that it installs correctly:
**In the backoffice repo**
1. `npm i` to ensure all dependencies are installed
2. `npm run build:for:npm` build the output files for npm
3. `npm pack` pack a local version of the npm package
4. Copy the package to a local Umbraco project where it should be installed
**In your Umbraco project**
1.  Point to the local version in your `package.json` file: `"@umbraco-cms/backoffice": "./umbraco-cms-backoffice-14.2.0.tgz"`
2.  Run `npm i` in your Umbraco project …
> Chore: Remove postinstall script

- src/packages/block/block-type/types.ts
The PR fixes a breaking change.
Export of `UmbBlockTypeBaseModel` has been moved from `@umbraco-cms/backoffice/block-type` to `@umbraco-cms/backoffice/extension-registry`. This PR reexports the type from `@umbraco-cms/backoffice/block-type`again.
> Bugfix: Reexport `UmbBlockTypeBaseModel` from `@umbraco-cms/backoffice/block-type`

- src/mocks/data/data-type/data-type.data.ts
- src/packages/block/block-grid/context/block-grid-manager.context.ts
- src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
- src/packages/core/utils/index.ts
- src/packages/core/utils/path/remove-initial-slash-from-path.function.ts
- src/packages/core/utils/path/remove-last-slash-from-path.function.ts
When configuring a `layoutStylesheet` against a BlockGrid datatype, the path to the CSS isn't resolved correctly when the front end is built and included in the NuGet package for release. The URL it is trying to be loaded from includes the backoffice path as part of the URL.
When running the Backoffice project locally, `appUrl` will always resolve to `http://localhost:5173`, whereas when running within the context of a C# project, `appUrl` will resolve to the absolute backoffice path, e.g. `https://localhost:44338/umbraco`.
See https://github.com/umbraco/Umbraco-CMS/issues/16897.
Fixes the above linked issue so that BlockGrid layouts can be rendered correctly in the backoffice, and in Custom Views, with applied CSS.
This also fixes the same issue with Block icons.
Will need to be tested …
> [v14.2.0-RC] Fix Block Grid `layoutStylesheet` not using correct URL

- src/packages/core/components/input-date/input-date.element.ts
- src/packages/property-editors/date-picker/manifests.ts
- src/packages/property-editors/date-picker/property-editor-ui-date-picker.element.ts
This PR adds `readonly` mode to the Date Picker Property Editor UI
> Feature: Readonly mode for Date Picker Property Editor UI

- src/packages/core/components/input-slider/input-slider.element.ts
- src/packages/property-editors/slider/manifests.ts
- src/packages/property-editors/slider/property-editor-ui-slider.element.ts
This PR adds `readonly` mode to the Slider Property Editor UI
> Feature: Readonly mode for Slider Property Editor UI

- src/packages/core/components/input-dropdown/input-dropdown-list.element.ts
- src/packages/property-editors/dropdown/manifests.ts
- src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
This PR adds `readonly` mode to the Dropdown Property Editor UI
> Feature: Readonly mode for Dropdown Property Editor UI

- src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
- src/packages/property-editors/radio-button-list/manifests.ts
- src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
This PR adds `readonly` mode to the Radio Button List Property Editor UI
> Feature: Readonly mode for Radio Button List Property Editor UI

- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
- src/packages/tiny-mce/property-editors/tiny-mce/manifests.ts
- src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
This PR adds `readonly` mode to the Tiny MCE Property Editor UI
> Feature: Readonly mode for Tiny MCE Property Editor UI

- src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
This PR fixes the document name input so it is set to read-only when the user doesn't have access to edit a language.
> Bugfix: Set document name to read only when user does not have access to edit a language

- src/packages/dictionary/workspace/views/workspace-view-dictionary-editor.element.ts
This PR implements language permissions in the dictionary so it is only possible to update the language the current user has access to.
> Feature: Support Language Permissions in Dictionary Section

- src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
- src/packages/media/media/property-editors/media-picker/manifests.ts
- src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
- src/packages/property-editors/toggle/manifests.ts
This PR adds `readonly` mode to the Rich Media Picker Property Editor UI
> Feature: Readonly mode for Rich Media Picker Property Editor UI

- examples/ufm-custom-component/README.md
- examples/ufm-custom-component/custom-ufm-component.ts
- examples/ufm-custom-component/index.ts
- src/packages/ufm/index.ts
Raised on the docs repo, https://github.com/umbraco/UmbracoDocs/issues/6374, the `UmbUfmComponentBase` class wasn't being exported.
This PR...
- Exports `UmbUfmComponentBase` type
- Adds custom UFM component example
> Bugfix: Exports `UmbUfmComponentBase` type

- src/packages/members/member/components/input-member/input-member.element.ts
- src/packages/members/member/property-editor/member-picker/manifests.ts
- src/packages/members/member/property-editor/member-picker/property-editor-ui-member-picker.element.ts
This PR adds `readonly` mode to the Member Picker Property Editor UI
> Feature: Readonly mode for Member Picker Property Editor UI

- src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts
- src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
- src/packages/multi-url-picker/property-editor/manifests.ts
- src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.element.ts
This PR adds `readonly` mode to the Multi URL Picker Property Editor UI
> Feature: Readonly mode for Multi URL Picker Property Editor UI

- src/packages/block/block-grid/context/block-grid-entries.context.ts
- src/packages/block/block-rte/context/block-rte-entries.context.ts
- src/packages/block/block-rte/context/block-rte-manager.context.ts
- src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
- src/packages/block/block/context/block-manager.context.ts
- src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
- src/packages/core/property/property/property.element.ts
Fixes so Blocks are created via a modal Workspace, unless its Block List Editor in Inline Editing Mode.
There was a few missing parts of the current source that this PR corrects.
This now also considers if a Block has any content properties, if not it will not be created via the Workspace, instead directly.
Meaning we do not open Blocks in a Workspace if they dont have any Content Properties.
> Fix: Determine when to create Blocks directly or via Block Workspace

- src/packages/block/block-grid/context/block-grid-entries.context.ts
- src/packages/block/block-grid/workspace/block-grid-type-workspace.modal-token.ts
- src/packages/block/block/context/block-manager.context.ts
- src/packages/core/validation/mixins/form-control.mixin.ts
- src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
Fixes Group rules + Combination of rules
So now you can have a single element rule and a group rule (specified permissions for Areas) Where those two now play well together.
For this PR I tested with a requirement of the headline to be present at least once, and maximum once.
And the group of Elements should be present twice.
Every things is good in this case:
A few screenshots of bad cases:
You may do another test to ensure the system works intuitively.
Notice, when picking a group, its only the Blocks of the group that is set for Allow in Areas that is considered.
But for Element Rules that settings does not matter.
So this PR also changes to Allow In Areas are ticked pr. default. which is similar to v.13.
> Fix: Block Grid Editor — Specified Permissions Group Rules

- src/packages/dictionary/workspace/views/workspace-view-dictionary-editor.element.ts
Used `zero-width space` character instead of `unnamed` instead for dictionary item name fallback in `dictionaryItem_description`.
As noted in umbraco/Umbraco-CMS#16385, using `unnamed` as a fallback for empty dictionary item names can be confusing, potentially being thought as an existing item. Displaying a quoted empty string is clearer and directly reflects the empty value.
In the code, placeholders in the format `%index%` and `{index}` are replaced with values from `args`. If an empty string is passed, it is treated as falsy, so placeholders are not replaced:
```javascript
if (typeof term === 'string') {
if (args.length > 0) {
term = term.replace(/(%(\d+)%|\{(\d+)\})/g, (match, _p1, p2, p3): string => {
const index = p2 || p3;
return String(args[index] || match);
});
}
}
```
Thus I …
> Fix: Update dictionary's name fallback value when using it as a placeholder in `dictionaryItem_description` localization term

- src/packages/block/block-rte/tiny-mce-plugin/tiny-mce-block-picker.plugin.ts
- src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
Adds the `UmbBlockRteEntriesContext` to the tinymce property editor UI so that the blocks plugin can calculate the path to the block picker modal. This is modeled after the block-list itself and is the missing piece to make the block picker work again following a regression between 14.1 and 14.2.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17003
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16949
1. Add an RTE to a page
2. Add blocks to the RTE and enable the "Insert blocks" button
3. Verify that the block picker opens when you click the button
4. Verify that a block is inserted into the editor (click the view source button) of the rich text editor
> Bugfix: Blocks in RTE redirects to the frontpage

- src/libs/context-api/debug/context-data.function.ts
Fixes a simple nullcheck when the code determines a certain item in an array is an object but the value of the reference is null
I was testing out the debugElement inside a user profile app and noticed it wasn't showing the console error directed me to the line and showed the missing truthy check.
The routerContext router value was null and thus threw and error when the system tried to figure out if type was an observable
> Fix null ref exception in Context Data

- src/packages/block/block/conditions/block-entry-show-content-edit.condition.ts
- src/packages/block/block/conditions/block-workspace-has-settings.condition.ts
- src/packages/core/extension-registry/conditions/index.ts
- src/packages/core/extension-registry/conditions/types.ts
A part of moving Block Conditions was not cleaned up properly
> Feature: clean up block conditions

- src/packages/core/extension-registry/models/index.ts
- src/packages/core/extension-registry/models/tiptap-extension.model.ts
- src/packages/rte/manifests.ts
- src/packages/rte/tiptap/components/input-tiptap/index.ts
- src/packages/rte/tiptap/components/input-tiptap/input-tiptap.element.ts
- src/packages/rte/tiptap/components/input-tiptap/tiptap-extension.ts
- src/packages/rte/tiptap/components/input-tiptap/tiptap-fixed-menu.element.ts
- src/packages/rte/tiptap/extensions/manifests.ts
- src/packages/rte/tiptap/extensions/tiptap-mediapicker.extension.ts
- src/packages/rte/tiptap/index.ts
- src/packages/rte/tiptap/manifests.ts
- src/packages/rte/tiptap/property-editors/tiptap/manifests.ts
- Introduces a new `tiptapExtension` extension type
- Extension has 2 parts, `getExtensions()` to return [a Tiptap extension instance](https://tiptap.dev/docs/editor/extensions/custom-extensions); and `getToolbarButtons()`.
- Adds a placeholder extension for the Media Picker toolbar button/feature
- Refactored the `umb-input-tiptap` and `umb-tiptap-fixed-menu` components to use the new extension type
- Load up a Tiptap RTE and notice that the Media Picker button is in the toolbar (and clicking it will open the media modal)
> Adds `tiptapExtension` extension type

- src/packages/core/components/multiple-text-string-input/input-multiple-text-string-item.element.ts
- src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
MultipleTextString property editor now adds a new line when pressing enter (similar to how it was in v13)
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16162
> MultipleTextString: Add new line on pressing enter

- src/packages/core/components/multiple-color-picker-input/multiple-color-picker-input.element.ts
- src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
Fixed an issue where the the user would lose tab focus when changing color values
Add new row when pressing enter if a label is filled out.
Automatically opens the color picker window when pressing enter in the color input field
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16158
> MultipleColorPicker: Tab behaviour and new line on enter

- src/packages/rte/tiptap/components/input-tiptap/input-tiptap.element.ts
- src/packages/rte/tiptap/components/input-tiptap/tiptap-fixed-menu.element.ts
- src/packages/rte/tiptap/components/input-tiptap/tiptap-hover-menu.element.ts
Adds readonly mode to the Tiptap input element. It changes the background color and disables all controls and sets `editable` to false on the editor.
> feat: adds readonly mode to the tiptap input element

- src/external/tiptap/extensions/tiptap-umb-image.extension.ts
- src/external/tiptap/index.ts
- src/mocks/data/document/document.data.ts
- src/packages/rte/tiptap/components/input-tiptap/input-tiptap.element.ts
- src/packages/rte/tiptap/extensions/manifests.ts
- src/packages/rte/tiptap/extensions/tiptap-image.extension.ts
Adds all needed attributes to images by extending the Image extension.
Launch the Vite dev server with mocked data and check that [the mocked image](http://localhost:5173/section/content/workspace/document/edit/all-rtes-id/invariant) now has width, height, and loading attributes:
> Feature: Add images to Tiptap

- src/packages/rte/manifests.ts
- src/packages/rte/tiptap/components/input-tiptap/input-tiptap.element.ts
- src/packages/rte/tiptap/components/input-tiptap/tiptap-fixed-menu.element.ts
- src/packages/rte/tiptap/extensions/manifests.ts
- src/packages/rte/tiptap/extensions/tiptap-extension.ts
- src/packages/rte/tiptap/extensions/tiptap-image.extension.ts
- src/packages/rte/tiptap/extensions/tiptap-mediapicker.extension.ts
- src/packages/rte/tiptap/extensions/tiptap-toolbar-button.element.ts
- src/packages/rte/tiptap/extensions/types.ts
- src/packages/rte/tiptap/manifests.ts
- src/packages/rte/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
- Adds support for custom elements in the toolbar
- Adds a `button` kind for `tiptapExtension` for default toolbar buttons
- Amends how the toolbar extensions are loaded in/rendered
If the Media Picker button is rendered on the toolbar, then it's working.
_**Note**: I've noticed a re-rendering when editing content, which is causing the toolbar to glitch... I expect that we'll revisit that particular code when we do the data-type configuration plumbing._
> Feature: Tiptap toolbar elements

- index.html
- src/mocks/data/document-type/document-type.data.ts
- src/packages/block/block-custom-view/block-editor-custom-view.extension.ts
- src/packages/block/block-grid/context/block-grid-manager.context.ts
- src/packages/block/block-list/context/block-list-manager.context.ts
- src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
- src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.element.ts
- src/packages/block/block-rte/context/block-rte-entries.context.ts
- src/packages/block/block-rte/context/block-rte-manager.context.ts
- src/packages/block/block-rte/manifests.ts
- src/packages/block/block-rte/tiny-mce-plugin/tiny-mce-block-picker.plugin.ts
- src/packages/block/block-rte/tiptap-extension/block-picker.extension.ts
- src/packages/block/block-rte/tiptap-extension/manifests.ts
- src/packages/block/block-rte/types.ts
- src/packages/block/block/context/block-manager.context.ts
- src/packages/block/custom-view/manifest.ts
- src/packages/rte/tiptap/components/input-tiptap/input-tiptap.element.ts
- src/packages/rte/tiptap/components/toolbar/tiptap-toolbar-button.element.ts
- src/packages/rte/tiptap/extensions/core/image.extension.ts
- src/packages/rte/tiptap/extensions/types.ts
- src/packages/rte/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
- src/packages/rte/vite.config.ts
- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
- src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
- Remove the tight coupling between TinyMCE and the Block RTE context(s) changing from a push to a pull configuration to allow each editor (TinyMCE and Tiptap) to handle how they would like to insert blocks
- Add a new extension (block picker) to Tiptap that opens the blockpicker modal and adds commands to insert blocks
- Remove certain attributes marked as deprecated in V14 that were no longer used (originData)
- (Temporarily?) disable the 'delete' button on blocks, since you should remove any objects in a rich text editor by pressing the actual delete button on your keyboard (and I couldn't get Tiptap to play well with this function in due time)
- Finally fix the issue where TinyMCE could not load on the dev server due to a module not being loaded
Create element types, add them to the …
> Feature: Tiptap blockpicker

- src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
When trying to create a new document type under content (at the root), and there is no allowed document types available, show the correct message and remove the edit button.
The button has been removed as there are multiple options when creating a document type (it was not there in v13 either)
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17107
> Bugfix: No document type allowed at root message

- src/packages/block/block/workspace/views/edit/block-workspace-view-edit-properties.element.ts
- src/packages/core/content-type/components/property-type-based-property/property-type-based-property.element.ts
- src/packages/core/property/index.ts
- src/packages/core/property/types/index.ts
- src/packages/core/property/types/unsupported-properties.type.ts
- src/packages/core/property/unsupported-property/index.ts
- src/packages/core/property/unsupported-property/unsupported-property.element.ts
- src/packages/core/property/unsupported-property/utils.ts
A fresh PR for the adding logic to unsupported properties based on the comments from the previous PR: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2102
Added `UMB_UNSUPPORTED_EDITOR_SCHEMA_ALIASES` which contains all unsupported schemas.
Added element `umb-unsupported-property` to be used for any property that are unsupported.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16664
> Feature: Unsupported properties

- src/packages/rte/tiptap/components/input-tiptap/input-tiptap.element.ts
- src/packages/rte/tiptap/components/input-tiptap/tiptap-fixed-menu.element.ts
Fixes the toolbar overlapping elements outside the editor by giving the editor a stacking context (z-index: 0)
> make z-index relative to the editor

- src/packages/core/components/code-block/code-block.element.ts
- src/packages/sysinfo/components/sysinfo.element.ts
Revert to `white-space: pre` and fix the underlying issue with sysinfo.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17152
> Bugfix: Code Block is removing spaces

- src/packages/core/extension-registry/models/index.ts
- src/packages/property-editors/content-picker/dynamic-root/components/input-content-picker-document-root.element.ts
- src/packages/property-editors/content-picker/dynamic-root/dynamic-root.extension.ts
- src/packages/property-editors/content-picker/dynamic-root/index.ts
- src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
- src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
- src/packages/property-editors/content-picker/dynamic-root/modals/index.ts
Types moved from `@umbraco-cms/backoffice/extension-registry` to `@umbraco-cms/backoffice/content-picker`:
- `ManifestDynamicRootOrigin `
- `ManifestDynamicRootQueryStep `
> Extension Manifest Map: Dynamic Root

- src/packages/rte/tiptap/components/input-tiptap/input-tiptap.element.ts
- src/packages/rte/tiptap/property-editors/tiptap/manifests.ts
Follows similar pattern as our TinyMCE configuration where the height/width of the editor can be defined in a combined field for Dimensions.
> Tiptap: Combined Max Height/Width options into Dimensions

- src/packages/rte/tiptap/extensions/umb/link.extension.ts
- src/packages/rte/tiptap/property-editors/tiptap/manifests.ts
Configured the overlay size option for the Tiptap Link extension (using the URL Picker modal).
> Tiptap: Configured overlay size for Link picker

- src/packages/rte/tiptap/components/input-tiptap/input-tiptap.element.ts
I'd noticed that the CSS rules for the Tiptap Table extension was being nested in another rule, (probably from a bad merge conflict). This PR fixes this.
> Tiptap: Fixes Table CSS rules

- src/packages/rte/tiny-mce/property-editors/tiny-mce/manifests.ts
- src/packages/rte/tiny-mce/property-editors/toolbar/property-editor-ui-tiny-mce-toolbar-configuration.element.ts
The layout of the TinyMCE toolbar configuration was a bit squashed. This PR amends the layout to space it out.
**Before**
**After**
> Bugfix: TinyMCE toolbar config layout

- src/packages/rte/tiptap/components/input-tiptap/tiptap-fixed-menu.element.ts
If a Tiptap toolbar extension has been renamed or removed, the data-type configuration would still contain the alias reference, so this PR adds a checks to ensure the component exists.
> Bugfix: Tiptap toolbar, ensure component exists

- src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
- src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
Renamed "umb-tiptap-fixed-menu" to "umb-tiptap-toolbar"
Since we refer to this as "toolbar" throughout the Tiptap feature.
> Tiptap: Renamed "umb-tiptap-fixed-menu" to "umb-tiptap-toolbar"

- src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-toolbar-configuration.element.ts
For the Tiptap data-type toolbar configuration, adds a `isValidTiptapToolbarValue()` method to ensure that the toolbar value is in the correct structure, e.g. `Array<Array<Array<string>>>` (`UmbTiptapToolbarValue`).
This is required for when a data-type swaps its property-editor, e.g. from TinyMCE to Tiptap, and the value from the previous "toolbar" configuration is briefly passed into the new "toolbar" property-editor. If the value's structure doesn't align, then an error would be thrown. This validation attempts to prevent this scenario.
Take an existing data-type configuration that has a "toolbar" field, e.g. TinyMCE, then change the Property Editor to "Rich Text Editor [Tiptap]", check there are no JavaScript errors in the browser's devtools.
> Tiptap: Validates toolbar configuration value

- src/packages/dictionary/collection/action/manifests.ts
- src/packages/translation/menu/manifests.ts
* Fixes the create dictionary collection action path
* Changes the Section Sidebar Menu title to dictionary until we have a dictionary menu item.
> V15: Hotfix: Create dictionary collection action wrong path

- src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
This fix adds an `await` to the manifests initializer so we are sure the manifests have been loaded before trying to calculate which preview element to show.
It also optimizes the element slightly to get rid of the `_src` state and to rely more on the `value` property.
> V15 Hotfix: Media previews are not shown for anything other than images

- src/packages/core/utils/math/calculate-extrapolated-value.test.ts
- src/packages/core/utils/math/clamp.test.ts
- src/packages/core/utils/math/distance.test.ts
- src/packages/core/utils/math/get-accumulated-value-of-index.test.ts
- src/packages/core/utils/math/get-interpolated-index-of-position-in-weight-map.test.ts
- src/packages/core/utils/math/inverse-lerp.test.ts
- src/packages/core/utils/math/is-within-rect.test.ts
- src/packages/core/utils/math/lerp.test.ts
> Chore: Add unit tests for math functions

- src/packages/core/utils/state-manager/state.manager.test.ts
Adds tests for the State Manager
> Chore: Add unit tests for the state manager

- .vscode/settings.json
- src/packages/documents/documents/modals/publish-modal/document-publish-modal.element.ts
- src/packages/documents/documents/modals/publish-with-descendants-modal/document-publish-with-descendants-modal.element.ts
- src/packages/documents/documents/modals/schedule-modal/document-schedule-modal.element.ts
- src/packages/documents/documents/modals/shared/document-variant-language-picker.element.ts
- src/packages/documents/documents/modals/unpublish-modal/document-unpublish-modal.element.ts
- src/packages/documents/documents/modals/utils.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
Makes it a requirement that mandatory languages follow each other in publish/publish-with-descendants/unpublished dialogs.
To ensure the user select all mandatory languages when publishing or opposite if unpublishing.
> Feature: Handle mandatory languages in publish'ish dialogs

- src/packages/media/media/components/input-upload-field/preview/input-upload-field-file.element.ts
Fixed a bug where the file extension type would not be shown on custom files (forexample `.udt` files).
Added localization
Example (not fixed):
Example (fixed):
> Bugfix: Uploadfield file preview shows file extension

- src/packages/media/media/collection/media-collection.element.ts
- src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
- src/packages/media/media/dropzone/dropzone.element.ts
- src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Original text from [PR #2258](https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2258)
From my testing it is not possible to make a boolean property `false` if it's by default `true` therefore the default for `multiple` has to be `false` which also makes more sense when looking at the usage: `<umb-dropzone multiple></umb-dropzone>`
> Bugfix: Allow/disallow multiple files for dropzone

- src/packages/property-editors/collection/manifests.ts
This PR partially fixes umbraco/Umbraco-CMS#17230 with an update to the manifest that provides the labels and descriptions for the properties with the outdated verbiage.  To fully address the original issue, I think we need to do a few more things:
- Update the [`ListView.spec.ts`](https://github.com/umbraco/Umbraco-CMS/blob/e4dbf4ce9ff9ca70ed7c82c0c735a4d576aad692/tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ListView.spec.ts) acceptance test that lives outside this submodule.  I'll make that update and submit it as a separate PR to its respective repo.
- Update the Collection/List View docs article that lives here: https://github.com/umbraco/UmbracoDocs/blob/main/14/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/listview.md
This …
> Update Collection view's instruction text to match current Backoffice terminology

- src/packages/core/components/input-color/input-color.element.ts
fix: only set the ?readonly attribute on the swatches element since it handles setting it on the colors afterwards based on this comment: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2451#discussion_r1798968698
CC @bjarnef - is this reasonable?
> Bugfix: Set ?readonly only on color swatches, and not on the individual swatch

- src/packages/documents/document-redirect-management/dashboard-redirect-management.element.ts
Icon alignment on links in the redirect seems off. I fixed it by making them inline-flex, and then aligning the content.
Before:
After:
> Fixes icon alignment in links in redirect dashboard

- src/packages/settings/welcome/settings-welcome-dashboard.element.ts
Noticed a couple of buttons were sticking together on small screens, so I wrapped them in flex with a gap between, to make sure they were nicely spaced.
See screenshots:
Before:
After:
> Adds gap between grouped buttons in settings welcome dashboard

- src/packages/multi-url-picker/tiny-mce-plugin/tiny-mce-multi-url-picker.plugin.ts
- src/packages/tiny-mce/plugins/tiny-mce-code-editor.plugin.ts
When adding/editing a link in TinyMCE that has an anchor or querystring, but no URL part, the link markup would include the current backoffice path, along with an `undefined` suffix.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17009
Add/edit a link without entering a URL, but adding either an anchor hash or querystring value. The link's `href` should **not contain** either `undefined` or the current backoffice path.
> Bugfix: TinyMCE anchor links without base URL

- src/packages/block/block/context/block-manager.context.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17274
> Hotfix: correct config field alias to 'useLiveEditing'

- src/packages/core/temporary-file/temporary-file-manager.class.ts
- src/packages/tiptap/extensions/core/media-upload.extension.ts
Add a listener for "paste" events and upload any files that might be included in the clipboard.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17258
Take a screenshot or copy an image into the clipboard, then paste it (CTRL+V) into a Tiptap instance with the media upload extension enabled.
> Tiptap: allow images to be uploaded from the clipboard

- src/packages/ufm/components/ufm-render/ufm-render.element.ts
I noticed that property labels now use umb-ufm-render, which (because of the nature of markdown I guess), turns simple text into paragraphs. This makes it have a top and bottom margin from the user agent stylesheet.
I added some css to remove the top margin from the first element and bottom margin from the last to combat this.
Before:
After:
> Removes unnecessary margin in ufm-render-element

- src/packages/documents/documents/workspace/document-workspace.context.ts
Make the preview url construction use server paths
> use server paths for preview url construction

- src/packages/core/collection/components/collection-action-bundle.element.ts
- src/packages/core/collection/components/collection-filter-field.element.ts
- src/packages/core/collection/components/collection-view-bundle.element.ts
- src/packages/core/collection/components/index.ts
- src/packages/dictionary/collection/dictionary-collection.element.ts
- src/packages/documents/documents/collection/document-collection-toolbar.element.ts
- src/packages/documents/documents/collection/document-collection.element.ts
- src/packages/extension-insights/collection/extension-collection.element.ts
- src/packages/media/media/collection/media-collection-toolbar.element.ts
- src/packages/media/media/collection/media-collection.element.ts
- src/packages/members/member/collection/member-collection-header.element.ts
- src/packages/members/member/collection/member-collection.element.ts
- src/packages/relations/relation-types/collection/relation-type-collection.element.ts
- src/packages/user/user-group/collection/user-group-collection-header.element.ts
- src/packages/user/user-group/collection/user-group-collection.element.ts
- src/packages/user/user/collection/user-collection-header.element.ts
- src/packages/user/user/collection/user-collection.element.ts
Since reviewing the Dictionary Collection toolbar filter (PR #2415) last week, I looked at the other Collection toolbars to see if we could de-duplicate the filter input code, to make a reusable component.
This PR introduces a `<umb-collection-filter-field>` component.
Try out the Collection toolbar filter field on the following areas, to make sure that it still works as expected.
- Dictionary
- Documents
- Extension Insights
- Media
- Members
- Users
- User Groups
> Feature: Collection Toolbar Filter Field

- src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
We are currently experiencing an issue where a workspace modal closes before the discard changes dialog is resolved. As a temporary solution, I have removed the discard changes functionality when a workspace is open in a modal until we have a permanent fix.
> Workaround: Ignore discard changes when in a workspace modal

- src/packages/core/menu/menu-variant-tree-structure-workspace-context-base.ts
We currently get a js error in the console when creating a document in the root. This is caused because the unique is `null` and we throw an error when falsy. This fix changes the code to only check for `undefined`.
* Create a document in the root. You will see the error in the console.
* After the fix is applied the error is gone.
> Bugfix: Allow breadcrumb for variant root items

- src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
When opening the infinite editing in several layer, e.g. when opening the icon picker as third layer in infinite editing the properties are shown above backdrop.
Removing this solves this. I don't see a specific need for this?
> Remove z-index from header in content type design editor property

- src/packages/tags/components/tags-input/tags-input.element.ts
This PR ensures the tags editor matchlist is on top on following markdown toolbar and fixes https://github.com/umbraco/Umbraco-CMS/issues/17340
The matchlist could probably make sense to use a component with input + `<datalist>` (as @leekelleher suggested in https://github.com/umbraco/Umbraco.UI/discussions/879) altough date/time input doesn't work inside datalist in Firefox.
https://caniuse.com/?search=datalist
> Tags matchlist on top of following markdown toolbar

- src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
This PR hides the template input on a document info view when there are no configured allowed templates. We do this to prevent an experience where the editor opens an empty template picker or a template picker with only disabled items in it. The same UX will be useful when the CMS is fully headless and there are no templates.
Here is a screenshot of something that is not there  😄
> Bugfix: Hide template input when there are no allowed templates

- src/packages/documents/documents/entity-actions/unpublish.action.ts
- src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17345
> Hotfix: Publish with decendants structure reload

- src/packages/user/user/repository/disable/disable-user.repository.ts
- src/packages/user/user/repository/enable/enable-user.repository.ts
We currently display an incorrect notification when a user is enabled. The PR addresses this issue and also uses localized text when enabling and disabling.
> Hotfix: Correct user enable notification

- src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts
Currently I don't think it is clear when a content type group is sorted as when `drag-placeholder` attribute is added the entire element is invisible.
Sorting is initially enabled (which is shouldn't be here) because the group has `draggable="true` - I think I created an issue for that in *Umbraco.CMS.Backoffice* repository, but the issue tracker were later disabled (and issues reported in *CMS* repository instead), so I can't access my own initially reported issues 😅
I think it is best practice to have a drop placeholder indication where the sorted item is placed when releasing dropping item (normally using mouse, but could be touch as well).
> Content type group sorting placeholder

- src/packages/core/repository/detail/detail-repository-base.ts
I'd noticed on a Media item workspace (on the Info/General panel) that the "Last edited" (updated date) property wasn't updating. Drilling down, I found that the base class `UmbDetailRepositoryBase.save()` method was returning the original model value, not the updated model (from the backend/server). Meaning properties that are updated by the server weren't being reflected on the client side.
Go to an existing Media item, go to the Info workspace view, press the Save button, notice that the "Last edited" date has updated (without refresh).
> Bugfix: Detail repository base `save()` returns updated model

- src/packages/core/icon-registry/icon-dictionary.json
- src/packages/core/icon-registry/icons.ts
- src/packages/core/icon-registry/icons/icon-clear-formatting.ts
- src/packages/tiptap/extensions/manifests.ts
- src/packages/tiptap/extensions/toolbar/clear-formatting.extension.ts
Adds a **Clear Formatting** feature for the Tiptap RTE toolbar.
Introduces the Lucide icon "[remove-formatting](https://lucide.dev/icons/remove-formatting)" to the backoffice.
Enable the "Clear Formatting" action on a Tiptap toolbar configuration. Go to the Tiptap RTE, highlight text that has formatting, e.g. bold, italic, etc. Press the "Clear Formatting" button and notice that the text formatting has been removed.
> Feature: Tiptap "Clear Formatting" toolbar action

- src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
Experimenting with a background colour (plus box shadow) on the Tiptap RTE toolbar, to give it more definition and depth.
**Before**
**After**
> Cosmetic: Tiptap toolbar, background color + box shadow

- src/packages/core/components/history/history-item.element.ts
- src/packages/documents/documents/repository/index.ts
- src/packages/documents/documents/repository/manifests.ts
- src/packages/documents/documents/repository/url/constants.ts
- src/packages/documents/documents/repository/url/document-url.repository.ts
- src/packages/documents/documents/repository/url/document-url.server.data-source.ts
- src/packages/documents/documents/repository/url/document-url.store.context-token.ts
- src/packages/documents/documents/repository/url/document-url.store.ts
- src/packages/documents/documents/repository/url/index.ts
- src/packages/documents/documents/repository/url/manifests.ts
- src/packages/documents/documents/repository/url/types.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info-reference.element.ts
- src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17183.
Half feature, half bug fix. When saving/publishing a document, the components on the Info workspace view were not automatically updating. Using the Request Reload Structure event (from the workspace context), the Info components are refreshed on save/publish.
For the Links component, this makes use of a new dedicated Document URL Repository, (as opposed to observing the workspace context's `.urls` property).
Go to an existing document, go to the Info workspace view, rename the document (e.g. append a number), press Publish, notice that the URL is updated in the "Links" component and that the "History" component has the latest Save/Publish audit logs.
> Feature: Document Workspace Info reload components

- src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
- src/packages/markdown-editor/monaco-markdown-editor-action.extension.ts
- src/packages/multi-url-picker/monaco-markdown-editor-action/manifests.ts
Following on from #2495, updated the Markdown Editor toolbar to visually align with the Tiptap RTE toolbar, including using the same icons for heading, bold, italic, et al.
**Before**
**After**
This does introduce a change (feature), as the button icon for any `monacoMarkdownEditorAction` extensions was hardcoded to "icon-link" (for the URL Picker feature), so `MetaMonacoMarkdownEditorAction` has been updated to have an optional `label` and `icon`.
This is mostly a cosmetic change, but with the addition of the label/icon properties to the extension manifest, testing should be to make sure that the toolbar buttons all still function as expected.
> Feature: Markdown Editor toolbar styling

- src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts
Displays the state/messaging of a document's links, (including variants).
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17388.
Test out with a variety of document states: new document (unsaved), draft, published, unpublished, and then a combination of states for document variants, e.g. published in the default culture, but variant culture is not created.
> Feature: Document Workspace Info Link State

- src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16985
When running the backoffice from the CMS code (non-Vite), the thumbnail image path/URL was incorrect; it included the backoffice path (e.g. `/umbraco/`) and stripped a trailing slash. Which led to a 404 error when attempting to load the image.
This PR removes the backoffice path from the base URL and makes use of the [`URL()` object](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) to join the paths.
Test that a Block Type card still shows the thumbnail image when running the backoffice via Vite; and that the it works when running the backoffice from the CMS, (e.g. `dotnet run` and `npm run build:for:cms`).
> Hotfix: Block Type card thunbnail image path/URL

- src/packages/webhook/workspace/webhook/views/webhook-details-workspace-view.element.ts
This fixes [16388](https://github.com/umbraco/Umbraco-CMS/issues/16388)
Replicated on 15.1.0-rc1.preview.16.
The URL is a mandatory field for a webhook, so I've set it as required. Additionally I have also set it to autofocus on load.
https://github.com/user-attachments/assets/409b157c-505e-487f-8662-f65c06ae8c1e
> Feature: Set the URL field as required and focus on it

- src/packages/ufm/components/content-name/content-name.component.ts
- src/packages/ufm/components/manifests.ts
- src/packages/ufm/contexts/ufm.context.ts
- src/packages/ufm/plugins/marked-ufm.plugin.ts
- src/packages/ufm/plugins/marked-ufm.test.ts
- src/packages/ufm/ufm-component.extension.ts
Following internal review and feedback, the single character marker prefixes can be confusing. For established syntax like outputting a raw value or using a localization key, the respected marker prefixes `=` and `#` are intuitive, however with the new UFM Content Name component, the chose marker prefix is `~`, which is not established and counter intuitive.
To aid discovery, the use of a UFM component alias will be encouraged, e.g. `{umbContentName: propertyAlias}`
The `~` marker prefix will still work and be supported in v15, but set to be deprecated in a future release, the `umbContentName` alias prefix will be used going forwards.
First, test that the existing UFM syntaxes still work as expected. Then test that the "umbContentName" alias prefix works in various places, e.g. Block …
> Hotfix: UFM alias prefixes

- src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
I noticed this when I was trying to replicate [16207](https://github.com/umbraco/Umbraco-CMS/issues/16207)
Basically this allows for the document create options from the modal to be opened when the space or enter is pressed.
Open the Content tab
Using the keyboard, tab to the + icon to create a new document.
Press enter/space to start the action.
The 'document creation options' modal will open.
Tab to the document type you'd like to create & press enter/space.
Before the change:
https://github.com/user-attachments/assets/32276da1-4d75-40f2-8e5d-e8d76ee892bf
After the change:
https://github.com/user-attachments/assets/651c7b3b-ca80-4dcf-86a5-dadcc994b85a
> Allow for the document create options to be opened on space/enter clicked

- src/packages/block/block-type/workspace/block-type-workspace.context.ts
- src/packages/block/block/workspace/block-workspace.context.ts
- src/packages/core/property-type/workspace/property-type-workspace.context.ts
- src/packages/data-type/workspace/data-type-workspace.context.ts
- src/packages/dictionary/workspace/dictionary-workspace.context.ts
- src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
- src/packages/documents/document-types/workspace/document-type-workspace.context.ts
- src/packages/documents/documents/workspace/document-workspace.context.ts
- src/packages/language/workspace/language/language-workspace.context.ts
- src/packages/media/media-types/workspace/media-type-workspace.context.ts
- src/packages/media/media/workspace/media-workspace.context.ts
- src/packages/members/member-group/workspace/member-group/member-group-workspace.context.ts
- src/packages/members/member-type/workspace/member-type-workspace.context.ts
- src/packages/members/member/workspace/member/member-workspace.context.ts
- src/packages/templating/scripts/workspace/script-workspace.context.ts
- src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts
- src/packages/templating/templates/workspace/template-workspace.context.ts
- src/packages/user/user-group/workspace/user-group/user-group-workspace.context.ts
- src/packages/webhook/workspace/webhook/webhook-workspace.context.ts
This PR addresses an issue encountered when changing from editing an existing entity to creating a new one of the same type. In some workspaces, when users attempted to create a new entity, the `isNew` state, which should be set to true upon creation, was mistakenly retained as false from the editing state at first. This resulted in a redirect from the create URL back to the edit URL.
To fix this, this PR ensures that the redirect controller is initialized after the scaffolding logic is complete. Since the scaffolding/create method is already async, it makes sense to await this so we first start observing the "isNew" state afterward. This way, we ensure that the state we observe is correct.
> Hotfix: Ensure scaffolding is done before initializing the redirect controller

- src/libs/context-api/consume/context-consumer.test.ts
- src/libs/context-api/consume/context-request.event.ts
- src/libs/context-api/provide/context-boundary.controller.ts
- src/libs/context-api/provide/context-boundary.ts
- src/libs/context-api/provide/context-provider.ts
- src/libs/context-api/provide/index.ts
- src/packages/core/modal/component/modal.element.ts
- src/packages/core/router/modal-registration/modal-route-registration.controller.ts
- src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.defaults.ts
Prevent context consumption of route-context from a modal that is not routable. Making routableModals never construct a path and thereby not valid.
This is breaking in the sense if someone wanted to retrieve the Route Context from a not-routable-modal. But this is not what we want pr. default.
If you still like to do so you have to consume the context with `.passContextAliasMatches()` enabled on your consumption.
fixes https://github.com/umbraco/Umbraco-CMS/issues/17434
> hotfix: 17434 (prevent routable modals inside not routable modals)

- src/packages/block/block-grid/components/block-grid-areas-container/block-grid-areas-container.element.ts
- src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
- src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
- src/packages/block/block-grid/components/block-scale-handler/block-scale-handler.element.ts
What it says, not breaking, no change, just imports
> Feature: Fix imports for circular deps

- src/packages/documents/documents/entity-actions/public-access/repository/public-access.repository.ts
Spelling correction of "acccess" to "access".
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17444
> Bugfix: Corrects "Public access" notification typo

- src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Disables the Link Picker modal's submit action/button if URL or querystring are not set.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17411
Open the Link Picker modal (from either the Multi-URL Picker or a Rich Text editor), if the URL or querystring is not set, then the Submit button will be disabled.
> Bugfix: Disables Link Picker modal submit button

- src/packages/tiptap/extensions/toolbar/link.extension.ts
In the Tiptap Link Picker extension, when adding a link with an anchor/querystring and empty URL (for in-page navigation), the `href` was being stringified with the URL's `null` value.
In the Tiptap editor, open the Link Picker modal, set an anchor/querystring value without setting the URL field, press Submit.
Select the link you've just created, edit in the Link Picker modal, notice that the URL value is empty and **not** set to a stringified `null` value.
> Bugfix: Tiptap Link Picker, fixes anchor with an empty URL

- src/packages/block/block-grid/components/block-grid-areas-container/block-grid-areas-container.element.ts
- src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
- src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts
Makes the create button in a grid hide properly.
> Feature: Block Grid — make area create button hide on drag

- src/packages/block/block-grid/components/block-grid-area/block-grid-area.element.ts
- src/packages/block/block-grid/components/block-grid-area/index.ts
- src/packages/block/block-grid/components/block-grid-areas-container/block-grid-areas-container.element.ts
- src/packages/block/block-grid/components/block-grid-block-inline/block-grid-block-inline.element.ts
- src/packages/block/block-grid/components/block-grid-block/block-grid-block.element.ts
A component for rendering a single area
> Feature: block area component
