umbraco/Umbraco.CMS.Backoffice

src/installer/installer-user.element.ts

Just adding the missing labels to fix the accessibility warning

adding labels for accessibility

---

src/backoffice/dashboards/published-status/dashboard-published-status.element.ts
src/backoffice/sections/shared/section-dashboards.element.ts

update button colors on dashboard & add a note about the fix that is needed in a comment

update button colors

---

.gitignore
.storybook/preview.js
package-lock.json
package.json
src/backoffice/editors/shared/editor-entity-layout/editor-entity-layout.element.ts
src/backoffice/editors/shared/editor-entity-layout/editor-entity-layout.stories.ts

This PR adds the [Web Component Analyzer](https://www.npmjs.com/package/web-component-analyzer) package to the project and loads in the custom-elements.json file to render docs in storybook.

Feature/Web Component Analyzer

---

.gitignore
.vscode/lit.code-snippets

Current Snippets:
"lit new" - scaffolds a new lit element

Adds code snippets to the project

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

Adds css-variable-autocomplete to recommended extensions and sets it up to look for uui css variables

uui css variable intellisense

---

src/backoffice/backoffice.element.ts
src/backoffice/editors/document-type/editor-document-type.element.ts
src/backoffice/editors/document/editor-document.element.ts
src/backoffice/editors/manifests.ts
src/backoffice/editors/media/editor-media.element.ts
src/backoffice/editors/user-group/editor-user-group.element.ts
src/backoffice/editors/user/editor-user.element.ts
src/backoffice/property-actions/manifests.ts
src/backoffice/property-editor-uis/manifests.ts
src/backoffice/sections/content/content-section.element.ts
src/backoffice/sections/manifests.ts
src/backoffice/sections/media/media-section.element.ts
src/backoffice/sections/packages/section-packages.element.ts
src/backoffice/sections/settings/settings-section.element.ts
src/backoffice/sections/users/section-users.element.ts
src/backoffice/trees/data-types/tree-data-types.element.ts
src/backoffice/trees/documents/tree-documents.element.ts
src/backoffice/trees/manifests.ts
src/core/extensions-registry/models.ts

removes ManifestWithLoader type, move the definition to ManifestElement.

remove ManifestWithLoader type, move the definition to ManifestElement.

---

src/core/context-api/consume/context-consumer.controller.ts
src/core/context-api/consume/context-consumer.ts
src/core/context-api/provide/context-provider.controller.ts
src/core/context-api/provide/context-provider.ts
src/core/controller/controller-host.mixin.ts
src/core/controller/controller.class.ts
src/core/controller/controller.interface.ts
src/core/controller/controller.test.ts
src/core/element/element.mixin.ts
src/core/element/lit-element.element.ts
src/core/observable-api/observer.controller.ts
src/core/observable-api/observer.ts
src/core/resources/resource.controller.ts

the ability for controllers to replace each other and testing this.

add and use unique to replace controllers if using same alias.

---

devops/icons/index.js

Update icon script to generate SVG icons into the JSON file and .js files that are referenced/used

Update icon script to use correct path to collection of SVGs

---

src/backoffice/users/current-user/current-user.store.ts

Adds a current user by taking the first user from the mock data

fix current user

---

libs/observable-api/array-state.test.ts
libs/observable-api/deep-state.test.ts
libs/observable-api/object-state.test.ts
src/backoffice/documents/document-blueprints/document-blueprint.detail.store.ts
src/backoffice/documents/document-blueprints/document-blueprint.tree.store.ts
src/backoffice/documents/document-types/document-type.detail.store.ts
src/backoffice/documents/document-types/document-type.tree.store.ts
src/backoffice/documents/documents/document.detail.store.ts
src/backoffice/documents/documents/document.tree.store.ts
src/backoffice/media/media-types/media-type.tree.store.ts
src/backoffice/media/media/media.detail.store.ts
src/backoffice/media/media/media.tree.store.ts
src/backoffice/members/member-types/member-type.tree.store.ts
src/backoffice/settings/data-types/data-type.detail.store.ts
src/backoffice/settings/data-types/data-type.tree.store.ts
src/backoffice/shared/components/workspace-property/workspace-property.context.ts
src/backoffice/translation/dictionary/dictionary.detail.store.ts
src/backoffice/translation/dictionary/dictionary.tree.store.ts
src/backoffice/users/current-user/current-user-history.store.ts
src/backoffice/users/user-groups/user-group.store.ts
src/backoffice/users/users/user.store.ts
src/stories/store.stories.mdx

Updated code using the new state.

use getObservablePart

---

src/backoffice/media/media/workspace/media-workspace.element.ts
src/backoffice/settings/data-types/workspace/data-type-workspace.element.ts

As the other sections these should be using load and create methods.

use the load and create methods

---

src/backoffice/documents/documents/document.detail.store.ts
src/backoffice/shared/components/workspace/workspace-content/views/edit/workspace-view-content-edit.element.ts
src/backoffice/shared/components/workspace/workspace-context/entity-manager-controller.ts
src/backoffice/shared/components/workspace/workspace-context/workspace-context.ts
src/backoffice/shared/property-editors/uis/number-range/property-editor-ui-number-range.element.ts

Corrected a few mistakes.
Making Entitymanager use arrow functions for now. This will go away with Repository anyway, but to make things work for now.
Ensuring the Workspace Alias fits across.   we should make a TOKEN, but we have an 'interface' challenge.

A few issues breaking workspaces

---

.github/workflows/build_test.yml

remove lcov reporter since it's spammy and just uploading the report instead

remove lcov reporter

---

libs/router/router-slot.element.ts
src/app.ts
src/backoffice/packages/package-section/views/created/created-packages-section-view.element.ts
src/backoffice/packages/package-section/views/installed/installed-packages-section-view.element.ts
src/backoffice/settings/dashboards/examine-management/dashboard-examine-management.element.ts
src/backoffice/settings/dashboards/health-check/dashboard-health-check.element.ts
src/backoffice/shared/collection/collection.element.ts
src/backoffice/shared/components/backoffice-frame/backoffice-main.element.ts
src/backoffice/shared/components/section/section-dashboards/section-dashboards.element.ts
src/backoffice/shared/components/section/section.element.ts
src/backoffice/users/user-section/views/users/section-view-users.element.ts
src/backoffice/users/user-section/views/users/workspace-view-users-overview.element.ts

Align so we always use the `umb-router-slot`

use umb-router-slot

---

src/backoffice/documents/document-types/manifests.ts
src/backoffice/documents/document-types/tree/manifests.ts

Fixes registration of document type repo in tree and section manifests

fix manifests

---

src/backoffice/translation/dictionary/repository/dictionary.repository.ts
src/backoffice/translation/dictionary/workspace/dictionary-workspace.context.ts

Updates dictionary repo to implement both tree and detail interfaces

UmbDetailRepository implemented in Dictionary repo

---

.github/CONTRIBUTING.md

Update the contrib doc images.
Change file path for images so they show up in the contrib doc.
- [ X ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)
Getting the contrib doc updated to help give examples to people who would like to contribute to the backoffice project.
View contrib.md file and verify images show up.
- [ X ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [ X ] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/.github/CONTRIBUTING.md)>)** document.
- [ X ] I have added tests to cover my changes.

update contrib images

---

src/backoffice/shared/components/workspace/workspace-action-menu/workspace-action-menu.element.ts

small fix for the action-menu positioning.

small fix for the action-menu positioning

---

.eslintrc.json
src/backoffice/documents/document-types/workspace/document-type-workspace.stories.ts
src/backoffice/media/media/entity-bulk-actions/trash/trash.action.ts
src/backoffice/media/media/workspace/media-workspace.stories.ts
src/backoffice/members/members/member.detail.store.ts
src/backoffice/packages/package-section/views/created/packages-created-overview.element.ts
src/backoffice/packages/package-section/views/installed/installed-packages-section-view-item.element.ts
src/backoffice/settings/dashboards/examine-management/views/section-view-examine-indexers.ts
src/backoffice/settings/extensions/workspace/extension-root-workspace.element.ts
src/backoffice/shared/components/input-language-picker/input-language-picker.element.ts
src/backoffice/shared/components/input-user-group/input-user-group.element.ts
src/backoffice/shared/components/input-user/input-user.element.ts
src/backoffice/shared/property-editors/uis/icon-picker/property-editor-ui-icon-picker.stories.ts
src/backoffice/shared/property-editors/uis/multiple-text-string/input-multiple-text-string-item/input-multiple-text-string-item.element.ts
src/backoffice/users/user-section/views/user-groups/user-group-table-name-column-layout.element.ts
src/backoffice/users/user-section/views/user-groups/user-group-table-sections-column-layout.element.ts
src/backoffice/users/user-section/views/user-groups/workspace-view-user-groups.element.ts
src/backoffice/users/user-section/views/users/list-view-layouts/table/workspace-view-users-table.element.ts
src/backoffice/users/user-section/views/users/workspace-view-users-selection.element.ts

import aliases

---

src/backoffice/settings/dashboards/models-builder/dashboard-models-builder.element.ts
src/backoffice/settings/dashboards/published-status/dashboard-published-status.element.ts
src/backoffice/settings/dashboards/settings-welcome/dashboard-settings-welcome.element.ts
src/backoffice/shared/components/section/section-main/section-main.element.ts

- fix a few warnings in the console
- wrapping the main content of the page with the `main` element
Issue #485

#485 settings dashboard accessibility

---

src/upgrader/upgrader.stories.ts

Convert to Storybook 7 format.

Convert Upgrader stories to new Storybook format

---

libs/context-api/debug/context-data.function.ts
src/backoffice/shared/components/debug/debug.element.ts

It would be useful if we could see some of the properties and values in objects assigned to contexts for umb-debug element viewer
Make the umb-debug element & browser extension provide even more useful info to developers
This shows the objects that are observables/subscribable RxJS stuff for developers

Umb Debug - Try to show more meaningful data

---

.storybook/preview-head.html
.storybook/preview.js

After the latest merges Storybook can not run or build.
This PR updates storybook to work with the latest code updates.

Bugfix: Fix storybook

---

src/packages/settings/themes/manifests.ts

Fixes the paths for the theme switcher

Fix theme switcher paths

---

src/packages/users/user-groups/entity-bulk-actions/delete/delete.action.ts
src/packages/users/users/collection/user-collection-header.element.ts
src/packages/users/users/entity-bulk-actions/delete/delete.action.ts
src/packages/users/users/entity-bulk-actions/disable/disable.action.ts
src/packages/users/users/entity-bulk-actions/enable/enable.action.ts
src/packages/users/users/entity-bulk-actions/unlock/unlock.action.ts
src/packages/users/users/modals/invite/user-invite-modal.element.ts
src/packages/users/users/repository/sources/user-disable.server.data.ts
src/packages/users/users/repository/sources/user-enable.server.data.ts
src/packages/users/users/repository/sources/user-unlock.server.data.ts
src/packages/users/users/repository/sources/user.server.data.ts
src/packages/users/users/repository/user.repository.ts
src/packages/users/users/types.ts

Implements bulk actions for users

Add user bulk actions

---

src/packages/core/workspace/workspace-variant/index.ts

fix: export umb-variantable-variant correctly

---

package.json
src/external/backend-api/src/models/ContentTreeItemResponseModel.ts
src/external/backend-api/src/models/DocumentTypeResponseModel.ts

Just another models update.
But also changed the URL for the "generate:API" script

Lastest api models

---

src/packages/core/modal/token/allowed-document-types-modal.token.ts
src/packages/core/workspace/index.ts
src/packages/core/workspace/workspace-footer/index.ts
src/packages/documents/document-types/modals/allowed-document-types/allowed-document-types-modal.element.ts
src/packages/documents/documents/entity-actions/create/create.action.ts

Work on create documents at root.
Cn be merged in the current state, but the feature is not done. Is awaiting the End-point for retrieving allowed document-types at root.

create documents at root

---

package.json
src/packages/users/current-user/index.ts
src/packages/users/user-section/index.ts
src/packages/users/users/index.ts
tsconfig.json
web-test-runner.config.mjs

user exports

---

src/packages/documents/document-types/workspace/manifests.ts
src/packages/documents/document-types/workspace/views/design/document-type-workspace-view-edit-tab.element.ts
src/packages/documents/document-types/workspace/views/settings/document-type-workspace-view-settings.element.ts
src/packages/documents/document-types/workspace/views/structure/document-type-workspace-view-structure.element.ts

Just a simple rename and some structural change and a little bit of UI changes.

Document Type Workspace: Rename details tab to settings

---

package.json
src/external/backend-api/src/index.ts
src/external/backend-api/src/models/DocumentItemResponseModel.ts
src/external/backend-api/src/models/DocumentTreeItemResponseModel.ts
src/external/backend-api/src/models/PropertyTypeResponseModelBaseModel.ts
src/external/backend-api/src/models/PublishedStateModel.ts
src/external/backend-api/src/models/VariantTreeItemModel.ts
src/mocks/data/utils.ts

Updated api calls, including fixing our npm script to target management api.

Api updates

---

.storybook/preview.js
src/apps/app/app.element.ts
src/libs/extension-api/types.ts
src/packages/users/current-user/modals/current-user/current-user-modal.element.ts

fix storybook imports

---

src/packages/templating/templates/entity-actions/create/create.action.ts
src/packages/templating/templates/workspace/template-workspace.context.ts
src/packages/templating/templates/workspace/template-workspace.element.ts

A minor change to the work of Julias PR #796 796

null as root parentId

---

package-lock.json
package.json

Updated the UI Library to 1.4.0-rc.1

update uui to newest version

---

README.md
src/packages/core/localization/localize.element.test.ts
src/packages/templating/components/insert-menu/templating-insert-menu.element.ts
utils/json-schema/test-package.json

Updates the documentation so it fits with how its done today.

Update documentation to use new conditions system

---

storybook/stories/extending/registration/conditions.mdx

correct mdx docs

---

package-lock.json
package.json

update UUI to rc2

---

src/packages/users/users/index.ts
src/packages/users/users/repository/index.ts

This PR exports the UmbUserRepository from the @umbraco-cms/backoffice/users

Feature: Export UmbUserRepository from user module

---

src/packages/core/components/input-list-base/input-list-base.ts
src/packages/users/user-groups/collection/user-group-collection-header.element.ts
src/packages/users/user-groups/collection/user-group-collection-view.element.ts
src/packages/users/user-groups/workspace/user-group-workspace-editor.element.ts
src/packages/users/users/collection/user-collection-header.element.ts
src/packages/users/users/collection/views/grid/user-collection-grid-view.element.ts
src/packages/users/users/collection/views/table/column-layouts/status/user-table-status-column-layout.element.ts
src/packages/users/users/workspace/user-workspace-editor.element.ts
src/packages/users/utils.test.ts
src/packages/users/utils.ts

Add localization of user(s) and usergroup(s)

---

src/mocks/data/data-type.data.ts
src/packages/core/property-editor/uis/text-box/property-editor-ui-text-box.element.ts

input mode for property editor text box

input mode for property editor text box

---

src/packages/core/workspace/workspace-property-layout/workspace-property-layout.element.ts

out comment container-queries as they don't work currently.

out-commented container queries for now

---

.github/localization_overview.md
src/packages/settings/dashboards/performance-profiling/dashboard-performance-profiling.element.ts

Localization Markdown Overview

Localization MD overview

---

.github/localization_overview.md
src/assets/lang/da-dk.ts
src/assets/lang/en-us.ts
src/packages/settings/dashboards/settings-welcome/dashboard-settings-welcome.element.ts

More localization, new keys for settings-welcome dashboard.
Keys added to localization overview for help.

localization for settingsdashboard

---

package-lock.json
package.json

Bump @umbraco-ui/uui to 1.5.0 final

build(deps): bump @umbraco-ui/uui from 1.5.0-rc.3 to 1.5.0

---

.github/localization_overview.md
src/packages/settings/dashboards/telemetry/dashboard-telemetry.element.ts

Localization for telemetry dashboard.

localization for telemetry

---

web-test-runner.config.mjs

Hack to remove lit dev mode warning.

hack to remove lit dev mode warning

---

src/packages/templating/scripts/entity-actions/create/create-empty.action.ts
src/packages/templating/scripts/workspace/script-workspace-edit.element.ts
src/packages/templating/scripts/workspace/script-workspace.context.ts
src/packages/templating/scripts/workspace/script-workspace.element.ts
src/packages/templating/stylesheets/workspace/stylesheet-workspace-editor.element.ts
src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts

- Redirecting scripts from create workspace to edit workspace when saving
- Fixed an issue where scripts could not be created inside a folder that's inside a folder
- Fixed an issue with the path preview of stylesheets and scripts

fix script and stylesheet pathing

---

src/apps/backoffice/backoffice.element.ts
src/libs/class-api/context-base.class.ts

Wups, late fix of refactoring.

Bug fix/fix backoffice context

---

src/packages/core/property-editor/schemas/Umbraco.CheckboxList.ts

To keep the consistency across the codebase.

Corrected casing of "CheckboxList"

---

src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts

Following the same pattern using the `UmbSorterController` as implemented in [multiple-color-picker-input.element.ts](https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/7f33d0cdb01adba965e22d7e03baa5712b34885b/src/packages/core/components/multiple-color-picker-input/multiple-color-picker-input.element.ts#L17)
This can be tested on the **Checkbox List** data-type configuration.

Added sorting to multiple-text-string element

---

src/packages/log-viewer/components/log-viewer-date-range-selector.element.ts
src/packages/log-viewer/workspace/logviewer.context.ts
src/packages/log-viewer/workspace/views/overview/components/log-viewer-message-templates-overview.element.ts
src/packages/log-viewer/workspace/views/overview/log-overview-view.element.ts
src/packages/log-viewer/workspace/views/search/components/log-viewer-message.element.ts
src/packages/log-viewer/workspace/views/search/components/log-viewer-messages-list.element.ts
src/packages/log-viewer/workspace/views/search/components/log-viewer-search-input.element.ts
src/packages/log-viewer/workspace/views/search/log-search-view.element.ts

PR that fixes a couple of bugs from the issue tracker, related to the Log Viewer.
- https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/951
- https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1004
- https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1005
- https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1008

Log Viewer: Bugs from issue tracker

---

src/packages/settings/languages/entity-actions/language-create-entity-action.ts

Fixes an issue where the create entity action would do a full page refresh.

Bugfix: Dont do full page reload when creating language from the entity action button

---

src/external/router-slot/util/anchor.ts

Fix CTRL + click or CMD + Click so we can open links in a new tab.

Fix: Make sure we dont use history api if user wants to open in a new tab.

---

src/packages/core/data-type/tree/folder/data-type-folder.repository.ts
src/packages/documents/document-types/entity-actions/create/create.action.ts
src/packages/documents/document-types/entity-actions/create/modal/document-type-create-options-modal.element.ts
src/packages/documents/document-types/entity-actions/create/modal/index.ts
src/packages/documents/document-types/tree/folder/document-type-folder.repository.ts
src/packages/documents/document-types/tree/folder/document-type-folder.server.data-source.ts
src/packages/documents/document-types/tree/folder/index.ts
src/packages/documents/document-types/tree/folder/manifests.ts
src/packages/documents/document-types/tree/folder/types.ts
src/packages/documents/document-types/tree/index.ts
src/packages/documents/document-types/tree/manifests.ts

This PR implements folders for Document Types

Feature: Document Type Folders

---

src/packages/media/media/tree/media-tree.server.data-source.ts

eslint ignorer

---

src/libs/extension-api/controller/base-extension-initializer.controller.ts
src/libs/extension-api/controller/base-extensions-initializer.controller.ts
src/libs/extension-api/initializers/bundle-extension-initializer.ts
src/libs/extension-api/initializers/entry-point-extension-initializer.ts
src/libs/extension-api/registry/extension.registry.test.ts
src/libs/extension-api/registry/extension.registry.ts
src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
src/packages/core/components/input-section/input-section.element.ts
src/packages/core/components/input-tiny-mce/input-tiny-mce.element.ts
src/packages/core/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
src/packages/core/data-type/modals/property-editor-ui-picker/property-editor-ui-picker-modal.element.ts
src/packages/core/localization/components/ui-culture-input/ui-culture-input.element.ts
src/packages/core/localization/registry/localization.registry.ts
src/packages/core/modal/common/section-picker/section-picker-modal.element.ts
src/packages/core/property-editor/uis/tiny-mce/config/toolbar/property-editor-ui-tiny-mce-toolbar-configuration.element.ts
src/packages/core/themes/theme.context.ts
src/packages/core/tree/tree-item-base/tree-item-base.context.ts
src/packages/health-check/dashboard-health-check.element.ts
src/packages/packages/package-section/views/created/created-packages-section-view.element.ts
src/packages/packages/package-section/views/installed/installed-packages-section-view-item.element.ts
src/packages/user/current-user/user-profile-apps/user-profile-app-themes.element.ts
src/packages/user/user-group/collection/components/user-group-table-sections-column-layout.element.ts
src/packages/user/user-group/components/user-group-ref/user-group-ref.element.ts
src/packages/user/user-group/workspace/components/user-group-default-permission-list.element.ts
src/packages/user/user-permission/components/entity-user-permission-settings-list/entity-user-permission-settings-list.element.ts

* More refactoring to make it easier to work with
* More tests
* Better typings
* Aligned names with our convention of not naming observable by 'get...'

Align naming + clean up + more tests

---

docs/authentication.md

Update auth docs

---

src/packages/block/block-list/components/ref-list-block/ref-list-block.element.ts
src/packages/core/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
src/packages/core/data-type/workspace/views/details/data-type-details-workspace-view.element.ts
src/packages/documents/documents/components/input-document-root-picker/input-document-root-picker.element.ts
src/packages/documents/documents/entity-actions/permissions/permissions-modal.element.ts

just correcting a few more attributes

use standalone

---

src/packages/user/user/collection/index.ts
src/packages/user/user/index.ts

export user collection repository

---

.vscode/extensions.json

append edittor config to vscode recommendations

---

src/packages/core/collection/default/collection-default.context.ts
src/packages/core/collection/types.ts
src/packages/core/property-editor/uis/collection-view/config/column-configuration/property-editor-ui-collection-view-column-configuration.element.ts
src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
src/packages/documents/documents/collection/views/index.ts
src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts

Aligns the code for both the Table and Grid views for the Document Collections.

Document Collection Views refactor

---

src/packages/documents/documents/collection/action/create-document-collection-action.element.ts

This patch wires up the Collection's "Open in Infinity Editor" option, so that the create new document action will open in a modal.
Note: There is a small issue with the URL of the modal overlay, which I'm hoping can be resolved soon.

Feature: Document Collection: Create Document action opens in modal

---

src/packages/dictionary/collection/views/table/dictionary-table-collection-view.element.ts
src/packages/dictionary/workspace/views/workspace-view-dictionary-editor.element.ts
src/packages/documents/documents/entity-actions/culture-and-hostnames/modal/culture-and-hostnames-modal.element.ts
src/packages/language/app-language-select/app-language-select.element.ts
src/packages/language/modals/language-picker/language-picker-modal.element.ts

adjust filter for language requestCollection so we use the default (currently set to 100)

The same amount of languages are not always requested

---

src/mocks/data/partial-view/partial-view.data.ts

Minor typo in the path of embed.cshtml in mock data.

Fix path in embed.cshtml mock data

---

src/mocks/data/document/document-collection.manager.ts
src/mocks/data/document/document.db.ts
src/mocks/data/media/media-collection.manager.ts
src/mocks/data/media/media.data.ts
src/mocks/data/media/media.db.ts
src/mocks/handlers/document/collection.handlers.ts
src/mocks/handlers/document/index.ts
src/mocks/handlers/media/collection.handlers.ts
src/mocks/handlers/media/index.ts

Adds mock API for Document and Media Collection.
This is to compliment the work done in #1203 and #1249.

Chore: Mock API for Document and Media Collection

---

src/packages/documents/documents/index.ts

Document Tree Repositories export

---

src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
src/packages/documents/documents/collection/views/manifests.ts
src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
src/packages/documents/documents/entity-bulk-actions/manifests.ts

These changes came from aligning code with the Media Collection work in PR #1250.

Chore: Document Collection code tidy-up

---

src/packages/core/components/multiple-color-picker-input/multiple-color-picker-input.element.ts
src/packages/core/property-editor/schemas/Umbraco.Dropdown.Flexible.ts
src/packages/core/property-editor/uis/color-swatches-editor/property-editor-ui-color-swatches-editor.element.ts
src/packages/core/property-editor/uis/text-box/manifests.ts
src/packages/media/media/section-view/media-section-view.element.ts

Some small fixes for `14.0.0--preview007` release.

Fixes for `14.0.0--preview007` release

---

LICENSE
src/shared/icon-registry/LICENSE

Just a short fix to get the Lucide License in a prominent spot. 
But we should look into other ways of doing this in the future.

Append Lucide License

---

src/packages/media/media/collection/action/create-media-collection-action.element.ts
src/packages/media/media/collection/action/manifests.ts
src/packages/media/media/collection/manifests.ts

Adds the "Create" action/button for the Media Collection UI, with

Feature: Media Collection: Create Action

---

src/packages/data-type/umbraco-package.ts
src/packages/tiny-mce/umbraco-package.ts

Yeah, sorry a little mistake from my side.

Fix mistake in latest new packages

---

src/packages/documents/documents/conditions/document-workspace-has-collection.condition.ts
src/packages/documents/documents/workspace/document-workspace.context.ts
src/packages/documents/documents/workspace/views/collection/document-workspace-view-collection.element.ts

> [!IMPORTANT]
> Waiting on PR #1270 to be merged in before marking this PR as ready for review.

Wires up Content Type Collections repository/data-source

---

src/mocks/data/data-type/data-type.data.ts
src/packages/media/media/collection/repository/media-collection.repository.ts
src/packages/media/media/collection/repository/media-collection.server.data-source.ts
src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
src/packages/media/media/section-view/media-section-view.element.ts

Wired up the Media section view with the Collection data-type configuration.
Also added support for the `sortOrder` value in the Media Collection Views.

Media section view collection amends

---

src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts
src/packages/user/user-group/workspace/user-group-workspace.context.ts

This feature needs to be reimplemented as the server part will change. 
I have removed the current code, because it doesn't work.

Bugfix: remove incomplete assign users to groups feature

---

package.json

What it says, super simple, just an easy way to switch without manipulating files.

script for different dev modes

---

.vscode/settings.json
src/packages/core/sorter/sorter.controller.ts
src/packages/core/workspace/workspace-is-new-redirect-controller/workspace-is-new-redirect-controller.ts
src/packages/data-type/workspace/data-type-workspace-editor.element.ts
src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
src/packages/documents/document-types/workspace/document-type-workspace.element.ts
src/packages/documents/document-types/workspace/views/design/document-type-workspace-view-edit-properties.element.ts
src/packages/documents/document-types/workspace/views/design/document-type-workspace-view-edit-property.element.ts
src/packages/documents/document-types/workspace/views/design/document-type-workspace-view-edit-tab.element.ts
src/packages/language/workspace/language/language-workspace.element.ts
src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
src/packages/media/media-types/workspace/views/design/media-type-workspace-view-edit-property.element.ts

Fixes of Document Type Editor

---

src/packages/documents/document-types/workspace/document-type-workspace.context.ts
src/packages/media/media-types/repository/detail/media-type-detail.server.data-source.ts
src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
src/packages/media/media-types/workspace/media-type-workspace.context.ts
src/packages/media/media-types/workspace/views/structure/media-type-workspace-view-structure.element.ts

Follows the same pattern as PR #1306 (Document Type Structure - configure collection UI).
With some alignment and tidy-up in the `UmbMediaTypeWorkspaceContext` class.

Feature: Media Type Structure - configure collection UI

---

src/libs/extension-api/controller/base-extension-initializer.controller.ts

Make sure we handle these cases, as they do happen.

Fix: handle conditions changed while processing

---

src/packages/core/property/property/property.context.ts
src/packages/core/property/property/property.element.ts
src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts

append getters for less lit 3 warnings

---

src/packages/core/property-editor/uis/collection-view/config/layout-configuration/property-editor-ui-collection-view-layout-configuration.element.ts

fix value of property editors can be undefined

---

src/apps/installer/consent/installer-consent.element.ts
src/apps/installer/database/installer-database.element.ts
src/apps/installer/installer.context.ts

* Adds checkbox for `trustServerCertificate`
* Sets default telemetry level to `DETAILED`

Installer does not allow `trustServerCertificate` for SQL Server

---

src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts
src/packages/templating/templates/workspace/template-workspace.context.ts

Bugfix: Redirect template and stylesheet when creating new

---

src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts

The info tab does not really take variants into account. This is trying to find the oldest variant for the "create date" and informing about all variant states at once.

Render variant states

---

src/packages/data-type/collection/index.ts
src/packages/data-type/collection/manifests.ts
src/packages/data-type/collection/repository/data-type-collection.repository.ts
src/packages/data-type/collection/repository/data-type-collection.server.data-source.ts
src/packages/data-type/collection/repository/index.ts
src/packages/data-type/collection/repository/manifests.ts
src/packages/data-type/collection/repository/types.ts
src/packages/data-type/collection/types.ts
src/packages/data-type/manifests.ts
src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-data-type-picker-modal.element.ts
src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts

Replacing the placeholder Tree repository calls with the new Collection repository.

Feature: DataType Picker Flow, now using DataType Filter endpoint

---

src/packages/packages/package-section/manifests.ts

The implementation is not finalised so there is no need to show it at the moment.

Chore: Temp remove create package section view

---

src/mocks/data/log-viewer.data.ts
src/mocks/handlers/log-viewer.handlers.ts
src/packages/log-viewer/workspace/logviewer.context.ts
src/packages/log-viewer/workspace/logviewer/logviewer-workspace.element.ts
src/packages/log-viewer/workspace/views/overview/components/log-viewer-log-level-overview.element.ts
src/packages/log-viewer/workspace/views/overview/components/log-viewer-message-templates-overview.element.ts
src/packages/log-viewer/workspace/views/overview/components/log-viewer-saved-searches-overview.element.ts
src/packages/log-viewer/workspace/views/search/components/log-viewer-messages-list.element.ts
src/packages/log-viewer/workspace/views/search/components/log-viewer-search-input.element.ts
src/packages/log-viewer/workspace/views/search/log-search-view.element.ts

Pagination added for common log messages (10 per page) and saved searches (15 per page). Can be changed

Feature: LogViewer pagination

---

src/packages/core/collection/components/collection-view-bundle.element.ts
src/packages/core/collection/default/collection-default.element.ts
src/packages/core/components/extension-with-api-slot/extension-with-api-slot.element.ts
src/packages/core/utils/selection-manager/selection.manager.ts
src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
src/packages/documents/documents/collection/document-collection.context.ts
src/packages/documents/documents/collection/repository/document-collection.repository.ts
src/packages/documents/documents/collection/repository/document-collection.server.data-source.ts
src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
src/packages/documents/documents/workspace/views/collection/document-workspace-view-collection.element.ts
src/packages/media/media/collection/media-collection.context.ts
src/packages/media/media/collection/repository/media-collection.repository.ts
src/packages/media/media/workspace/views/collection/media-workspace-view-collection.element.ts

Corrected several snags with the Collections UI for Documents and Media, as well as friendlier DX for extension implementations.

Bugfix: Collections UI snags

---

src/packages/media/media-types/workspace/manifests.ts
src/packages/media/media-types/workspace/media-type-workspace.context.ts
src/packages/members/member-type/workspace/manifests.ts
src/packages/members/member-type/workspace/member-type-workspace.context.ts

Align member type, so it works again.

fix member type editor

---

src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
src/packages/language/global-contexts/app-language.context.ts

This PR adds functionality to render the label for the currently selected app language

Feature: Document tree item variant label

---

src/packages/members/member/workspace/views/content/member-workspace-view-content-properties.element.ts

BUGFIX: Member content view not rendering. 

---

src/apps/app/app.context.ts
src/packages/core/auth/auth.context.ts
src/packages/core/router/route.context.ts
src/packages/core/section/section-sidebar/section-sidebar.context.ts
src/packages/core/section/section-sidebar/section-sidebar.element.ts
src/packages/core/themes/theme.context.ts
src/packages/core/workspace/components/workspace-split-view/workspace-split-view.context.ts
src/packages/core/workspace/workspace-property-dataset/invariant-workspace-property-dataset-context.ts
src/packages/documents/documents/global-contexts/document-configuration.context.ts
src/packages/documents/documents/property-dataset-context/document-property-dataset-context.token.ts
src/packages/language/global-contexts/app-language.context.ts

A few minor corrections, updates from a forgotten branch.

Improvements: forgotten improvements from old PR

---

docs/authentication.md

Amended paths to remove the old "New" paths.

Chore: Updated Authentication documentation

---

src/packages/core/property-editor/uis/user-picker/property-editor-ui-user-picker.element.ts
src/packages/user/user/components/user-input/user-input.element.ts
src/packages/user/user/modals/user-picker/user-picker-modal.element.ts

This PR doesn't fix everything with the User Picker, there are still something that are broken (e.g. the server is expecting an `int` value, of the User ID), but there are other UI amends go towards any future fixes.

Bugfix: User Picker UI

---

src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
src/packages/core/components/input-radio-button-list/input-radio-button-list.stories.ts
src/packages/core/property-editor/uis/radio-button-list/property-editor-ui-radio-button-list.element.ts

With recent changes to how the Management API sends the data structure for the Radio Button List, the UI was completely broken™. This PR fixes that.

Bugfix: Radio Button List data structure

---

src/packages/core/property-editor/uis/checkbox-list/input-checkbox-list/input-checkbox-list.element.ts
src/packages/core/property-editor/uis/checkbox-list/input-checkbox-list/input-checkbox-list.stories.ts
src/packages/core/property-editor/uis/checkbox-list/property-editor-ui-checkbox-list.element.ts

With recent changes to how the Management API sends the data structure for the Checkbox List, the UI was completely broken™. This PR fixes that.

Bugfix: CheckboxList data structure

---

src/packages/core/property-editor/schemas/Umbraco.Decimal.ts
src/packages/core/property-editor/uis/number/manifests.ts

Allows decimal in the step setting for decimals.
Bug:
Step property cannot be set for the step setting?

Feature: Allow Decimals in step setting

---

package.json
typedoc.config.js

- Updates the script names to be prefixed with either server or ui as they now collide.
- Updates the API docs folder name to fit the host

Chore: Explicit API script names

---

src/packages/settings/dashboards/published-status/dashboard-published-status.element.ts

Removes a debug element that should be in the UI

Bugfix: Remove debug element in dashboard

---

src/packages/block/block-grid/property-editors/block-grid-type-configuration/property-editor-ui-block-grid-type-configuration.element.ts
src/packages/block/block-list/property-editors/block-list-type-configuration/property-editor-ui-block-list-type-configuration.element.ts
src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
src/packages/block/block-type/workspace/manifests.ts

Enables sorting for the blocks config editor.
Small breaking change.
- Deleting a block now dispatches a `delete` event rather than change.

Feature: Sorter for block grid and list config editor

---

src/packages/core/modal/common/item-picker/item-picker-modal.element.ts
src/packages/core/modal/component/modal-base.element.ts

Adds a filter input to the Item Picker modal.

Feature: Item Picker modal filter

---

src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
src/packages/tiny-mce/property-editors/block-configuration/property-editor-ui-block-rte-type-configuration.element.ts
src/packages/tiny-mce/property-editors/dimensions/property-editor-ui-tiny-mce-dimensions-configuration.element.ts
src/packages/tiny-mce/property-editors/max-image-size/property-editor-ui-tiny-mce-maximagesize-configuration.element.ts

Fixes some bug issues in RTE editor.
- Can now update width/height dimensions
- Can now update max img size
- Can add blocks

Feature: RTE PropertyEditor bug fixes

---

src/packages/core/extension-registry/menu-item/manifests.ts
src/packages/core/extension-registry/workspace/extension-root-workspace.element.ts
src/packages/core/settings/manifests.ts
src/packages/dictionary/menu/manifests.ts
src/packages/documents/documents/menu.manifests.ts
src/packages/log-viewer/menu-item/manifests.ts
src/packages/media/media/menu.manifests.ts
src/packages/media/menu.manifests.ts
src/packages/relations/relation-types/menu-item/manifests.ts
src/packages/templating/menu.manifests.ts

Feature: Advanced settings menu

---

src/packages/documents/documents/workspace/document-workspace-editor.element.ts

Bugfix: Invariant workspace url

---

src/packages/core/workspace/index.ts
src/packages/user/current-user/profile/current-user-profile-user-profile-app.element.ts
src/packages/user/user-group/entity.ts
src/packages/user/user-group/section-view/user-group-section-view.element.ts
src/packages/user/user/collection/views/grid/user-grid-collection-view.element.ts
src/packages/user/user/collection/views/table/column-layouts/name/user-table-name-column-layout.element.ts
src/packages/user/user/modals/create/create-user-success-modal.element.ts
src/packages/user/user/section-view/users-section-view.element.ts
src/packages/user/user/workspace/user-workspace.context.ts

The User and User Group workspace aren't loading. This PR fixes that.
- [ x] Bug fix (non-breaking change which fixes an issue)

Bugfix: User + User group workspace not loading

---

src/libs/element-api/element.mixin.ts

only initialize localization controller if used

---

src/packages/core/extension-registry/models/workspace-view.model.ts
src/packages/core/workspace/components/workspace-collection/manifests.ts
src/packages/documents/documents/workspace/manifests.ts
src/packages/media/media/workspace/manifests.ts

Added a new Kind for Collection workspace views, for reuse of the Document and Media collections.

Feature: Workspace View Collection Kind

---

src/packages/core/culture/components/input-culture-select/input-culture-select.element.ts
src/packages/language/workspace/language/views/language-details-workspace-view.element.ts

Fixes a bug that wouldn't allow the user to create a new language.

Bugfix: Language select

---

src/packages/documents/document-blueprints/entity-actions/create/create.action.ts

Blueprint Create Action: Navigate to the correct URL when creating a blueprint from a documenttype.

Feature: Blueprint Create Action URL

---

src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
src/packages/block/block-grid/workspace/views/block-grid-type-workspace-view-settings.element.ts

Correct the config Alias + debounce change events
Fixes https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1558

Fix: Block Grid Editor, Allow Block at root

---

src/packages/block/block-type/workspace/block-type-workspace.context.ts
src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts

fix: remove event listener

---

src/packages/documents/document-blueprints/types.ts
src/packages/documents/documents/entity-actions/create-blueprint/create-blueprint.action.ts
src/packages/documents/documents/entity-actions/create-blueprint/index.ts
src/packages/documents/documents/entity-actions/create-blueprint/modal/create-blueprint-modal.element.ts
src/packages/documents/documents/entity-actions/create-blueprint/modal/create-blueprint-modal.token.ts
src/packages/documents/documents/entity-actions/create-blueprint/repository/document-create-blueprint.repository.ts
src/packages/documents/documents/entity-actions/create-blueprint/repository/document-create-blueprint.server.data-source.ts
src/packages/documents/documents/entity-actions/create-blueprint/repository/index.ts
src/packages/documents/documents/entity-actions/create-blueprint/repository/manifests.ts
src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
src/packages/documents/documents/workspace/document-workspace.context.ts

Creates a blueprint from a document, and a document from a blueprint.

Feature: Document create Blueprints and from Blueprints

---

src/packages/core/auth/modals/manifests.ts
src/packages/core/components/multiple-color-picker-input/multiple-color-picker-input.element.ts
src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
src/packages/dictionary/collection/views/manifests.ts
src/packages/dictionary/workspace/manifests.ts
src/packages/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
src/packages/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
src/packages/media/media-types/entity-actions/create/manifests.ts
src/packages/media/media-types/property-editors/media-type-picker/manifests.ts
src/packages/media/media-types/property-editors/media-type-picker/property-editor-ui-media-type-picker.element.ts
src/packages/media/media-types/workspace/manifests.ts
src/packages/media/media/entity-actions/create/manifests.ts
src/packages/media/media/property-editors/image-cropper/manifests.ts
src/packages/media/media/property-editors/image-crops-configuration/manifests.ts
src/packages/media/media/property-editors/media-picker/manifests.ts
src/packages/media/media/workspace/manifests.ts
src/packages/models-builder/manifests.ts
src/packages/settings/dashboards/manifests.ts
src/packages/tags/property-editors/tags/manifests.ts
src/packages/templating/modals/manifests.ts
src/packages/templating/partial-views/entity-actions/create/manifests.ts
src/packages/templating/scripts/entity-actions/create/manifests.ts
src/packages/templating/stylesheets/components/stylesheet-input/stylesheet-input.element.ts
src/packages/templating/stylesheets/components/stylesheet-rule-input/manifests.ts
src/packages/templating/stylesheets/entity-actions/create/manifests.ts
src/packages/templating/stylesheets/workspace/manifests.ts
src/packages/templating/templates/modals/manifests.ts

A bunch of minor fixes that I'd picked up on whilst working on other features and doing code reviews, that I didn't deem significant enough to have as their own pull requests, but good to get these in for RC001. 🚀

Chore: Lee's code sweep (for RC001)

---

src/packages/core/section/section-picker-modal/section-picker-modal.element.ts

Localize section labels in picker

Bugfix: Localize section labels in picker

---

src/packages/core/workspace/components/variant-selector/variant-selector.element.ts

Hide variant dropdown when invariant

Bugfix: Hide variant dropdown when invariant

---

src/packages/media/media/tree/manifests.ts
src/packages/media/media/tree/tree-item/media-tree-item.context.ts
src/packages/media/media/tree/tree-item/media-tree-item.element.ts

feature: Media Tree Item

---

src/packages/data-type/tree/data-type-tree.store.ts
src/packages/dictionary/tree/dictionary-tree.store.ts
src/packages/documents/document-blueprints/tree/document-blueprint-tree.store.ts
src/packages/documents/document-types/tree/document-type.tree.store.ts
src/packages/documents/documents/tree/document-tree.store.ts
src/packages/media/media-types/tree/media-type-tree.store.ts
src/packages/media/media/tree/media-tree.store.ts
src/packages/members/member-type/tree/member-type-tree.store.ts
src/packages/templating/partial-views/tree/partial-view-tree.store.ts
src/packages/templating/stylesheets/tree/stylesheet-tree.store.ts
src/packages/templating/templates/tree/template-tree.store.ts

Trees are manually updated, so the store connector doesn't do anything for the tree store. This PR removes all the store connector code for trees.

Chore: Remove unused store connector for trees

---

src/packages/core/section/section-sidebar-context-menu/section-sidebar-context-menu.element.ts

Localizes the sidebar context menu headline, (taking the localization key from the tree/menu manifest).

Bugfix: Localizes the sidebar context menu headline

---

src/packages/user/user-group/repository/detail/user-group-detail.server.data-source.ts
src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts

Adds the missing icon picker for user groups

bugfix: Add missing user group icon picker

---

src/packages/language/components/index.ts
src/packages/language/index.ts
src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts

This PR adds the missing language permission UI to a user group workspace

Bugfix: User group add missing language permissions

---

package-lock.json
package.json

fix: the background bleeds through certain modals

---

src/external/backend-api/src/services.ts

Generate new server models (2024-04-16)

chore: generate new server models

---

src/packages/documents/documents/components/input-document/input-document.element.ts

Remove guid in picked document

Bugfix: Remove guid in picked document

---

src/packages/user/user-group/collection/views/user-group-table-collection-view.element.ts

Render the user group document and media start node names in the collection.

Bugfix: Look up user group start node names

---

src/packages/core/components/input-number-range/input-number-range.element.ts

One last form control related fix

fix number range from control implementation

---

src/packages/data-type/repository/detail/data-type-detail.repository.ts
src/packages/data-type/repository/detail/data-type-detail.store.ts
src/packages/data-type/repository/detail/manifests.ts
src/packages/data-type/repository/item/data-type-item.repository.ts
src/packages/data-type/repository/item/data-type-item.store.ts
src/packages/data-type/repository/item/manifests.ts
src/packages/data-type/tree/data-type-tree.repository.ts
src/packages/data-type/tree/data-type-tree.store.ts
src/packages/data-type/tree/manifests.ts

Lazy loading data types repos + stores from manifests

Improvementy: Lazy load Data Type repo + stores

---

src/packages/members/member-type/modal/member-type-picker-modal.token.ts

Use import alias instead of relative import.

Use alias import of modal token

---

src/packages/data-type/entity-actions/create/create.action.ts
src/packages/data-type/entity-actions/create/manifests.ts
src/packages/data-type/entity-actions/duplicate/repository/data-type-duplicate.repository.ts
src/packages/data-type/entity-actions/duplicate/repository/manifests.ts
src/packages/data-type/entity-actions/move-to/repository/data-type-move.repository.ts
src/packages/data-type/entity-actions/move-to/repository/manifests.ts
src/packages/data-type/tree/folder/data-type-folder.repository.ts
src/packages/data-type/tree/folder/manifests.ts

To ensure that manifest bundling doesn't include anything else than manifests, we need to lazy load all elements/apis

Data Type - manifest lazy load apis (bundling prep)

---

src/packages/webhook/index.ts

Removes import of file that doesn't exist.

Bugfix: remove import of components

---

src/packages/core/workspace/components/workspace-action/common/submit/submit.action.ts

This PR fixes the save button sometimes being disabled. The button didn't get reenabled when the unique was set to a value.

Bugfix: Save button is randomly disabled

---

src/packages/core/components/input-multi-url/input-multi-url.element.ts
src/packages/core/modal/common/link-picker/link-picker-modal.element.ts
src/packages/core/modal/token/link-picker-modal.token.ts
src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
src/packages/property-editors/multi-url-picker/property-editor-ui-multi-url-picker.element.ts

Fixed various issues with the Multi-URL Picker editor.
- Added sorting
- Added removal confirmation modal
- Fixed the Overlay Size bug, re: #1673
- Hides the tree item actions in the modal (for Documents and Media)
- Disables the search input in the modal _(temporary fix)_

Bugfix: Added sorting to Multi-URL Picker

---

src/packages/property-editors/collection-view/config/column/column-configuration.element.ts
src/packages/property-editors/collection-view/config/layout/layout-configuration.element.ts

Added sorting to the Collection View configuration editors for Columns and Layout.

Bugfix: Added sorting to Collection configuration editors

---

src/packages/documents/document-blueprints/entity-actions/manifests.ts
src/packages/documents/document-blueprints/entity-actions/move-to/index.ts
src/packages/documents/document-blueprints/entity-actions/move-to/manifests.ts
src/packages/documents/document-blueprints/entity-actions/move-to/repository/constants.ts
src/packages/documents/document-blueprints/entity-actions/move-to/repository/document-blueprint-move.repository.ts
src/packages/documents/document-blueprints/entity-actions/move-to/repository/document-blueprint-move.server.data-source.ts
src/packages/documents/document-blueprints/entity-actions/move-to/repository/index.ts
src/packages/documents/document-blueprints/entity-actions/move-to/repository/manifests.ts
src/packages/documents/document-blueprints/menu-item/manifests.ts
src/packages/documents/document-blueprints/tree/constants.ts
src/packages/documents/document-blueprints/tree/index.ts
src/packages/documents/document-blueprints/tree/manifests.ts

MoveTo entity action for document blueprints.

Feature: Move Entity Action

---

src/packages/core/components/input-entity/input-entity.element.ts
src/packages/data-type/components/data-type-input/data-type-input.element.ts
src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
src/packages/language/components/input-language/input-language.element.ts
src/packages/media/media-types/components/input-media-type/input-media-type.element.ts
src/packages/templating/stylesheets/components/stylesheet-rule-input/stylesheet-rule-input.element.ts
src/packages/user/user/components/user-input/user-input.element.ts

Added missing sorting feature to the following picker inputs...
- Data Type picker
- Document Type picker
- Entity picker
- Language picker
- Media Type picker
- Stylesheet Rule picker
- User picker
Also tidied up the code/markup for consistency between pickers.
To test this, either use Kenn's comprehensive test database (internal use only, so far), or the Cream Package Builder section makes use of most of these pickers.

Bugfix: Added sorting to picker inputs

---

src/packages/core/workspace/components/workspace-entity-action-menu/workspace-entity-action-menu.element.ts

Fix: umb-workspace-entity-action-menu: only prevent rendering when undefined

---

src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
src/packages/documents/documents/paths.ts

dont show label for block type + use parent path

---

src/packages/core/extension-registry/conditions/section-alias.condition.ts

Ability to configure section alias condition with oneOf

---

src/packages/media/media/collection/repository/media-collection.server.data-source.ts
src/packages/media/media/collection/types.ts
src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
src/packages/media/media/collection/views/table/column-layouts/media-table-column-name.element.ts
src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
src/packages/media/media/index.ts
src/packages/media/media/paths.ts

Aligns the Media Collection Views with the fixes made in Document Collection Views (PR #1736).
- Adds loading state
- Fixes open media editor modal

Bugfix: Media Collection View - loading state + opens modal

---

src/packages/documents/document-types/entity-actions/create/manifests.ts

Bugfix: remove create action on doc type items

---

src/packages/core/components/split-panel/split-panel.element.ts

Adds overflow to the split panel slots to allow scrolling

Bugfix: Split panel overflow

---

src/packages/language/repository/detail/language-detail.server.data-source.ts

This PR removes the code that lowercase the language iso code. I thought it would fix a bug where some languages couldn't be created because of an invalid iso code, but it didn't. The PR is still valid as we shouldn't change the iso codes coming from the server.

Bugfix: Don't lower case iso codes

---

src/packages/user/user-group/collection/manifests.ts
src/packages/user/user-group/collection/repository/user-group-collection.server.data-source.ts
src/packages/user/user-group/collection/types.ts
src/packages/user/user-group/collection/user-group-collection-header.element.ts
src/packages/user/user-group/collection/user-group-collection.context.ts
src/packages/user/user-group/collection/user-group-collection.element.ts
src/packages/user/user-group/collection/views/constants.ts
src/packages/user/user-group/collection/views/manifests.ts

The PR adds the search input to the user group collection.
Make sure you can search for a user group in the user group collection.

Feature: Add user group query filter

---

src/assets/lang/en-us.ts
src/assets/lang/en.ts
src/packages/core/components/input-entity/input-entity.element.ts
src/packages/core/components/input-slider/input-slider.element.ts
src/packages/core/components/stack/stack.element.ts
src/packages/core/modal/common/icon-picker/icon-picker-modal.element.ts
src/packages/core/workspace/components/workspace-breadcrumb/workspace-menu-breadcrumb/workspace-menu-breadcrumb.element.ts
src/packages/core/workspace/components/workspace-breadcrumb/workspace-variant-menu-breadcrumb/workspace-variant-menu-breadcrumb.element.ts
src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
src/packages/data-type/modals/property-editor-ui-picker/property-editor-ui-picker-modal.element.ts
src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
src/packages/documents/document-types/workspace/views/structure/document-type-workspace-view-structure.element.ts
src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
src/packages/markdown-editor/property-editors/markdown-editor/property-editor-ui-markdown-editor.element.ts
src/packages/user/current-user/theme/current-user-theme-user-profile-app.element.ts
src/packages/user/user/components/user-input/user-input.element.ts

Ah-ha! Here comes another round of **Lee's Codesweep™**! 🦄 
Various small amends, tweaks, fixes and code polish that I'd picked up on since RC3's general frontend stabilisation. 🚀
All nice to have for RC4.

Chore: Lee's code sweep (for RC4)

---

src/packages/multi-url-picker/link-picker-modal/link-picker-modal.stories.ts

Chore: fix storybook build

---

src/packages/user/user/workspace/components/user-workspace-access/user-workspace-access.element.ts
src/packages/user/user/workspace/components/user-workspace-assign-access/user-workspace-assign-access.element.ts

This PR fixes a left over after the user model updates in the management api PR #1817. I am not 100% sure why our build didn't fail because I could see the errors highlighted in VS Code when opening the file 🤔 .

Bugfix: User Access data mapping missing

---

src/packages/media/media/collection/media-collection.context.ts
src/packages/media/media/components/input-media/input-media.context.ts
src/packages/media/media/dropzone/dropzone.element.ts
src/packages/media/media/modals/media-picker/media-picker-modal.element.ts

Better thumbnail quality for big screens
Fixed a bug where sorting an item triggered the dropzone component.

Feature: Thumbnails and sorter dropzone collision

---

src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
src/packages/media/media/components/input-media/input-media.context.ts
src/packages/media/media/components/input-media/input-media.element.ts
src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
src/packages/media/media/modals/media-picker/media-picker-modal.token.ts
src/packages/media/media/modals/media-picker/types.ts
src/packages/media/media/property-editors/media-entity-picker/property-editor-ui-media-entity-picker.element.ts
src/packages/media/media/property-editors/media-picker/components/index.ts
src/packages/media/media/property-editors/media-picker/components/input-rich-media/index.ts
src/packages/media/media/property-editors/media-picker/components/input-rich-media/input-rich-media.element.ts
src/packages/media/media/property-editors/media-picker/index.ts
src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
src/packages/media/media/tree/media-tree.repository.ts
src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
src/packages/tiny-mce/plugins/tiny-mce-mediapicker.plugin.ts

Adds filter options to the Media Picker Modal
Added some of the missing configuration of Property Editor Media Picker
Media Collection now has the checkered background for transparent images 
🎉🎉

Feature: MediaPickerModal Filters & InputMedia Configuration

---

src/packages/user/current-user/repository/current-user.server.data-source.ts
src/packages/user/current-user/types.ts

Maps the `hasAccessToSensitiveData` server value to the `UmbCurrentUserModel`.

Map has access to sensitive data

---

src/packages/user/user/entity-bulk-actions/disable/disable.action.ts
src/packages/user/user/entity-bulk-actions/enable/enable.action.ts
src/packages/user/user/entity-bulk-actions/unlock/unlock.action.ts

Fixes reload of the user collection for the enable, disable, and unlock bulk actions.

Bugfix: Reload user collection on disable, enable, and unlock

---

index.html
src/apps/backoffice/components/backoffice-header-logo.element.ts
src/apps/backoffice/components/backoffice-header.element.ts
src/css/user-defined.css
src/packages/core/components/header-app/header-app-button.element.ts
src/packages/search/umb-search-header-app.element.ts
src/packages/user/current-user/current-user-header-app.element.ts
web-test-runner.config.mjs

Add a user-defined.css file to be loaded up front on the server, just as we do on the login screen. This file gives developers an easy way to add and edit variables to the backoffice.
Note: We need to load it in Index.cshtml on the server when this PR has been merged.

Feature: User defined CSS

---

src/packages/documents/documents/entity-actions/publish.action.ts
src/packages/documents/documents/entity-bulk-actions/publish/publish.action.ts

Dispatch request reload event after publish and publish bulk actions.
* Test that a collection publishing state is updated when using the bulk actions.
* Test that a collection publishing state is updated when using the tree item actions

Bugfix: request reload of entity after publish

---

src/packages/documents/documents/recycle-bin/entity-action/manifests.ts

Sets up conditions for the recycle bin entity actions:
Trash -> Permission to delete
Empty Recycle bin -> Permission to delete
Restore from Recycle bin -> Permission to move

implement user permission conditions for recycle bin entity actions

---

src/packages/core/section/section-sidebar-context-menu/section-sidebar-context-menu.element.ts

use scroll container for actions modal

---

src/assets/lang/en.ts

Adds the following missing translations en.ts
```
general_users
treeHeaders_relations
user_invite
user_usergroups
welcomeDashboard_ourUmbracoHeadline
welcomeDashboard_ourUmbracoDescription
welcomeDashboard_ourUmbracoButton
welcomeDashboard_documentationHeadline
welcomeDashboard_documentationDescription
welcomeDashboard_communityHeadline
welcomeDashboard_communityDescription
welcomeDashboard_resourcesHeadline
welcomeDashboard_resourcesDescription
welcomeDashboard_trainingHeadline
welcomeDashboard_trainingDescription 
```

Bugfix: Add missing EN translations

---

src/packages/core/tree/folder/entity-action/create-folder/create-folder.action.ts
src/packages/core/tree/folder/entity-action/delete-folder/delete-folder.action.ts
src/packages/core/tree/folder/entity-action/update-folder/update-folder.action.ts

Fixes the cyclic imports for tree folders. The actions were importing their own module. They now use a relative import instead.

Bugfix: Fix tree folder cyclic imports

---

src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts

Fixes broken build. 😖 
I'm unsure how PR #1853 got merged in, as the build was reported as broken.

Chore: Fixed up breaking-changes with modal/router imports

---

src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts

Implements the the Media info details to match v13.
Fixes
- https://github.com/umbraco/Umbraco-CMS/issues/16396

Bugfix: Media Workspace Info details

---

src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts

Updated the Markdown Editor to wire up the media URL (from the Media Picker).
I also did a code sweep over the code/markup, made some amends...
- Renamed "actions" as "toolbar"
- Used `uui-button-group` to group similar actions

Feature: Markdown Editor: Wired up media URLs

---

src/packages/language/collection/constants.ts
src/packages/language/collection/index.ts
src/packages/language/collection/manifests.ts
src/packages/language/collection/repository/constants.ts
src/packages/language/collection/repository/index.ts
src/packages/language/collection/repository/manifests.ts
src/packages/language/global-contexts/app-language.context-token.ts
src/packages/language/global-contexts/app-language.context.ts
src/packages/language/global-contexts/index.ts
src/packages/language/repository/detail/constants.ts
src/packages/language/repository/detail/index.ts
src/packages/language/repository/detail/language-detail.repository.ts
src/packages/language/repository/detail/language-detail.server.data-source.ts
src/packages/language/repository/detail/language-detail.store.context-token.ts
src/packages/language/repository/detail/language-detail.store.ts
src/packages/language/repository/detail/manifests.ts
src/packages/language/repository/item/constants.ts
src/packages/language/repository/item/index.ts
src/packages/language/repository/item/language-item.repository.ts
src/packages/language/repository/item/language-item.store.context-token.ts
src/packages/language/repository/item/language-item.store.ts
src/packages/language/repository/item/manifests.ts

Preparatory work for bundling. This PR splits the const and tokens from their implementation files.
* smoke test the language workspace

Chore: Language Split const and tokens from implementation

---

src/packages/core/components/input-with-alias/input-with-alias.element.ts
src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16412
The text for name and alias can later be localized with these keys:
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/assets/lang/en.ts#L644
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/assets/lang/en.ts#L657

Add placeholder to name input

---

src/packages/core/extension-registry/models/tree.model.ts

Allow conditions in tree manifests.

Feature: Allow conditional trees

---

src/packages/block/block-grid/property-editors/block-grid-layout-stylesheet/property-editor-ui-block-grid-layout-stylesheet.element.ts
src/packages/static-file/components/input-static-file/input-static-file.context.ts
src/packages/static-file/components/input-static-file/input-static-file.element.ts
src/packages/static-file/modals/static-file-picker-modal.token.ts
src/packages/static-file/repository/item/static-file-item.server.data-source.ts

Fixed a bug for static file picker: you can now actually pick items, and see what you picked 😊

Bugfix: Static file picker

---

src/assets/lang/da-dk.ts
src/assets/lang/en.ts
src/packages/search/search-modal/search-modal.element.ts

Fixes: https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1874
Enhances the global search with navigation tips when no search input is provided.

Bugfix: Add navigation tips to global search

---

src/packages/user/current-user/current-user.context.ts

PR: Check for backoffice path before redirect

---

src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
src/packages/media/media/entity-actions/create/media-create-options-modal.element.ts

Adds descriptions to media types and shows them in the media create options modal.
1. Add a description to a media type
2. Verify it shows up in the options dialog when creating new media content

Feature: Media Type Descriptions

---

src/external/backend-api/src/models.ts
src/mocks/data/media-type/media-type.data.ts
src/mocks/data/media-type/media-type.db.ts
src/packages/data-type/reference/index.ts
src/packages/data-type/reference/manifests.ts
src/packages/data-type/reference/repository/data-type-reference.repository.ts
src/packages/data-type/reference/repository/data-type-reference.server.data.ts
src/packages/data-type/reference/repository/index.ts
src/packages/data-type/reference/repository/manifests.ts
src/packages/data-type/workspace/views/info/data-type-workspace-view-info-reference.element.ts
src/packages/data-type/workspace/views/info/workspace-view-data-type-info.element.ts

Wires up the UI for the DataType tracked references endpoint.
This will fix https://github.com/umbraco/Umbraco-CMS/issues/16390.

Feature: DataType tracked references

---

src/packages/dictionary/components/input-dictionary/input-dictionary.context.ts

Pass the tree item model to the generic so we can remove the tsignore

Chore: remove ts ignore in UmbDictionaryPickerContext

---

src/packages/dictionary/collection/repository/manifests.ts

The PR changes the static import of the collection repo to a dynamic import

Bugfix: Lazy load Dictionary collection repo

---

src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts

Fixes an issue where a data type wouldnt show up if there was more than 100 available data types... 🤯
If you use Kenn's database, search for "e"

Bugfix: Search results for data types

---

src/packages/block/block-grid/context/block-grid-manager.context.ts
src/packages/block/block-grid/workspace/block-grid-workspace.modal-token.ts
src/packages/block/block-list/workspace/block-list-workspace.modal-token.ts
src/packages/block/block/context/block-manager.context.ts
src/packages/block/block/workspace/block-workspace.context.ts

Before this fix we always inserted block in a area and in the root. Maybe releated to Live Editing. But it made good sense looking at the code.

fix inserting block only at the right spot

---

src/packages/dictionary/entity-action/move-to/repository/dictionary-move.repository.ts
src/packages/dictionary/entity-action/move-to/repository/manifests.ts
src/packages/dictionary/repository/detail/dictionary-detail.repository.ts
src/packages/dictionary/repository/detail/dictionary-detail.store.ts
src/packages/dictionary/repository/detail/manifests.ts
src/packages/dictionary/repository/export/dictionary-export.repository.ts
src/packages/dictionary/repository/export/manifests.ts
src/packages/dictionary/repository/import/dictionary-import.repository.ts
src/packages/dictionary/repository/import/manifests.ts
src/packages/dictionary/repository/item/dictionary-item.repository.ts
src/packages/dictionary/repository/item/dictionary-item.store.ts
src/packages/dictionary/repository/item/manifests.ts
src/packages/dictionary/tree/dictionary-tree.repository.ts
src/packages/dictionary/tree/dictionary-tree.store.ts
src/packages/dictionary/tree/manifests.ts

User dynamic import of all dictionary API's instead of static imports

v14: Bugfix: lazy load all dictionary apis from manifests

---

src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts

Fixed a bug where the route would not update (render) on the initial load of the document info page.

Bugfix: Fix render of documenttype routing in info tab

---

src/packages/dictionary/modals/dictionary-picker-modal.token.ts

Use import alias instead of relative import so we don't include them in the future dictionary bundle

Chore: Use import aliases for imports in dictionary picker modal

---

src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
src/packages/documents/documents/entity-bulk-actions/manifests.ts
src/packages/media/media/entity-bulk-actions/manifests.ts
src/packages/property-editors/collection/config/bulk-action-permissions/permissions.element.ts
src/packages/property-editors/collection/config/column/column-configuration.element.ts
src/packages/property-editors/collection/config/order-by/order-by.element.ts

Updates the imports to use the import alias instead.

Chore: Change relative core collection imports to use alias

---

src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts

- Hides the extra features that are related to focalpoint in Image cropper
- Doesn't calculate focalpoint even when its hidden.

Feature: Hide focalpoint in ImageCropper

---

src/packages/core/section/section-sidebar/section-sidebar.element.ts

Fixes #https://github.com/umbraco/Umbraco-CMS/issues/16236
Adds a bit of spacing to the sidebar bottom

Bugfix: Add sidebar bottom space

---

src/packages/core/tree/folder/modal/folder-modal-element-base.ts

Focuses the name input when creating and updating a folder
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16167

Bugfix: Focus folder name input

---

src/external/backend-api/src/models.ts
src/external/backend-api/src/services.ts
src/packages/documents/document-blueprints/repository/detail/document-blueprint-detail.server.data-source.ts
src/packages/documents/document-blueprints/types.ts

Generate new models and add `template` to the blueprint model. I am a little unsure of this since the `template` is not returned from the server in the details request anyway.

Server models 2024-05-31

---

src/assets/lang/en-us.ts
src/assets/lang/en.ts

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16519

Bugfix: Remove of in translation

---

.eslintrc.json
package-lock.json
package.json
src/packages/dictionary/package.json
src/packages/dictionary/vite.config.ts
src/packages/webhook/package.json
src/packages/webhook/vite.config.ts
src/vite-config-base.ts

See #1977 for more details about the bundling changes.
This PR adds bundling for the webhook package.

Chore: Bundling of the Webhook package

---

src/packages/media/media/collection/media-collection.element.ts
src/packages/media/media/dropzone/dropzone-manager.class.ts

Fixed a bug when dropping a media (in a folder) into the dropzone, it would upload the item in the root, rather than in the folder it was dragged into.
Fixed a bug where the media tree did not update when a file was uploaded via dropzone
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16524

upload to correct folder when dropping file

---

src/packages/core/tree/entity-actions/duplicate-to/modal/duplicate-to-modal.element.ts
src/packages/documents/documents/entity-actions/duplicate/modal/duplicate-document-modal.element.ts

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16098

Bugfix: Disable duplicate button when nothing is selected

---

src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
src/packages/media/media/entity-actions/create/media-create-options-modal.element.ts

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16489

Bugfix: Add missing edit permissions for create options modals

---

src/packages/user/user-group/components/input-user-group/user-group-input.element.ts
src/packages/user/user/components/user-document-start-node/user-document-start-node.element.ts
src/packages/user/user/components/user-media-start-node/user-media-start-node.element.ts
src/packages/user/user/workspace/components/user-workspace-access/user-workspace-access.element.ts

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16522

Bugfix: user startnode and user group links

---

src/packages/templating/templates/modals/query-builder/query-builder-filter.element.ts

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16457

Bugfix: Query Builder sending previous data

---

src/assets/lang/en-us.ts
src/assets/lang/en.ts

localization updates on en.ts and en-us.ts files
- [x ] Bug fix (non-breaking change which fixes an issue)

Dictionary Section got wrong name in header

---

package-lock.json
package.json

There is some good new features with TypeScript 5.5 that I would like to us get in.
Generally better type checking :-)

Upgrade to typescript 5.5

---

src/packages/block/block-grid/components/block-grid-area-config-entry/workspace/block-grid-area-type-workspace.context.ts
src/packages/block/block/conditions/block-workspace-has-settings.condition.ts
src/packages/block/block/context/block-entries.context.ts
src/packages/block/block/context/block-entry.context.ts
src/packages/block/block/manifests.ts
src/packages/block/block/workspace/block-element-manager.ts
src/packages/block/block/workspace/block-element-property-dataset.context-token.ts
src/packages/block/block/workspace/block-element-property-dataset.context.ts
src/packages/block/block/workspace/block-workspace.context-token.ts
src/packages/block/block/workspace/block-workspace.context.ts
src/packages/block/block/workspace/manifests.ts
src/packages/block/block/workspace/views/edit/block-workspace-view-edit-properties.element.ts
src/packages/block/block/workspace/views/edit/block-workspace-view-edit-tab.element.ts
src/packages/block/block/workspace/views/edit/block-workspace-view-edit.element.ts
src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts

Block Editors: only show settings when available in block workspace

---

src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts

reintroduce redirects in workspace

---

src/packages/core/section/section-sidebar/section-sidebar.element.ts

This context is removed by mistake. The tree context menu does not open when clicking the `...` on a menu item.

Bugfix: Add back sidebar context

---

package-lock.json
package.json
src/packages/property-editors/index.ts
src/packages/property-editors/package.json
src/packages/property-editors/vite.config.ts

This PR bundles the Property Editors Package including all modules.

Chore: Bundling Property Editors package

---

src/assets/lang/es-es.ts

Translate package section to español

Translate package section to español

---

package-lock.json
package.json

Chore: Update UUI Library to version 1.9.0-rc.2

---

src/packages/core/workspace/components/workspace-action/common/submit/submit.action.ts
src/packages/core/workspace/contexts/tokens/variant-dataset-workspace-context.interface.ts
src/packages/documents/document-blueprints/workspace/manifests.ts

Removes a few older interfaces that were deprecated before the RC.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16689

Chore: Remove interfaces deprecated before the RC

---

.github/README.md
sonar-project.properties

build: add sonar-project.properties to account for what are sources and test files

---

src/packages/core/culture/repository/culture.repository.ts
src/packages/core/culture/repository/manifests.ts
src/packages/core/modal/common/embedded-media/repository/manifests.ts
src/packages/core/modal/common/embedded-media/repository/oembed.repository.ts

I had an outstanding task to make sure all repositories and stores are lazy-loaded.
I found a couple of missed repositories, everything else is being lazy-loaded.

Chore: Lazy-load missed repositories

---

examples/block-custom-view/README.md
examples/block-custom-view/block-custom-view.ts
examples/block-custom-view/index.ts

Example of custom view for Block Editor

Feature: example custom view

---

src/packages/core/extension-registry/conditions/manifests.ts
src/packages/core/extension-registry/conditions/menu-alias.condition.ts
src/packages/core/extension-registry/conditions/multiple-app-languages.condition.ts
src/packages/core/extension-registry/conditions/section-alias.condition.ts
src/packages/core/extension-registry/conditions/types.ts
src/packages/language/app-language-select/manifests.ts
src/packages/language/global-contexts/app-language.context.ts

Only shows App Language Selector when more than one app language available.

multiple-app-languages-condition

---

src/apps/backoffice/backoffice.context.ts

correct name

---

src/packages/documents/documents/workspace/document-workspace.context.ts

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16498

Bugfix: Set trashed context when creating a new item

---

package-lock.json
package.json
src/packages/log-viewer/package.json
src/packages/log-viewer/vite.config.ts

This PR bundles the Log Viewer Package including all modules.

Chore: Bundle Log Viewer Package

---

package-lock.json
package.json
src/packages/relations/index.ts
src/packages/relations/package.json
src/packages/relations/relation-types/collection/constants.ts
src/packages/relations/relation-types/collection/index.ts
src/packages/relations/relation-types/collection/manifests.ts
src/packages/relations/relation-types/collection/repository/constants.ts
src/packages/relations/relation-types/collection/repository/index.ts
src/packages/relations/relation-types/collection/repository/manifests.ts
src/packages/relations/relation-types/repository/detail/constants.ts
src/packages/relations/relation-types/repository/detail/index.ts
src/packages/relations/relation-types/repository/detail/manifests.ts
src/packages/relations/vite.config.ts

This PR bundles the Relations Package including all modules.

Chore: Bundle Relations Package

---

package-lock.json
package.json
src/packages/ufm/package.json
src/packages/ufm/vite.config.ts

This PR bundles the UFM Package including all modules.

Chore: Bundle UFM Package

---

src/packages/members/member-group/index.ts
src/packages/members/member/index.ts

Exports the Member and Member Group Collection modules

Feature: Export member and member group collection module

---

src/packages/core/workspace/components/workspace-action/common/submit/submit.action.ts

This PR adds back the reexport of UmbSaveWorkspaceAction

Hotfix: Add back reexport of UmbSaveWorkspaceAction

---

.github/RELEASE_INSTRUCTION.md
src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts

> [!IMPORTANT]  
> Rember to restore the release branch after the merge

Merge Release 14.2 branch into main

---

package-lock.json
package.json

Bumps the `package.json` version number to 14.3

Chore: Bump version to 14.3

---

src/packages/property-editors/checkbox-list/components/input-checkbox-list/input-checkbox-list.element.ts
src/packages/property-editors/checkbox-list/manifests.ts
src/packages/property-editors/checkbox-list/property-editor-ui-checkbox-list.element.ts

This PR adds `readonly` mode to the Checkbox List Property Editor UI

Feature: Readonly mode for Checkbox List Property Editor UI

---

src/packages/block/block-grid/components/block-grid-block-inline/block-grid-inline-property-dataset.context.ts
src/packages/block/block/workspace/block-element-property-dataset.context.ts
src/packages/core/content/property-dataset-context/content-property-dataset.context.ts
src/packages/core/property/property-dataset/property-dataset-base-context.ts
src/packages/core/property/property-dataset/property-dataset-context.interface.ts
src/packages/core/property/property/property.context.ts
src/packages/core/workspace/workspace-property-dataset/invariant-workspace-property-dataset-context.ts

V14: Rename readonly of Property Datatsets

---

src/packages/user/user/client-credential/create/modal/create-user-client-credential-modal.element.ts

Adds validator for client id pattern

Add client credential id pattern validation

---

src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts

Add null check before passing search config to the tree

Bugfix: add null check before passing search config

---

src/packages/user/current-user/profile/edit-current-user.action.ts
src/packages/user/user/index.ts

Updates current user edit path to new navigation structure

Bugfix: update current user edit path to new navigation structure

---

src/packages/rte/tiptap/extensions/code-editor.extension.ts
src/packages/rte/tiptap/extensions/manifests.ts
src/packages/rte/tiptap/extensions/tiptap-toolbar-button.element.ts

to edit the HTML source of the RTE
Press the `<>` button to view the HTML source, edit the markup, press Submit, the editor will be updated accordingly.

Tiptap extension: Code Editor

---

src/packages/code-editor/code-editor-modal/code-editor-modal.element.ts
src/packages/code-editor/code-editor-modal/code-editor-modal.stories.ts
src/packages/code-editor/code-editor-modal/code-editor-modal.token.ts
src/packages/code-editor/code-editor-modal/index.ts
src/packages/code-editor/code-editor-modal/manifests.ts
src/packages/code-editor/index.ts
src/packages/code-editor/manifests.ts
src/packages/core/modal/common/manifests.ts
src/packages/core/modal/token/index.ts
src/packages/tiny-mce/plugins/tiny-mce-code-editor.plugin.ts

Moves code editor modal + tokens and types into code editor module.

Fix: move code editor modal

---

src/packages/core/manifests.ts
src/packages/core/modal/common/confirm/confirm-modal.controller.ts
src/packages/core/modal/common/confirm/confirm-modal.token.ts
src/packages/core/modal/common/confirm/index.ts
src/packages/core/modal/common/confirm/manifests.ts
src/packages/core/modal/common/index.ts
src/packages/core/modal/common/item-picker/index.ts
src/packages/core/modal/common/item-picker/item-picker-modal.token.ts
src/packages/core/modal/common/item-picker/manifests.ts
src/packages/core/modal/common/manifests.ts
src/packages/core/modal/index.ts
src/packages/core/modal/manifests.ts
src/packages/core/modal/token/index.ts
src/packages/documents/documents/user-permissions/input-document-granular-user-permission/input-document-granular-user-permission.element.ts
src/packages/user/user-permission/index.ts
src/packages/user/user-permission/modals/index.ts
src/packages/user/user-permission/modals/manifests.ts
src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.element.ts
src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.token.ts
src/packages/user/user-permission/modals/settings/index.ts
src/packages/user/user-permission/modals/settings/manifests.ts

**From**
`import { UMB_ENTITY_USER_PERMISSION_MODAL } from '@umbraco-cms/backoffice/modal';`
**To**
`import { UMB_ENTITY_USER_PERMISSION_MODAL } from '@umbraco-cms/backoffice/user-permission';`

Fix: move user permission settings token

---

src/packages/block/block-rte/tiptap-extension/manifests.ts
src/packages/rte/tiptap/extensions/manifests.ts
src/packages/rte/tiptap/extensions/tiptap-toolbar-extension.ts
src/packages/rte/tiptap/extensions/toolbar/manifests.ts
src/packages/rte/tiptap/property-editors/property-editor-ui-tiptap-toolbar-configuration.element.ts

Adds a default set of toolbar items
Also adds title attribute to toolbar items
Default selection:

add defaults and title

---

src/packages/block/modals/manifest-viewer/manifest.ts
src/packages/core/auth/modals/manifests.ts
src/packages/core/content-type/modals/composition-picker/manifest.ts
src/packages/core/extension-registry/interfaces/index.ts
src/packages/core/extension-registry/models/index.ts
src/packages/core/modal/component/modal-base.element.ts
src/packages/core/modal/component/modal.element.ts
src/packages/core/modal/extensions/index.ts
src/packages/core/modal/extensions/modal-extension-element.interface.ts
src/packages/core/modal/extensions/modal.extension.ts
src/packages/core/modal/types.ts
src/packages/core/server-file-system/rename/modal/manifests.ts
src/packages/core/tree/entity-actions/duplicate-to/modal/manifests.ts
src/packages/core/tree/entity-actions/sort-children-of/modal/manifests.ts
src/packages/documents/document-types/entity-actions/import/modal/manifests.ts
src/packages/documents/documents/entity-actions/duplicate/modal/manifests.ts
src/packages/documents/documents/entity-actions/notifications/modal/manifests.ts
src/packages/documents/documents/modals/manifests.ts
src/packages/documents/documents/rollback/modal/manifests.ts
src/packages/media/media-types/entity-actions/import/modal/manifests.ts
src/packages/media/media/modals/image-cropper-editor/manifests.ts
src/packages/media/media/modals/media-picker/manifests.ts
src/packages/members/member/entity-actions/create/manifests.ts
src/packages/templating/modals/manifests.ts
src/packages/user/current-user/external-login/manifests.ts

Types moved from `@umbraco-cms/backoffice/extension-registry` to `@umbraco-cms/backoffice/modal:`
- `ManifestModal`

Extension Manifest Map: modal

---

src/packages/core/extension-registry/models/index.ts
src/packages/user/current-user/action/current-user-app-button.element.ts
src/packages/user/current-user/current-user-action.extension.ts
src/packages/user/current-user/external-login/configure-external-login-providers-action.ts
src/packages/user/current-user/index.ts
src/packages/user/current-user/mfa-login/configure-mfa-providers-action.ts
src/packages/user/current-user/profile/change-password-current-user.action.ts
src/packages/user/current-user/profile/edit-current-user.action.ts
src/packages/user/current-user/user-profile-app.extension.ts

Types moved from `@umbraco-cms/backoffice/extension-registry` to `@umbraco-cms/backoffice/current-user`:
- `ManifestUserProfileApp `
- `ManifestCurrentUserAction`

 Extension Manifest Map: User Profile App + Current User Action

---

src/packages/templating/templates/workspace/template-workspace.context.ts

Re-introducing some code that had been removed.

Bug: re-implement master template state

---

src/packages/core/utils/debounce/debounce.function.test.ts

Adds tests for the debounce function

Chore: Add unit tests for the debounce function

---

src/packages/block/block/workspace/block-element-manager.ts
src/packages/core/content-type/components/property-type-based-property/property-type-based-property.element.ts
src/packages/core/property/property/property.context.ts
src/packages/core/property/property/property.element.ts

Just some clean up from investigation work.

Chore: Property Type Clean up

---

src/packages/core/collection/components/collection-toolbar.element.ts
src/packages/dictionary/collection/dictionary-collection.element.ts
src/packages/dictionary/collection/manifests.ts

Adds search bar to translations/dictionary.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17101

Feature: Dictionary Searchbar

---

src/packages/dictionary/manifests.ts
src/packages/dictionary/search/constants.ts
src/packages/dictionary/search/dictionary-search.repository.ts
src/packages/dictionary/search/dictionary-search.server.data-source.ts
src/packages/dictionary/search/dictionary.search-provider.ts
src/packages/dictionary/search/index.ts
src/packages/dictionary/search/manifests.ts

Adds the missing `Dictionary` button to search

Feature: Adds the missing dictionary to search

---

src/packages/core/icon-registry/icon-dictionary.json
src/packages/core/icon-registry/icons.ts
src/packages/core/icon-registry/icons/icon-document-3d.ts
src/packages/core/icon-registry/icons/icon-document-chart-bar.ts
src/packages/core/icon-registry/icons/icon-document-chart-graph.ts
src/packages/core/icon-registry/icons/icon-document-command.ts
src/packages/core/icon-registry/icons/icon-document-font.ts
src/packages/core/icon-registry/icons/icon-document-html.ts
src/packages/core/icon-registry/icons/icon-document-image.ts
src/packages/core/icon-registry/icons/icon-document-js.ts
src/packages/core/icon-registry/icons/icon-document-key.ts
src/packages/core/icon-registry/icons/icon-document-medal.ts
src/packages/core/icon-registry/icons/icon-document-play.ts
src/packages/core/icon-registry/icons/icon-document-search.ts
src/packages/core/icon-registry/icons/icon-document-settings.ts
src/packages/core/icon-registry/icons/icon-document-spreadsheet.ts
src/packages/core/icon-registry/icons/icon-document-user.ts
src/packages/documents/document-types/entity-actions/create/modal/document-type-create-options-modal.element.ts
src/packages/documents/document-types/workspace/document-type-workspace.context.ts
src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
src/packages/templating/partial-views/entity-actions/create/options-modal/partial-view-create-options-modal.element.ts
src/packages/templating/partial-views/entity-actions/create/snippet-modal/create-from-snippet-modal.ts
src/packages/templating/partial-views/tree/partial-view-tree.server.data-source.ts
src/packages/templating/scripts/entity-actions/create/options-modal/script-create-options-modal.element.ts
src/packages/templating/scripts/tree/script-tree.server.data-source.ts
src/packages/templating/stylesheets/entity-actions/create/options-modal/stylesheet-create-options-modal.element.ts
src/packages/templating/stylesheets/tree/stylesheet-tree.server.data-source.ts
src/packages/templating/templates/global-components/template-card/template-card.element.ts
src/packages/templating/templates/tree/template-tree.server.data-source.ts

This PR updates and aligns icons for templates, partial views, stylesheets, and js.

Hotfix: Align templating icons

---

src/packages/documents/documents/workspace/document-workspace.context.ts

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16371
Do not include 'invariant'-culture in the preview URL when the document can't vary.

Hotfix: Invariant preview url

---

examples/block-custom-view/block-custom-view.ts
examples/block-custom-view/index.ts
src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts

Just a minor update on example and comment

Chore: Block Custom View — update comment and example

---

src/assets/lang/en-us.ts
src/packages/core/collection/default/collection-default.context.ts
src/packages/core/collection/default/collection-default.element.ts
src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
src/packages/media/media/collection/views/table/media-table-collection-view.element.ts

Implements an empty state across all collections
Example:
**Before:**
**After**

Bugfix: Collection empty state

---

.storybook/preview.js

Excludes decorators from source blocks in storybook.
Adds formatting to source blocks

Bugfix: Storybook - Add source block formatting and exclude decorators

---

src/packages/core/validation/controllers/validation.controller.ts

Chore: simplify code

---

src/packages/block/block-grid/context/block-grid-manager.context.ts
src/packages/block/block-list/context/block-list-entries.context.ts
src/packages/block/block-list/context/block-list-manager.context.ts
src/packages/block/block-rte/context/block-rte-entries.context.ts
src/packages/block/block-rte/context/block-rte-manager.context.ts
src/packages/block/block/context/block-manager.context.ts
src/packages/block/block/workspace/block-workspace.context.ts

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17282

Bugfix: Variant Blocks create duplicates in the frontend when created in an area

---

src/packages/documents/documents/property-dataset-context/index.ts
src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts

This PR fixes a couple of smaller issues around the variant publication state:
* Shows "Not created" state when a document or variant is not created
* Show the "Published (pending changes)" state when a document has pending changes.
* Hides the create date when a document is not created
* Only shows info for the current variant.
Partial fix towards resolving https://github.com/umbraco/Umbraco-CMS/issues/17240

Hotfix: document variant publication info

---

src/packages/language/global-contexts/app-language.context.ts

Saves the last selected app language in local storage so it will be remembered after a page refresh.

Feature: save selected app language in local storage

---

src/libs/extension-api/registry/extension.registry.ts
src/packages/core/extension-registry/registry.ts

Fixes so you get a true picture of your config options when appending conditions to other conditions.

Feat: condition config types as a generic for extension registry

---

src/libs/controller-api/controller-host.mixin.ts
src/libs/extension-api/controller/base-extension-initializer.controller.ts
src/packages/core/extension-registry/components/extension-slot/extension-slot.element.ts

Remove attached on destroy

---

src/packages/media/imaging/components/index.ts
src/packages/media/imaging/components/media-image.element.ts
src/packages/media/imaging/imaging.repository.ts
src/packages/media/imaging/imaging.server.data.ts
src/packages/media/imaging/imaging.store.ts
src/packages/media/imaging/types.ts

The initial work for a media image component, which can be used to show a image from a media item. Eventually be used in custom views in Blocks.

Feature: initial work on media image component
